Repository NLog/NLog, pull requests merged in 2018-10, with the labels that each got.

#2942 UnixMultiProcessFileAppender - Added missing SecuritySafeCritical
  src/NLog/Internal/FileAppenders/UnixMultiProcessFileAppender.cs
Labels: enhancement

#2934 CsvLayout - Performance&docs improvements, added Quoting also on Column.
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/Internal/StringBuilderPool.cs
  src/NLog/Layouts/CsvColumn.cs
  src/NLog/Layouts/CsvLayout.cs
  src/NLog/Layouts/CsvQuotingMode.cs
  tests/NLog.UnitTests/Layouts/CsvLayoutTests.cs
Labels: csv-layout, feature, performance

#2940 JSON encoding should create valid JSON for string dictionary-keys
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: enhancement, json / json-layout

#2949 MappedDiagnosticsLogicalContext - SetScoped with IReadOnlyList
  src/NLog/MappedDiagnosticsLogicalContext.cs
  tests/NLog.UnitTests/Contexts/MappedDiagnosticsLogicalContextTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: enhancement, performance

#2972 DatabaseTarget - Auto Load System.Data.Odbc for DbProvider=ODBC/SYSTEM.DATA.ODBC
  src/NLog/Targets/DatabaseTarget.cs
Labels: database-target, feature

#2979 NetCore Native reflection works better when attributes are allocated
  src/NLog/Internal/PropertyHelper.cs
Labels: enhancement

#2978 ExceptionLayoutRenderer - Skip "One or more errors occurred" for a AggregateException with a single exception
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  src/NLog/LayoutRenderers/MessageLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
  tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs
Labels: enhancement

#2971 ConfigurationItemFactory - Skip unneeded RegisterExtendedItems on .NET Core
  src/NLog/Config/ConfigurationItemFactory.cs
Labels: enhancement, performance

#2974 Feature/update resharper annotations
  src/NLog/Annotations.cs
  src/NLog/Config/ArrayParameterAttribute.cs
  src/NLog/Config/DefaultParameterAttribute.cs
  src/NLog/Config/NLogConfigurationItemAttribute.cs
  src/NLog/Config/NameBaseAttribute.cs
  src/NLog/Config/RequiredParameterAttribute.cs
Labels: enhancement
