Repository NLog/NLog, pull requests merged in 2018-12, with the labels that each got.

#3035 TargetWithContext - GetAllProperties should initialize dictionary capacity
  src/NLog/Targets/TargetWithContext.cs
Labels: performance

#3047 FileTarget- Make AutoClosingTimerCallback more relaxed when file path problems
  src/NLog/Targets/FileTarget.cs
Labels: enhancement, file-target

#3045 Create snupkg packages and use portable PDB
  appveyor.yml
  build.ps1
  src/NLog/NLog.csproj
Labels: build-config, feature

#3060 TargetWithContext: support for IRawValue
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/SimpleLayout.cs
  src/NLog/Targets/TargetPropertyWithContext.cs
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
  tools/CheckSourceCode/NLog.SourceCodeTests.exe.config
Labels: enhancement

#3061 TempDirLayoutRenderer - Avoid exception on static class initialization
  src/NLog/Config/Factory.cs
  src/NLog/Internal/NetworkSenders/HttpNetworkSender.cs
  src/NLog/LayoutRenderers/TempDirLayoutRenderer.cs
Labels: enhancement

#3050 Added IncludeGdc property in JsonLayout
  src/NLog/Layouts/JsonLayout.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
Labels: feature

#3017 Improve EventLogTarget installation logic - handle MaximumKilobytes for apps without elevated privileges
  src/NLog/Targets/EventLogTarget.cs
  tests/NLog.UnitTests/Targets/EventLogTargetTests.cs
Labels: enhancement, event-log-target, has unittests
