Repository NLog/NLog, pull requests merged in 2018-11, with the labels that each got.

#2986 Ignore DateArchive_UsesDateFromCurrentTimeSource on Travis with NetCore
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: hotfix

#2987 JSON encoding should create valid JSON for non-string dictionary-keys
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTests.cs
Labels: hotfix

#2988 NullAppender - Added missing SecuritySafeCritical
  src/NLog/Internal/FileAppenders/NullAppender.cs
  src/NLog/Internal/FileAppenders/UnixMultiProcessFileAppender.cs
Labels: enhancement, hotfix

#2985 LogBuilder - Fluent assignment of message-template after properties
  src/NLog/LayoutRenderers/AllEventPropertiesLayoutRenderer.cs
  src/NLog/LogEventInfo.cs
  tests/NLog.UnitTests/Fluent/LogBuilderTests.cs
Labels: hotfix

#2907 New Substring, Left & Right Wrappers
  src/NLog/LayoutRenderers/Wrappers/LeftLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/RightLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/SubstringLayoutRendererWrapper.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/LeftLayoutRendererWrapperTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/RightLayoutRendererWrapperTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/SubstringLayoutRendererWrapperTests.cs
Labels: feature, needs documentation on wiki, needs documention on nlog-project.org/config

#2670 XmlLayout - Render LogEventInfo.Properties as XML
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/Internal/XmlHelper.cs
  src/NLog/LayoutRenderers/Wrappers/TrimWhiteSpaceLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/XmlEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/XmlAttribute.cs
  src/NLog/Layouts/XmlLayout.cs
  tests/NLog.UnitTests/Layouts/XmlLayoutTests.cs
  tools/DumpApiXml/DocFileBuilder.cs
Labels: feature

#2983 JsonSerializer - Use ReferenceEquals instead of object.Equals
  src/NLog/Internal/SingleItemOptimizedHashSet.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTests.cs
Labels: json / json-layout

#2991 SubstringLayoutRenderer - Fixed bug when Start is higher than actual length + improve tests
  src/NLog/LayoutRenderers/Wrappers/SubstringLayoutRendererWrapper.cs
  tests/NLog.UnitTests/AssemblyInfo.cs
  tests/NLog.UnitTests/AsyncHelperTests.cs
  tests/NLog.UnitTests/Config/DuplicateConfigurationAttributeTests.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
  tests/NLog.UnitTests/GetLoggerTests.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
  tests/NLog.UnitTests/Internal/ExceptionHelperTests.cs
  tests/NLog.UnitTests/Internal/LayoutHelpersTests.cs
  tests/NLog.UnitTests/LayoutRenderers/FileContentsTests.cs
  tests/NLog.UnitTests/LayoutRenderers/IdentityTests.cs
  tests/NLog.UnitTests/LayoutRenderers/RegistryTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutOutputTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
  tests/NLog.UnitTests/LogFactoryTests.cs
  tests/NLog.UnitTests/LogManagerTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
  tests/NLog.UnitTests/Targets/ConcurrentFileTargetTests.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
  tests/NLog.UnitTests/Targets/EventLogTargetTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
  tests/NLog.UnitTests/Targets/MailTargetTests.cs
  tests/NLog.UnitTests/Targets/MessageQueueTargetTests.cs
  tests/NLog.UnitTests/Targets/MethodCallTests.cs
  tests/NLog.UnitTests/Targets/TargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/BufferingTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/FallbackGroupTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/RepeatingTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/WrapperTargetBaseTests.cs
Labels: never-released bug

#2994 LogBuilder - Support Fluent API where message-template (Fix bug)
  src/NLog/LogEventInfo.cs
Labels: bug, never-released bug

#2993 Version 4.5.11
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version

#2996 Improve null handling and annotations for LogEventInfo
  src/NLog/LogEventInfo.cs
Labels: enhancement

#3008 Better checks and error handling when applying xml variables
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationParser.cs
Labels: enhancement, nlog-configuration

#3015 Refactor: MappedDiagnosticsLogicalContext.Dispose
  src/NLog/MappedDiagnosticsLogicalContext.cs
Labels: refactoring

#3013 Removed use of lock(this), removed dead code
  src/NLog/Common/LogEventInfoBuffer.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/MultiFileWatcher.cs
  src/NLog/Internal/NetworkSenders/TcpNetworkSender.cs
  src/NLog/Internal/NetworkSenders/UdpNetworkSender.cs
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/Internal/TimeoutContinuation.cs
  src/NLog/LayoutRenderers/FileContentsLayoutRenderer.cs
  src/NLog/Layouts/SimpleLayout.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/Wrappers/AsyncRequestQueue-T.cs
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
  src/NLog/Targets/Wrappers/RandomizeGroupTarget.cs
Labels: refactoring

#3014 XmlLayout - Added object reflection using ObjectReflectionCache
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/Layouts/JsonLayout.cs
  src/NLog/Layouts/XmlLayout.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Layouts/XmlLayoutTests.cs
Labels: enhancement

#2941 TargetWithContext - Include all properties even when duplicate names (rename with postfix: _1, _2 etc)
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
Labels: feature

#3010 Small refactorings
  src/NLog.Extended/LayoutRenderers/AppSettingLayoutRenderer.cs
  src/NLog.sln.DotSettings
  src/NLog/Common/AsyncHelpers.cs
  src/NLog/Common/ConversionHelpers.cs
  src/NLog/Common/InternalLogger.cs
  src/NLog/Conditions/ConditionAndExpression.cs
  src/NLog/Conditions/ConditionOrExpression.cs
  src/NLog/Conditions/ConditionTokenizer.cs
  src/NLog/Config/ConfigurationItemCreator.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/ExceptionRenderingFormat.cs
  src/NLog/Config/INamedItemFactory.cs
  src/NLog/Config/InstallationContext.cs
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/NLogXmlElement.cs
  src/NLog/GlobalDiagnosticsContext.cs
  src/NLog/ILoggerExtensions.cs
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/Internal/StringHelpers.cs
  src/NLog/LayoutRenderers/Wrappers/CachedLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WrapperLayoutRendererBuilderBase.cs
  src/NLog/Layouts/JsonLayout.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/SimpleLayout.cs
  src/NLog/MappedDiagnosticsContext.cs
  src/NLog/MappedDiagnosticsLogicalContext.cs
  src/NLog/NullLogger.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/DebuggerTarget.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/WebServiceTarget.cs
  tests/NLog.UnitTests/Internal/NetworkSenders/TcpNetworkSenderTests.cs
  tests/NLog.UnitTests/LogManagerTests.cs
  tests/NLog.UnitTests/Targets/MethodCallTests.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
Labels: refactoring

#3027 Recognize Utf8 without hyphen as valid Encoding
  src/NLog/Internal/PropertyHelper.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
Labels: feature
