Repository NLog/NLog, pull requests merged in 2018-02, with the labels that each got.

#2568 WebServiceTarget - Rollback added Group-Layout
  src/NLog/Targets/MethodCallParameter.cs
  src/NLog/Targets/MethodCallTargetBase.cs
  src/NLog/Targets/WebServiceTarget.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
Labels: enhancement

#2555 JsonLayout - Use capturetype and added MaxRecursionLimit and set default to 0
  src/NLog/Internal/Fakeables/FakeAppDomain.cs
  src/NLog/Internal/PropertiesDictionary.cs
  src/NLog/Layouts/JsonAttribute.cs
  src/NLog/Layouts/JsonLayout.cs
  src/NLog/MessageTemplates/CaptureType.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/JsonSerializeOptions.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
  tests/NLog.UnitTests/LoggerTests.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTests.cs
Labels: discussion, enhancement, needs documentation on wiki

#2542 Added TooManyStructuredParametersShouldKeepBeInParamList testcase
  tests/NLog.UnitTests/LoggerTests.cs
Labels: test

#2571 4.5 rc5 version and release notes
  build.ps1
  src/NLog/NLog.csproj
Labels: build-config, documentation

#2580 ColoredConsoleTarget.cs: Fix typo
  src/NLog/Targets/ColoredConsoleTarget.cs
Labels: documentation

#2576 Fix possible infinite loop in message template parser + better handling incorrect templates
  src/NLog/MessageTemplates/MessageTemplateParameters.cs
  tests/NLog.UnitTests/MessageTemplates/MessageTemplateParametersTests.cs
Labels: bug, has unittests

#2581 MessageTemplateParameter(s) ctors to internal
  src/NLog/MessageTemplates/MessageTemplateParameter.cs
  src/NLog/MessageTemplates/MessageTemplateParameters.cs
Labels: enhancement

#2585 NLog 4.5 rc6 version and changelog
  build.ps1
  src/NLog/NLog.csproj
Labels: build-config, documentation

#2584 ColoredConsoleTarget.cs: Whitespace cleanups
  src/NLog/Targets/ColoredConsoleTarget.cs
Labels: enhancement

#2596 LogFactory - Assign Configuration should only perform a single InitializeAll
  src/NLog/LogFactory.cs
Labels: enhancement

#2601 Changelog NLog 4.4.13
  CHANGELOG.md
Labels: documentation

#2600 Fix 'System.ReadOnlySpan`1[System.Char]' cannot be converted to type 'System.String'.
  appveyor.yml
  src/NLog/Internal/PropertyHelper.cs
Labels: bug

#2603 MultiFileWatcher - Improve error handling if FileSystemWatcher fails
  src/NLog/Internal/MultiFileWatcher.cs
Labels: enhancement, nlog-configuration
