Repository NLog/NLog, pull requests merged in 2018-07, with the labels that each got.

#2788 ${Assembly-version} make GetAssembly protected and virtual
  src/NLog/LayoutRenderers/AssemblyVersionLayoutRenderer.cs
  src/NLogAutoLoadExtension/NLogAutoLoadExtension.csproj
  src/NLogAutoLoadExtension/Properties/AssemblyInfo.cs
  tests/NLog.UnitTests/LayoutRenderers/AssemblyVersionTests.cs
Labels: enhancement

#2763 Throw better error when target name is null
  src/NLog/Config/LoggingConfiguration.cs
Labels: enhancement, nlog-configuration

#2761 ${Callsite} fix class naming when includeNamespace=false and cleanNamesOfAnonymousDelegates=true
  src/NLog/Internal/StackTraceUsageUtils.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteTests.cs
Labels: bug

#2776 FileTarget - Introduced OpenFileFlushTimeout to help when AutoFlush = false
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/CountingSingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/FileAppenders/ICreateFileParameters.cs
  src/NLog/Internal/FileAppenders/MutexMultiProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/NullAppender.cs
  src/NLog/Internal/FileAppenders/RetryingMultiProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/SingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/UnixMultiProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Internal/FileAppenders/FileAppenderCacheTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteTests.cs
  tests/NLog.UnitTests/LayoutRenderers/IdentityTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: enhancement, file-target, performance

#2797 Better performance with Activator.CreateInstance
  src/NLog/Internal/FactoryHelper.cs
Labels: performance

#2804 FileTarget - Do not trust Last File Write TimeStamp when AutoFlush=false
  src/NLog/Internal/FileAppenders/SingleProcessFileAppender.cs
  src/NLog/Targets/FileTarget.cs
Labels: enhancement, file-target

#2792 OutputDebugStringTarget - Support Xamarin iOS and Android
  src/NLog/Targets/OutputDebugStringTarget.cs
Labels: Xamarin, feature

#2807 Fix XML documentation for partial class Logger
  src/NLog/Logger-Conditional.cs
Labels: documentation

#2808 Version 4.5.7
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version
