Repository NLog/NLog, pull requests merged in 2018-04, with the labels that each got.

#2637 Fix IndexOutOfRangeException in NestedDiagnosticsLogicalContext
  src/NLog/NestedDiagnosticsLogicalContext.cs
  tests/NLog.UnitTests/LayoutRenderers/NDLCTests.cs
Labels: bug

#2628 RoundRobinGroupTarget - Replaced lock with Interlocked for performance
  src/NLog/Targets/Wrappers/RoundRobinGroupTarget.cs
Labels: performance

#2638 Handle null values correctly in LogReceiverSecureService
  src/NLog/Targets/LogReceiverWebServiceTarget.cs
  tests/NLog.UnitTests/LogReceiverService/LogReceiverServiceTests.cs
Labels: bug

#2640 FileTarget - InitializeFile no longer need justData parameter + dispose fileapenders earlier
  src/NLog/Targets/FileTarget.cs
Labels: file-target, performance, refactoring

#2639 MessageTemplates - Optimize ParseHole for positional templates
  src/NLog/MessageTemplates/TemplateEnumerator.cs
Labels: performance

#2642 FileTarget - InitializeFile should skip dictionary lookup when same file
  src/NLog/Targets/FileTarget.cs
Labels: file-target, performance

#2645 Minor performance optimization of some layoutrenderers
  src/NLog/LayoutRenderers/CallSiteLayoutRenderer.cs
  src/NLog/LayoutRenderers/CallSiteLineNumberLayoutRenderer.cs
  src/NLog/LayoutRenderers/LevelLayoutRenderer.cs
  src/NLog/LayoutRenderers/ProcessTimeLayoutRenderer.cs
  src/NLog/LayoutRenderers/SequenceIdLayoutRenderer.cs
Labels: performance

#2644 FallbackGroupTarget: handle async state on fallback correctly
  src/NLog/Targets/Wrappers/FallbackGroupTarget.cs
  tests/NLog.UnitTests/Targets/Wrappers/FallbackGroupTargetTests.cs
Labels: bug, enhancement

#2648 ${processtime} and ${time} added invariant option
  src/NLog/LayoutRenderers/ProcessTimeLayoutRenderer.cs
  src/NLog/LayoutRenderers/TimeLayoutRenderer.cs
Labels: feature

#2643 UWP with NetStandard2 on Net Native does not support Assembly.CodeBase + Handle native methods in StackTrace
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Internal/StackTraceUsageUtils.cs
  src/NLog/LayoutRenderers/StackTraceLayoutRenderer.cs
  src/NLog/LogFactory-T.cs
  src/NLog/LogFactory.cs
  src/NLog/LoggerImpl.cs
  src/NLog/NLogTraceListener.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteTests.cs
Labels: UWP, refactoring

#2662 FileTarget - Improve handling of archive with multiple active files
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: bug, file-target

#2587 Internal Log - Include target type and target name in the log messages
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/EventLogTarget.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/LogReceiverWebServiceTarget.cs
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/NetworkTarget.cs
  src/NLog/Targets/PerformanceCounterTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/WebServiceTarget.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
  src/NLog/Targets/Wrappers/FallbackGroupTarget.cs
  src/NLog/Targets/Wrappers/LimitingTargetWrapper.cs
  src/NLog/Targets/Wrappers/PostFilteringTargetWrapper.cs
  src/NLog/Targets/Wrappers/RetryingTargetWrapper.cs
  src/NLog/Targets/Wrappers/SplitGroupTarget.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/LimitingTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/PostFilteringTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/RetryingTargetWrapperTests.cs
Labels: enhancement

#2664 Version 4.5.3
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version

#2673 TargetWithContext - Easier to use without needing to override ContextProperties
  src/NLog/Targets/TargetWithContext.cs
Labels: enhancement

#2586 Target.MergeEventProperties is now obsolete
  src/NLog/LogEventInfo.cs
  src/NLog/Logger-V1Compat.cs
  src/NLog/Logger.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/LogReceiverWebServiceTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
Labels: bug, enhancement, performance

#2679 Target.WriteAsyncThreadSafe should always have exception handler
  src/NLog/Targets/Target.cs
Labels: enhancement

#2682 Removed obsolete static Assembly lookup caching
  src/NLog/LoggerImpl.cs
Labels: refactoring

#2683 SonarQube WARNING: The following projects do not have a valid ProjectGuid
  src/NLog/NLog.csproj
Labels: build-config

#2675 DatabaseTarget - InitializeTarget with more logging
  src/NLog/Targets/DatabaseTarget.cs
Labels: database-target, enhancement
