Repository NLog/NLog, pull requests merged in 2018-05, with the labels that each got.

#2687 Fix: NLog.config build-action and copy for non-core projects, it's now "copy if newer"
  src/NuGet/NLog.Config/NLog.Config.nuspec
  src/NuGet/NLog.Config/tools/Install.ps1
Labels: bug, build-config, nlog-configuration

#2684 DatabaseTarget - Skip static assembly lookup for .Net Standard
  src/NLog/Targets/DatabaseTarget.cs
Labels: enhancement

#2690 SonarLint - Fixed different warnings from SonarQube
  src/NLog/Config/Factory.cs
  src/NLog/Layouts/SimpleLayout.cs
Labels: refactoring

#2688 Faulty invalidate of FormattedMessage when getting PropertiesDictionary
  src/NLog/LogEventInfo.cs
  tests/NLog.UnitTests/LoggerTests.cs
Labels: bug, has unittests

#2693 Deduplicate AppendIntegerAsString
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
Labels: refactoring

#2694 branchmode sonar
  run-sonar.ps1
Labels: build-config

#2691 Sonar warning fixes + C# 6 + 7 improvements
  src/NLog/Common/AsyncHelpers.cs
  src/NLog/Common/LogEventInfoBuffer.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Filters/WhenRepeatedFilter.cs
  src/NLog/Fluent/LogBuilder.cs
  src/NLog/ILoggerExtensions.cs
  src/NLog/Internal/FileAppenders/BaseMutexFileAppender.cs
  src/NLog/Internal/FileCharacteristicsHelper.cs
  src/NLog/Internal/LogMessageTemplateFormatter.cs
  src/NLog/Internal/NetworkSenders/NetworkSenderFactory.cs
  src/NLog/Internal/PropertiesDictionary.cs
  src/NLog/Internal/SimpleStringReader.cs
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/LayoutRenderers/RegistryLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/CachedLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/SimpleLayout.cs
  src/NLog/LogFactory.cs
  src/NLog/LogLevel.cs
  src/NLog/Logger-generated.cs
  src/NLog/Logger.cs
  src/NLog/LoggerImpl.cs
  src/NLog/NestedDiagnosticsLogicalContext.cs
  src/NLog/NullLogger.cs
  src/NLog/Targets/ConsoleTargetHelper.cs
  src/NLog/Targets/DateAndSequenceArchive.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/LineEndingMode.cs
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/WebServiceTarget.cs
  tests/NLog.UnitTests/Targets/NetworkTargetTests.cs
Labels: refactoring

#2695 LogEventInfo - Structured logging parameters are not always immutable
  src/NLog/Layouts/CompoundLayout.cs
  src/NLog/Layouts/CsvLayout.cs
  src/NLog/Layouts/JsonLayout.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/Log4JXmlEventLayout.cs
  src/NLog/Layouts/SimpleLayout.cs
  src/NLog/Targets/Target.cs
Labels: refactoring

#2696 Fixed Sonar warnings
  src/NLog/Internal/MultiFileWatcher.cs
  src/NLog/Internal/PropertiesDictionary.cs
  src/NLog/Internal/StringSplitter.cs
  src/NLog/LayoutRenderers/AppDomainLayoutRenderer.cs
  src/NLog/LayoutRenderers/ProcessInfoLayoutRenderer.cs
  src/NLog/LayoutRenderers/VariableLayoutRenderer.cs
  src/NLog/MessageTemplates/TemplateEnumerator.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/Wrappers/LogOnProviderType.cs
  src/NLog/Targets/Wrappers/SecurityLogOnType.cs
Labels: refactoring

#2698 FileTarget - Calculate correct archive date, when using Monthly archive
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: bug, file-target

#2700 sonarqube.com -> sonarcloud.io, analysis version
  run-sonar.ps1
Labels: build-config

#2697 Version 4.5.4
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version

#2705 Improve run-sonar.ps1
  run-sonar.ps1
Labels: build-config

#2706 skip building tags
  appveyor.yml
Labels: build-config

#2707 enabled VariablesTest_string_expanding unit test
  tests/NLog.UnitTests/Config/VariableTests.cs
Labels: nlog-configuration, test

#2711 Update tokens
  appveyor.yml
Labels: build-config

#2714 Added file target with special chars test, improved FileInRoot test
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: file-target, test

#2712 Rewrite Asserts for concurrenttest for better diag
  tests/NLog.UnitTests/Targets/ConcurrentFileTargetTests.cs
Labels: test

#2704 Allocation improvement in precalculating layouts
  src/NLog/LogEventInfo.cs
  src/NLog/LoggerImpl.cs
  src/NLog/Targets/Target.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
Labels: performance

#2727 Support for custom targets that implements IUsesStackTrace
  src/NLog/Targets/Target.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteTests.cs
Labels: bug, feature, has unittests

#2726 WhenRepeated - Support logging rules with multiple targets
  src/NLog/LoggerImpl.cs
  tests/NLog.UnitTests/Filters/WhenRepeatedTests.cs
Labels: feature, has unittests

#2736 FileTarget - Calculate correct archive date when multiple file appenders
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: bug, file-target

#2740 Fix Nuget install of OpenCover
  appveyor.yml
Labels: build-config

#2739 Target.WriteAsyncLogEvents(IList<AsyncLogEventInfo>) to public
  src/NLog/Targets/Target.cs
Labels: enhancement

#2734 Release 4.5.5
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version

#2745 FileTarget - Improve support for Linux FileSystem without BirthTime
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Targets/FileTarget.cs
Labels: file-target

#2743 JsonLayout - Reduce allocations when needing to escape string (44% time improvement)
  src/NLog/LayoutRenderers/Wrappers/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WhenEmptyLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WhenLayoutRendererWrapper.cs
  src/NLog/Layouts/JsonLayout.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
Labels: performance

#2744 LogEventInfo - HasProperties should allocate PropertiesDicitonary when needed
  src/NLog/LogEventInfo.cs
Labels: performance

#2747 JsonSerializer - Generate valid Json when hitting the MaxRecursionLimit
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
Labels: bug, has unittests, json-layout

#2752 JSON: Fixes issue where char types are not properly escaped
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
Labels: bug, json-layout

#2749 NLog.WindowsEventLog: Update dependency System.Diagnostics.EventLog to RTM version
  src/NLog.WindowsEventLog/NLog.WindowsEventLog.csproj
Labels: enhancement
