Repository NLog/NLog, pull requests merged in 2018-03, with the labels that each got.

#2613 Attempt to make some unit-tests more stable
  tests/NLog.UnitTests/LayoutRenderers/CallSiteTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/BufferingTargetWrapperTests.cs
Labels: test, unstable test

#2609 NLog - Fix Callsite when wrapping ILogger in Microsoft Extension Logging
  src/NLog/LoggerImpl.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteTests.cs
Labels: bug, enhancement

#2595 IsSafeToDeferFormatting - Convert.GetTypeCode is faster and better
  src/NLog/LogEventInfo.cs
Labels: performance

#2599 TryImplicitConversion should only check object types
  src/NLog/Internal/PropertyHelper.cs
Labels: enhancement

#2597 Replace WINDOWS_UWP with NETSTANDARD1_3 to support UWP10 shared libraries
  build.ps1
  src/NLog/Common/AsyncHelpers.cs
  src/NLog/Common/InternalLogger.cs
  src/NLog/Conditions/ConditionRelationalExpression.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/InstallationContext.cs
  src/NLog/Config/LoggingConfigurationReloadedEventArgs.cs
  src/NLog/Config/SimpleConfigurator.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/Internal/AssemblyHelpers.cs
  src/NLog/Internal/EnvironmentHelper.cs
  src/NLog/Internal/FileAppenders/BaseMutexFileAppender.cs
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/FileAppenders/MutexMultiProcessFileAppender.cs
  src/NLog/Internal/MultiFileWatcher.cs
  src/NLog/Internal/PlatformDetector.cs
  src/NLog/Internal/PortableThreadIDHelper.cs
  src/NLog/Internal/PropertyHelper.cs
  src/NLog/Internal/ThreadIDHelper.cs
  src/NLog/LayoutRenderers/AssemblyVersionLayoutRenderer.cs
  src/NLog/LayoutRenderers/BaseDirLayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/LayoutRenderers/MachineNameLayoutRenderer.cs
  src/NLog/LayoutRenderers/NLogDirLayoutRenderer.cs
  src/NLog/LayoutRenderers/ProcessIdLayoutRenderer.cs
  src/NLog/LayoutRenderers/ProcessInfoLayoutRenderer.cs
  src/NLog/LayoutRenderers/ProcessNameLayoutRenderer.cs
  src/NLog/LayoutRenderers/ThreadNameLayoutRenderer.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
  src/NLog/LoggerImpl.cs
  src/NLog/NLog.csproj
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/ConsoleTargetHelper.cs
  src/NLog/Targets/ConsoleWordHighlightingRule.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/LineEndingMode.cs
  src/NLog/Targets/TraceTarget.cs
Labels: enhancement, work in progress

#2591 callsite-filename renderer
  src/NLog/LayoutRenderers/CallSiteFileNameLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteFileNameLayoutTests.cs
Labels: feature, has unittests

#2592 Make Set methods of MDC and MDLC return IDisposable
  src/NLog/MappedDiagnosticsContext.cs
  src/NLog/MappedDiagnosticsLogicalContext.cs
  tests/NLog.UnitTests/Contexts/MappedDiagnosticsContextTests.cs
  tests/NLog.UnitTests/Contexts/MappedDiagnosticsLogicalContextTests.cs
Labels: feature

#2604 FileTarget - Failing to CreateArchiveMutex should not stop logging
  src/NLog/Internal/FileAppenders/BaseMutexFileAppender.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeFactory.cs
Labels: enhancement, file-target

#2612 add final param to `AddRule` Methods
  src/NLog/Config/LoggingConfiguration.cs
Labels: enhancement, feature, nlog-configuration

#2620 Single Target optimization should only be done when parseMessageTemplate = null
  src/NLog/Internal/LogMessageTemplateFormatter.cs
  src/NLog/LayoutRenderers/MessageLayoutRenderer.cs
  src/NLog/LogEventInfo.cs
  src/NLog/LoggerImpl.cs
Labels: bug

#2616 LogManager.Shutdown - Should disable file watcher and avoid auto reload
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
Labels: enhancement

#2619 NetworkTarget - Reduce allocation when buffer is less than MaxMessageSize
  src/NLog/Targets/NetworkTarget.cs
Labels: performance

#2622 NetworkTarget - Http / Https should not throw on async error response
  src/NLog/Internal/NetworkSenders/HttpNetworkSender.cs
Labels: enhancement, network/NLogViewer-target, performance

#2621 Single Target optimization logic refactored to reuse optimization approval
  src/NLog/Internal/LogMessageTemplateFormatter.cs
  src/NLog/MessageTemplates/LiteralHole.cs
  src/NLog/MessageTemplates/TemplateRenderer.cs
Labels: performance

#2633 Added NLog.MailKit Badge to ReadMe
  README.md
Labels: documentation

#2634 Update SHFB for NLog 4.5
  src/Docs/NLog.shfbproj
Labels: build-config
