Repository NLog/NLog, pull requests merged in 2018-09, with the labels that each got.

#2886 NDLC and NDC should use local LoggingConfiguration for FormatProvider
  src/NLog/Internal/FormatHelper.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/LayoutRenderers/NdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/NdlcLayoutRenderer.cs
Labels: enhancement, performance

#2885 Compact logging of logging levels for loggers with no active targets
  src/NLog/LogFactory.cs
Labels: enhancement

#2897 Removed System.Collections.NonGeneric dependency + InternalLogger - Faster filtering when configured LogLevel is Off
  src/NLog/Common/InternalLogger.cs
  src/NLog/Conditions/ConditionRelationalExpression.cs
  src/NLog/NLog.csproj
Labels: enhancement, performance

#2902 JSON serialize: support for DynamicObject + Improve JSON tests
  src/NLog/NLog.csproj
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerLegacyTests.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTests.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: feature, has unittests, json-layout, test

#2910 ObjectHandle - LifeTime avoid remoting exception: has been disconnected
  src/NLog/Internal/ObjectHandleSerializer.cs
  src/NLog/MappedDiagnosticsLogicalContext.cs
  src/NLog/NestedDiagnosticsLogicalContext.cs
Labels: enhancement

#2909 AsyncTaskTarget: Added support for BatchSize and RetryCount
  src/NLog/Targets/AsyncTaskTarget.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: feature

#2908 Layout Wrappers should not crash when Inner-Layout is null
  src/NLog/LayoutRenderers/Wrappers/WhenLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WrapperLayoutRendererBase.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/WhenEmptyTests.cs
Labels: enhancement

#2912 NLog.UnitTests - Configure internalLogLevel to Off by default
  tests/NLog.UnitTests/Config/InternalLoggingTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: enhancement, test

#2917 Logger.Log should initialize LogEventInfo.LoggerName
  src/NLog/Logger.cs
  tests/NLog.UnitTests/LoggerTests.cs
Labels: enhancement

#2914 AsyncTaskTarget - Retry WriteAsyncTask should be protected with SyncRoot
  src/NLog/Targets/AsyncTaskTarget.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: enhancement

#2920 Version 4.5.10
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version

#2915 Reduce code complexity in different locations
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Internal/ObjectGraphScanner.cs
  src/NLog/Internal/PropertiesDictionary.cs
  src/NLog/Internal/PropertyHelper.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/MethodCallTarget.cs
Labels: refactoring

#2918 PerformanceCounter - Improve behavior for CPU usage calculation + Format and Culture options
  src/NLog/LayoutRenderers/PerformanceCounterLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/PerformanceCounterLayoutRendererTests.cs
Labels: enhancement, feature, needs documentation on wiki

#2890 AsyncTargetWrapper - TimeToSleepBetweenBatches changed default to 1ms
  src/NLog/Targets/Wrappers/AsyncRequestQueue-T.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
Labels: enhancement, performance

#2905 Cleanup
  src/.nuget/NuGet.Config
  src/.nuget/NuGet.exe
  src/.nuget/NuGet.targets
  tools/CheckSourceCode/NLog.SourceCodeTests.exe
  tools/CheckSourceCode/NLog.SourceCodeTests.pdb
  tools/SyncProjectItems/Program.cs
  tools/SyncProjectItems/Properties/AssemblyInfo.cs
  tools/SyncProjectItems/SyncProjectItems.csproj
Labels: build-config

#2922 AppVeyor - Skip publish on PullRequest and add suffix
  appveyor.yml
  build.ps1
Labels: build-config

#2926 NullAppender - Added missing SecuritySafeCritical
  src/NLog/Internal/FileAppenders/NullAppender.cs
Labels: enhancement

#2891 LoggingConfigurationParser - Extracted from XmlLoggingConfiguration + rule name for `<rule>` + logger attribute for filtering
  src/NLog/Config/ILoggingConfigurationElement.cs
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/LoggingRule.cs
  src/NLog/Config/NLogXmlElement.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  tests/NLog.UnitTests/Config/ConfigApiTests.cs
  tests/NLog.UnitTests/Config/VariableTests.cs
Labels: feature, refactoring

#2929 Retry unstable integration tests
  tests/NLog.UnitTests/NLogTestBase.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
  tests/NLog.UnitTests/Targets/ConcurrentFileTargetTests.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/BufferingTargetWrapperTests.cs
Labels: test, unstable test

#2931 Invalid attribute values in the `<NLog>` element should not break logging & better attribute parsing order
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/NLogXmlElement.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
Labels: enhancement, nlog-configuration

#2858 LogFactory - LoadConfiguration with better support for relative paths
  src/NLog/Internal/Fakeables/FileWrapper.cs
  src/NLog/Internal/Fakeables/IFile.cs
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/LogFactoryTests.cs
  tests/NLog.UnitTests/Mocks/AppDomainMock.cs
  tests/NLog.UnitTests/Mocks/FileMock.cs
Labels: feature, nlog-configuration
