Repository NLog/NLog, pull requests merged in 2018-08, with the labels that each got.

#2830 Auto loading of assemblies was broken in some cases
  src/NLog/Config/ConfigurationItemFactory.cs
Labels: bug

#2816 MessageTemplates - Support rendering of alignment + padding
  src/NLog/MessageTemplates/TemplateRenderer.cs
  tests/NLog.UnitTests/LoggerTests.cs
  tests/NLog.UnitTests/MessageTemplates/RendererTests.cs
Labels: feature

#2814 LoggingConfiguration - Improves CheckUnusedTargets to handle target wrappers
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  tests/NLog.UnitTests/LayoutRenderers/IdentityTests.cs
Labels: enhancement, nlog-configuration, refactoring

#2809 MethodCallTarget - Support for Lamba method
  src/NLog/Targets/MethodCallTarget.cs
  src/NLog/Targets/MethodCallTargetBase.cs
  tests/NLog.UnitTests/Targets/MethodCallTests.cs
Labels: feature

#2831 Improve NLogTraceListener setters
  src/NLog/NLogTraceListener.cs
Labels: enhancement

#2817 Optimize LayoutRendererWrappers to reduce string allocations
  src/NLog/Filters/WhenRepeatedFilter.cs
  src/NLog/Internal/FilePathLayout.cs
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/LayoutRenderers/EnvironmentLayoutRenderer.cs
  src/NLog/LayoutRenderers/TraceActivityIdLayoutRenderer.cs
  src/NLog/LayoutRenderers/VariableLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/FileSystemNormalizeLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/LowercaseLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/OnExceptionLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/ReplaceLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/ReplaceNewLinesLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/TrimWhiteSpaceLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/UppercaseLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WhenEmptyLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WhenLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WrapperLayoutRendererBase.cs
  src/NLog/LayoutRenderers/Wrappers/WrapperLayoutRendererBuilderBase.cs
Labels: performance

#2833 Unit test after fixing ConfigurationItemFactory auto loading of assemblies
  src/NLog/Config/ConfigurationItemFactory.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
Labels: enhancement, refactoring, test

#2835 Unit test after fixing ConfigurationItemFactory auto loading of assemblies
  src/NLog/Config/ConfigurationItemFactory.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
Labels: bug, enhancement

#2834 Fix NLog.WindowsEventLog Package
  src/NLog.WindowsEventLog/NLog.WindowsEventLog.csproj
  src/NLog/Targets/EventLogTarget.cs
  src/NLog/Targets/EventLogTargetOverflowAction.cs
Labels: bug

#2838 Fix NLog.WindowsIdentity Package
  src/NLog.WindowsIdentity/NLog.WindowsIdentity.csproj
  src/NLog/LayoutRenderers/WindowsIdentityLayoutRenderer.cs
Labels: bug

#2836 WrapperLayoutRendererBuilderBase methods marked as obsolete
  src/NLog/LayoutRenderers/Wrappers/FileSystemNormalizeLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/LowercaseLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/ReplaceNewLinesLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/TrimWhiteSpaceLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/UppercaseLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WhenEmptyLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WhenLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WrapperLayoutRendererBuilderBase.cs
Labels: enhancement

#2709 XML Config: Support for constant variable in level attributes (level, minlevel, etc)
  src/NLog/Config/XmlLoggingConfiguration.cs
  tests/NLog.UnitTests/Config/VariableTests.cs
Labels: feature, has unittests, nlog-configuration

#2847 TargetWithContext - Allow custom target to provide their own dictionary
  src/NLog/Targets/TargetWithContext.cs
Labels: enhancement

#2846 Include Entry Assembly File Location when loading candidate NLog.config
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Internal/AssemblyHelpers.cs
  src/NLog/Internal/PathHelpers.cs
  src/NLog/LogFactory.cs
Labels: enhancement, nlog-configuration

#2850 NLogTraceListener - Reduce allocations for TraceData with single param
  src/NLog/NLogTraceListener.cs
Labels: enhancement, performance

#2848 Added defaultAction for <filter>
  src/NLog/Config/LoggingRule.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/Internal/TargetWithFilterChain.cs
  src/NLog/LogFactory.cs
  src/NLog/LoggerImpl.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
Labels: feature, nlog-configuration

#2853 adding <repository> to nuspec NLog.Config and NLog.Schema
  build.ps1
  src/NuGet/NLog.Config/NLog.Config.nuspec
  src/NuGet/NLog.Extended/NLog.Extended.nuspec
  src/NuGet/NLog.Schema/NLog.Schema.nuspec
  src/NuGet/NLog/NLog.nuspec
  tools/nuget.exe
Labels: enhancement

#2865 JSON encoding should create valid JSON for special double values (hotfix)
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTests.cs
Labels: bug

#2862 Include Entry Assembly File Location when loading candidate NLog.config (Hotfix)
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Internal/AssemblyHelpers.cs
  src/NLog/Internal/PathHelpers.cs
  src/NLog/LogFactory.cs
Labels: enhancement, nlog-configuration

#2857 Added support for complex objects in MDLC and NDLC using ObjectHandle
  src/NLog/MappedDiagnosticsLogicalContext.cs
  src/NLog/NestedDiagnosticsLogicalContext.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
Labels: feature

#2869 Version 4.5.9
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version

#2876 AsyncTargetWrapper - Allow ForceLockingQueue = false on Net45
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: enhancement
