Repository NLog/NLog, pull requests merged in 2019-02, with the labels that each got.

#3094 Fix AutoReload (never released bug)
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
Labels: never-released bug, nlog-configuration

#3082 WebService target: added support for custom SOAPAction property (Soap11+Soap12 protocol)
  src/NLog/Targets/WebServiceTarget.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
Labels: enhancement, webservice-target

#3096 Improve support for custom IDictionary implementation (JSON, XML and structured logging)
  src/NLog/Internal/DictionaryEntryEnumerable.cs
  src/NLog/Layouts/XmlLayout.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Internal/TrickyTestDictionary.cs
  tests/NLog.UnitTests/Layouts/XmlLayoutTests.cs
  tests/NLog.UnitTests/LoggerTests.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: enhancement

#3100 WebService target allow override of SoapAction through Headers
  src/NLog/Targets/WebServiceTarget.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
Labels: enhancement, webservice-target

#3103 StringBuilderPool - Reduce memory overhead until required
  src/NLog/Internal/StringBuilderPool.cs
  src/NLog/Targets/Target.cs
Labels: performance

#3091 IDatabaseValueConverter.cs → IPropertyTypeConverter, implement in DatabaseTarget, TargetWithContext & MethodCallTargetBase
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/IPropertyTypeConverter.cs
  src/NLog/Config/PropertyTypeConverter.cs
  src/NLog/Targets/DatabaseParameterInfo.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/DatabaseValueConverter.cs
  src/NLog/Targets/MethodCallParameter.cs
  src/NLog/Targets/MethodCallTargetBase.cs
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
  tests/NLog.UnitTests/Targets/DatabaseValueConverterTests.cs
Labels: database-target, enhancement, refactoring

#3104 SonarLint - Remove old todo noise
  src/NLog/Logger-generated.cs
  src/NLog/Logger-generated.tt
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/Targets/WebServiceTarget.cs
Labels: refactoring

#3105 Reduce code complexity & small code cleanup
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/LoggingConfigurationWatchableFileLoader.cs
  src/NLog/Internal/NetworkSenders/SslSocketProxy.cs
  src/NLog/Internal/PropertiesDictionary.cs
  src/NLog/Internal/XmlHelper.cs
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  src/NLog/LogFactory.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/TargetWithContext.cs
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
Labels: refactoring

#3107 Removed old todos and added missing docgen + Reduce code complexity of ParseRuleElement
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Internal/FilePathLayout.cs
  src/NLog/Internal/FormatHelper.cs
  src/NLog/Internal/StringSplitter.cs
  src/NLog/LayoutRenderers/AppSettingLayoutRenderer2.cs
  src/NLog/LayoutRenderers/Wrappers/XmlEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/JsonLayout.cs
  src/NLog/Layouts/XmlLayout.cs
  src/NLog/Targets/DatabaseParameterInfo.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/MemoryTarget.cs
  src/NLog/Targets/NetworkTarget.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: refactoring

#3098 <rule> support for one or more '*' and '?' wildcards and in any position
  src/NLog/Config/LoggerNameMatcher.cs
  src/NLog/Config/LoggingRule.cs
  tests/NLog.UnitTests/Config/ConfigApiTests.cs
Labels: feature, nlog-configuration, refactoring

#3110 Reduce code complexity & small refactorings
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/PropertyTypeConverter.cs
  src/NLog/Layouts/XmlLayout.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
Labels: refactoring

#3132 Fix Opencover on AppVeyor
  appveyor.yml
Labels: build-config

#3121 Hyperlinks to https:/
  examples/targets/Configuration API/ASPNetTrace/README.txt
  src/NLog/Annotations.cs
  src/NLog/Internal/FileAppenders/MutexMultiProcessFileAppender.cs
  src/NLog/Internal/ReflectionHelpers.cs
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/Internal/XmlHelper.cs
  src/NLog/LayoutRenderers/SpecialFolderLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WrapLineLayoutRendererWrapper.cs
  src/NLog/Layouts/LayoutParser.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/Win32FileAttributes.cs
  src/NLog/Targets/Wrappers/ImpersonatingTargetWrapper.cs
  tests/NLog.UnitTests/Internal/AsyncLogEventInfoTests.cs
  tests/NLog.UnitTests/ProcessRunner.cs
  tests/NLog.UnitTests/Targets/ConsoleTargetTests.cs
Labels: documentation

#3120 Improve build script
  build.ps1
Labels: build-config

#3141 AppSettingLayoutRenderer2 - Use Item instead of Name as it matches GDC
  src/NLog/LayoutRenderers/AppSettingLayoutRenderer2.cs
Labels: breaking change (but never released as RTM), needs documentation on wiki
