Repository NLog/NLog, pull requests merged in 2019-10, with the labels that each got.

#3609 FileTarget - Improve handling of relative path in ArchiveFileName
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDate.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDateAndSequence.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeSequence.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: bug, file-archiving, file-target, size/S

#3611 ${Exception} - Added Format options: HResult and Properties
  src/NLog/Config/ExceptionRenderingFormat.cs
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
Labels: feature, needs documentation on wiki, size/L

#3613 TypeDescriptor.GetConverter can throw after linker tree shake
  src/NLog/Internal/PropertyHelper.cs
Labels: external-bug, size/M

#3623 #3181 TimeSource ToString() tests
  tests/NLog.UnitTests/TimeSourceTests.cs
Labels: size/S

#3622 ConcurrentRequestQueue - Consumer should always pulse waiting producers
  src/NLog/Targets/Wrappers/AsyncRequestQueue-T.cs
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
Labels: enhancement, size/S

#3618 Faster reflection of NLog configuration items by skipping Type.IsDefined
  src/NLog/Config/Factory.cs
  src/NLog/Internal/ObjectGraphScanner.cs
  src/NLog/Layouts/Layout.cs
Labels: performance, size/L

#3640 Add null and recursive tests for ValueFormatter
  tests/NLog.UnitTests/MessageTemplates/ValueFormatterTest.cs
Labels: size/M, test

#3635 Console target thread safe and support for batch writing
  src/NLog/Common/InternalLogger.cs
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/Targets/ColoredConsoleAnsiPrinter.cs
  src/NLog/Targets/ColoredConsoleSystemPrinter.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/ConsoleTargetHelper.cs
  src/NLog/Targets/IColoredConsolePrinter.cs
  tests/NLog.UnitTests/Targets/ConsoleTargetTests.cs
Labels: console-target, enhancement, size/L

#3636 AsyncTargetWrapper - Eject writers on close incase timer thread is blocked
  src/NLog/Targets/Wrappers/AsyncRequestQueue-T.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
Labels: enhancement, performance, size/M

#3641 ${CallSite} - Handle MoveNext More robust
  src/NLog/Internal/StackTraceUsageUtils.cs
  src/NLog/LoggerImpl.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteTests.cs
Labels: bug, enhancement, size/L

#3642 More robust GetCurrentClassLogger when we get lambda_method
  src/NLog/Internal/StackTraceUsageUtils.cs
  tests/NLog.UnitTests/GetLoggerTests.cs
Labels: enhancement, size/S

#3631 Fixes bug in ExceptionLayoutRenderer where separator is excluded
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
Labels: bug, size/M, squash when passing

#3647 ${substring}: length should not be mandatory
  src/NLog/LayoutRenderers/Wrappers/SubstringLayoutRendererWrapper.cs
Labels: bug, documentation on wiki done, needs documentation on wiki, size/XS

#3649 Single file publish with ${basedir=fixTempDir=true} and prioritize process-dir for auto-loading exe.nlog
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Internal/Fakeables/AppEnvironmentWrapper.cs
  src/NLog/Internal/Fakeables/IAppEnvironment.cs
  src/NLog/LayoutRenderers/BaseDirLayoutRenderer.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
  tests/NLog.UnitTests/LayoutRenderers/BaseDirTests.cs
  tests/NLog.UnitTests/Mocks/AppEnvironmentMock.cs
Labels: size/L

#3651 ConcurrentRequestQueue - DequeueBatch should handle that input list is non-empty
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
  tests/NLog.UnitTests/Targets/Wrappers/ConcurrentRequestQueueTests.cs
Labels: enhancement, size/S
