Repository NLog/NLog, pull requests merged in 2019-06, with the labels that each got.

#3444 RetryingMultiProcessFileAppender - better init BufferSize
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/RetryingMultiProcessFileAppender.cs
Labels: merge when passing, performance

#3449 Decouple LoggingConfiguration from XmlLoggingConfiguration
  src/NLog/Config/IInitializeSucceeded.cs
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
Labels: merge when passing, refactoring

#3450 Partly decouple LogFactory from FileLoaders
  src/NLog/LogFactory.cs
  src/NLog/LoggingConfigurationFileLoaderFactory.cs
Labels: refactoring

#3457 Make AppDomainWrapper internal
  src/NLog/Internal/AppDomains/AppDomainWrapper.cs
Labels: breaking change, merge when passing

#3456 Improve exceptions on LoggingConfiguration.AddTarget
  src/NLog/Config/LoggingConfiguration.cs
  tests/NLog.UnitTests/Config/ConfigApiTests.cs
Labels: breaking behavior change, enhancement, merge when passing

#3458 Change default format of ${exception} to ToString,Data (was Message)
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
  tests/NLog.UnitTests/LoggerTests.cs
Labels: breaking behavior change

#3459 Support layouts (e.g. JSON) and inner text in <variable>
  src/NLog/Config/ILoggingConfigurationElement.cs
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/LayoutRenderers/VariableLayoutRenderer.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
  tests/NLog.UnitTests/Config/VariableTests.cs
  tests/NLog.UnitTests/LayoutRenderers/VariableLayoutRendererTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
Labels: XSD change, breaking change, feature, nlog-configuration

#3460 Remove unneeded [CLSCompliant(false)]
  src/NLog/LogManager.cs
Labels: enhancement, merge when passing

#3461 Set default of JsonLayout.MaxRecursionLimit to 1
  src/NLog/Layouts/JSON/JsonLayout.cs
Labels: breaking behavior change

#3462 Improve warning in VariableLayoutRenderer
  src/NLog/LayoutRenderers/VariableLayoutRenderer.cs
Labels: enhancement

#3469 LogLevel - Added support for TypeConverter
  src/NLog/Attributes/LogLevelTypeConverter.cs
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/LogLevel.cs
  src/NLog/NLog.csproj
  tests/NLog.UnitTests/LayoutRenderers/LogLevelTests.cs
Labels: feature, size/L

#3471 Added testcase for <variable> with inner <value>
  tests/NLog.UnitTests/Config/VariableTests.cs
Labels: merge when passing, size/S, test

#3477 AppSettingLayoutRenderer2 - Added support for ConnectionStrings Lookup
  src/NLog/Internal/ConfigurationManager2.cs
  src/NLog/Internal/IConfigurationManager2.cs
  src/NLog/LayoutRenderers/AppSettingLayoutRenderer2.cs
  tests/NLog.UnitTests/LayoutRenderers/AppSettingTests.cs
Labels: size/L

#3479 Added test: <variable> with both value attribute and <value>
  tests/NLog.UnitTests/Config/VariableTests.cs
Labels: size/S, test

#3478 XSD: Support <value> in <variable>
  tools/MakeNLogXSD/TemplateXSD.xml
Labels: XSD change, size/XS

#3482 Fix typos in docs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Layouts/JsonAttribute.cs
  src/NLog/Layouts/XmlAttribute.cs
  src/NLog/Layouts/XmlElement.cs
  src/NLog/Layouts/XmlLayout.cs
  src/NLog/MessageTemplates/Template.cs
  src/NLog/Targets/DatabaseParameterInfo.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/NLogViewerParameterInfo.cs
  src/NLog/Targets/NetworkTargetConnectionsOverflowAction.cs
  tools/MakeNLogXSD/TemplateXSD.xml
Labels: documentation, size/S

#3483 Fix typos in comments and test code
  src/NLog.sln.DotSettings
  src/NLog/Annotations.cs
  src/NLog/Common/InternalLogger.cs
  src/NLog/Conditions/ConditionRelationalExpression.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/ExceptionRenderingFormat.cs
  src/NLog/Config/Factory.cs
  src/NLog/Config/LoggerNameMatcher.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/CountingSingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/FileAppenders/MutexMultiProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/RetryingMultiProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/SingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/UnixMultiProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs
  src/NLog/Internal/LayoutHelpers-generated.cs
  src/NLog/Internal/NetworkSenders/HttpNetworkSender.cs
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/Internal/XmlHelper.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/LayoutRenderers/RegistryLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/XmlEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/LayoutParser.cs
  src/NLog/LogManager.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/JsonSerializeOptions.cs
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/WebServiceTarget.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs
  tests/NLog.UnitTests/Conditions/ConditionEvaluatorTests.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/Internal/FileAppenders/FileAppenderCacheTests.cs
  tests/NLog.UnitTests/Internal/LayoutHelpersTests.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
  tests/NLog.UnitTests/LogReceiverService/LogReceiverServiceTests.cs
  tests/NLog.UnitTests/LoggerTests.cs
  tests/NLog.UnitTests/Targets/ColoredConsoleTargetTests.cs
  tests/NLog.UnitTests/Targets/ConcurrentFileTargetTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/LimitingTargetWrapperTests.cs
Labels: documentation, size/L

#3486 Fix XSD generation
  tools/MakeNLogXSD/XsdFileGenerator.cs
Labels: size/XS

#3492 FileTarget - improvements when ConcurrentWrites=false + Extra test MessageTemplate.Render
  src/NLog/Internal/FileAppenders/BaseMutexFileAppender.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/MessageTemplates/RendererTests.cs
Labels: enhancement, refactoring, size/S

#3498 Deploy snupkg on AppVeyor without custom script
  appveyor.yml
Labels: build-config, merge when passing, size/XS

#3497 Print current building TargetFramework to log
  src/NLog/NLog.csproj
Labels: build-config, size/XS
