Repository NLog/NLog, pull requests merged in 2019-11, with the labels that each got.

#3654 ObjectPathRendererWrapper - Refactoring to reduce code complexity
  src/NLog/LayoutRenderers/Wrappers/ObjectPathRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WrapperLayoutRendererBase.cs
Labels: refactoring, size/M

#3660 ObjectHandleSerializer - GetObjectData should have SerializationFormatter=true
  src/NLog/Internal/ObjectHandleSerializer.cs
  src/NLog/MappedDiagnosticsLogicalContext.cs
Labels: enhancement, size/S

#3662 FileTarget - Extra logging when FileName Layout returns empty filename
  src/NLog/Targets/FileTarget.cs
Labels: enhancement, size/XS

#3653 Fixes NullReferenceException in SimpleLayout PreCalculate after TryGetRawValue
  src/NLog/Layouts/SimpleLayout.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutOutputTests.cs
Labels: size/M, squash when passing

#3657 Version 4.6.8 changelog
  CHANGELOG.md
  src/NLog/NLog.csproj
Labels: size/M

#3638 ApplicationEnvironment subfolder for process- and appdomain renderers
  src/NLog/LayoutRenderers/ApplicationEnvironment/AppDomainLayoutRenderer.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/AppSettingLayoutRenderer2.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/AssemblyVersionLayoutRenderer.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/AssemblyVersionType.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/EnvironmentUserLayoutRenderer.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/GarbageCollectorInfoLayoutRenderer.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/GarbageCollectorProperty.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/ProcessIdLayoutRenderer.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/ProcessInfoLayoutRenderer.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/ProcessInfoProperty.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/ProcessNameLayoutRenderer.cs
  src/NLog/LayoutRenderers/CallSite/CallSiteFileNameLayoutRenderer.cs
  src/NLog/LayoutRenderers/CallSite/CallSiteLayoutRenderer.cs
  src/NLog/LayoutRenderers/CallSite/CallSiteLineNumberLayoutRenderer.cs
  src/NLog/LayoutRenderers/CallSite/StackTraceFormat.cs
  src/NLog/LayoutRenderers/CallSite/StackTraceLayoutRenderer.cs
  src/NLog/LayoutRenderers/DateTime/DateLayoutRenderer.cs
  src/NLog/LayoutRenderers/DateTime/LongDateLayoutRenderer.cs
  src/NLog/LayoutRenderers/DateTime/ProcessTimeLayoutRenderer.cs
  src/NLog/LayoutRenderers/DateTime/QueryPerformanceCounterLayoutRenderer.cs
  src/NLog/LayoutRenderers/DateTime/ShortDateLayoutRenderer.cs
  src/NLog/LayoutRenderers/DateTime/TicksLayoutRenderer.cs
  src/NLog/LayoutRenderers/DateTime/TimeLayoutRenderer.cs
  src/NLog/LayoutRenderers/Machine/EnvironmentLayoutRenderer.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/LayoutWithHeaderAndFooter.cs
Labels: refactoring

#3664 Version 4.6.8
  build.ps1
Labels: merge when passing, version

#3668 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#3666 Refactor resolve & register for DI
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/ServiceRepository.cs
  src/NLog/Config/ServiceRepositoryExtensions.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/ProcessInfoLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/AllEventPropertiesLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/EventPropertiesLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/GdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/MdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/MdlcLayoutRenderer.cs
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/ObjectPathRendererWrapper.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/MethodCallTargetBase.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/TargetWithContext.cs
  src/NLog/Targets/WebServiceTarget.cs
Labels: size/L

#3637 TargetWithLayout changed default layout to have withexception=true, changed WithException to use | as exception separator as default
  src/NLog.MSMQ/Targets/MessageQueueTarget.cs
  src/NLog/LayoutRenderers/MessageLayoutRenderer.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/DebugTarget.cs
  src/NLog/Targets/DebuggerTarget.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/MemoryTarget.cs
  src/NLog/Targets/NLogViewerTarget.cs
  src/NLog/Targets/NetworkTarget.cs
  src/NLog/Targets/NullTarget.cs
  src/NLog/Targets/OutputDebugStringTarget.cs
  src/NLog/Targets/TargetWithLayout.cs
  src/NLog/Targets/TargetWithLayoutHeaderAndFooter.cs
  src/NLog/Targets/TraceTarget.cs
  src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs
Labels: new default (breaking), size/M

#3683 ObjectGraphScanner - Avoid holding list.SyncRoot lock while scanning
  src/NLog/Internal/ObjectGraphScanner.cs
Labels: performance, size/XS

#3684 ${message} renders Exception.GetType + Exception.Message when single exception parameter
  src/NLog/Internal/ExceptionMessageFormatProvider.cs
  src/NLog/LogEventInfo.cs
  tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs
Labels: breaking behavior change, feature, size/M

#3685 LogBuilder - Removed Caller-properties since they are available with ${callsite}
  src/NLog/Fluent/LogBuilder.cs
  src/NLog/LayoutRenderers/Contexts/AllEventPropertiesLayoutRenderer.cs
  tests/NLog.UnitTests/Fluent/LogBuilderTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/AllEventPropertiesTests.cs
Labels: breaking change, size/L

#3676 Fix setter ConfigurationItemFactory.Default
  src/NLog/Config/ConfigurationItemFactory.cs
Labels: size/XS

#3689 LoggingConfiguration - Moved CheckUnusedTargets to InitializeAll
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
Labels: enhancement, size/M

#3694 JsonSerializer - Write DateTime directly to StringBuilder instead of allocating string
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Internal/StringBuilderExtTests.cs
Labels: json / json-layout, performance, size/L

#3706 LongDateLayoutRenderer - Implement IRawValue-interface
  src/NLog/LayoutRenderers/LongDateLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/LongDateTests.cs
Labels: enhancement, size/S

#3705 JsonSerializer - Write DateTime directly to StringBuilder instead of allocating string
  src/NLog/Internal/StringBuilderExt.cs
Labels: json / json-layout, performance, size/XS

#3704 EventLogTarget - Improve diagnostics logging when using dynamic source
  src/NLog/Targets/EventLogTarget.cs
  tests/NLog.UnitTests/Targets/EventLogTargetTests.cs
Labels: enhancement, event-log-target, size/L

#3700 ExceptionLayoutRenderer - Added Format option called HResult (Fix NetCore)
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
Labels: bug, size/S

#3692 XmlLayout - Removed unnecessary double conversion to string
  src/NLog/Layouts/XmlElementBase.cs
Labels: performance, size/XS, xml-layout

#3691 FileTarget - ConcurrentWrites should use FileStream.Length in archive-check
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/FileAppenders/MutexMultiProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/SingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/UnixMultiProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs
  src/NLog/Internal/FileCharacteristics.cs
  src/NLog/Internal/FileCharacteristicsHelper.cs
  src/NLog/Internal/FileInfoExt.cs
  src/NLog/Internal/FileInfoHelper.cs
  src/NLog/Internal/Win32FileCharacteristicsHelper.cs
  src/NLog/Internal/Win32FileNativeMethods.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDynamicSequence.cs
  src/NLog/Targets/FileTarget.cs
Labels: file-archiving, file-target, performance, size/XL

#3713 Level LayoutRenderer Format extended with FullName
  src/NLog/LayoutRenderers/LevelFormat.cs
  src/NLog/LayoutRenderers/LevelLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/LogLevelTests.cs
Labels: enhancement, size/M
