Repository NLog/NLog, pull requests merged in 2019-07, with the labels that each got.

#3466 LoggingConfigurationParser - Moved attribute validation from Xml-Config
  src/NLog/Config/ILoggingConfigurationElement.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/NLogXmlElement.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/Internal/Strings/StringHelpers.cs
  tests/NLog.UnitTests/Config/DuplicateConfigurationAttributeTests.cs
  tests/NLog.UnitTests/Config/VariableTests.cs
Labels: refactoring, size/XL

#3494 GroupByTargetWrapper - Allow one to group by request-identifier
  src/NLog/Targets/Wrappers/GroupByTargetWrapper.cs
  tests/NLog.UnitTests/Targets/Wrappers/GroupByTargetWrapperTests.cs
Labels: size/L

#3513 AutoFlushTargetWrapper - Added FlushOnConditionOnly property
  src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
  tests/NLog.UnitTests/Targets/Wrappers/AutoFlushTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/BufferingTargetWrapperTests.cs
Labels: size/M

#3514 Added XmlLoggingConfiguration(XmlReader reader) ctor, improved docs and annotations
  src/NLog/Config/XmlLoggingConfiguration.cs
Labels: documentation, enhancement, size/M

#3515 Release 4.6.6
  CHANGELOG.md
  build.ps1
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/NLog.csproj
  src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
  tests/NLog.UnitTests/Targets/Wrappers/AutoFlushTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/BufferingTargetWrapperTests.cs
Labels: merge when passing, size/L, version

#3516 Port NLog 4.6.6 to dev
  CHANGELOG.md
  appveyor.yml
  build.ps1
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/Internal/FileAppenders/BaseMutexFileAppender.cs
  src/NLog/NLog.csproj
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
  tests/NLog.UnitTests/MessageTemplates/RendererTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/AutoFlushTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/BufferingTargetWrapperTests.cs
Labels: merge when passing, size/L

#3522 NetworkTarget - Fix InternalLogger.Trace to include Target name
  src/NLog/Targets/NetworkTarget.cs
Labels: enhancement, size/XS

#3524 Retry / improve unstable tests
  tests/NLog.UnitTests/AsyncHelperTests.cs
  tests/NLog.UnitTests/LogReceiverService/LogReceiverServiceTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/RetryingTargetWrapperTests.cs
Labels: size/L, unstable test

#3523 ColoredConsoleTarget - Added DetectOutputRedirected to skip coloring on redirect
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleTarget.cs
  tests/NLog.UnitTests/Targets/ColoredConsoleTargetTests.cs
Labels: enhancement, has unittests, size/M

#3527 XmlLayout - Defer allocation of ObjectReflectionCache until needed
  src/NLog/Layouts/XmlElementBase.cs
Labels: performance, size/XS
