Repository NLog/NLog, pull requests merged in 2019-01, with the labels that each got.

#3064 Improve EventLogTarget installation logic. Make public const values internal
  run-tests.ps1
  src/NLog.Extended/NLog.Extended.csproj
  src/NLog/Targets/EventLogTarget.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.UnitTests/Targets/EventLogTargetTests.cs
Labels: refactoring

#3067 AppDomainWrapper - BaseDirectory = null for Xamarin Android
  src/NLog/Internal/Fakeables/AppDomainWrapper.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
Labels: enhancement

#3071 Added ${HostName} Layout Renderer
  src/NLog/LayoutRenderers/HostNameLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/HostNameLayoutRendererTests.cs
Labels: feature, needs documentation on wiki

#3073 Small improvements (debugging, gitignore, DocFileBuilder)
  src/.gitignore
  src/NLogAutoLoadExtension/AutoLoadTarget.cs
  tools/CheckSourceCode/.gitignore
  tools/DumpApiXml/DocFileBuilder.cs
Labels: refactoring

#3074 LogLevel implement IConvertible
  src/NLog/LogLevel.cs
Labels: enhancement

#2610 Add notifications when Target drops LogEvent or cache size grows, grow *2 instead of +1
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/Wrappers/AsyncRequestQueue-T.cs
  src/NLog/Targets/Wrappers/AsyncRequestQueueBase.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
  src/NLog/Targets/Wrappers/LogEventDroppedEventArgs.cs
  src/NLog/Targets/Wrappers/LogEventQueueGrowEventArgs.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncRequestQueueTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/ConcurrentRequestQueueTests.cs
Labels: feature, has unittests

#3078 Fixed test LogEventDropped_OnRequestqueueOverflow when fast async
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
Labels: test

#3053 Added ${appsetting} - LayoutRenderer for easier access to app.config settings
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/LayoutRenderers/AppSettingLayoutRenderer2.cs
  tests/NLog.UnitTests/Config/ConfigurationItemFactoryTests.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
  tests/NLog.UnitTests/LayoutRenderers/AppSettingTests.cs
Labels: feature

#3075 LogLevel.GetTypeCode to Object, added tests
  src/NLog/LogLevel.cs
  tests/NLog.UnitTests/LayoutRenderers/LogLevelTests.cs
Labels: enhancement, test

#2899 Database target: support for DbType for parameters (including SqlDbType, OracleDbType etc.)
  src/NLog/Internal/DatabaseParameterTypeSetter.cs
  src/NLog/Targets/DatabaseParameterInfo.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/DatabaseValueConverter.cs
  src/NLog/Targets/IDatabaseValueConverter.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
  tests/NLog.UnitTests/Targets/DatabaseValueConverterTests.cs
Labels: database-target, feature

#3083 MemoryTarget - Added property MaxLogsCount
  src/NLog/Targets/MemoryTarget.cs
  src/NLog/Targets/Target.cs
  tests/NLog.UnitTests/Common/LastLogEventListTarget.cs
  tests/NLog.UnitTests/Fluent/LogBuilderTests.cs
  tests/NLog.UnitTests/LogManagerTests.cs
  tests/NLog.UnitTests/LoggerTests.cs
Labels: feature

#3088 SonarLint - Refactoring to reduce code complexity
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
Labels: refactoring

#3089 SonarLint - Refactoring to reduce code complexity (Fix performance)
  src/NLog/Targets/ColoredConsoleTarget.cs
Labels: refactoring

#3085 DatabaseTarget - Added support for PropertyName in DbType
  src/NLog/Internal/DatabaseParameterTypeSetter.cs
  src/NLog/Targets/DatabaseParameterInfo.cs
  src/NLog/Targets/DatabaseTarget.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: database-target, performance, refactoring

#3092 Support ${tempdir} for internalLogFile (nlog.config)
  src/NLog/Config/LoggingConfigurationParser.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
Labels: feature, nlog-configuration

#3079 File target: Handle UnauthorizedAccessException for multi-process mutexes (e.g. Xamarin and UWP)
  src/NLog/Internal/FileAppenders/BaseMutexFileAppender.cs
  src/NLog/Internal/PlatformDetector.cs
  src/NLog/Targets/FileTarget.cs
Labels: Xamarin, enhancement, file-target
