Repository NLog/NLog, pull requests merged in 2019-08, with the labels that each got.

#3532 Fix summary of NoRawValueLayoutRendererWrapper class
  src/NLog/LayoutRenderers/Wrappers/NoRawValueLayoutRendererWrapper.cs
Labels: documentation, size/XS

#3530 Added test cases for ValueFormatter
  tests/NLog.UnitTests/MessageTemplates/ValueFormatterTest.cs
Labels: enhancement, size/L

#3540 MessageTemplateParameters - Skip object allocation when no parameters
  src/NLog/LogEventInfo.cs
  src/NLog/MessageTemplates/MessageTemplateParameters.cs
Labels: performance, size/S

#3558 ExceptionLayoutRenderer - Added Source as new format parameter.
  src/NLog/Config/ExceptionRenderingFormat.cs
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
Labels: feature, size/M

#3546 NetworkTarget - HttpNetworkSender no longer sends out-of-order
  src/NLog/Internal/ExceptionHelper.cs
  src/NLog/Internal/NetworkSenders/HttpNetworkSender.cs
  src/NLog/Internal/NetworkSenders/IWebRequestFactory.cs
  src/NLog/Internal/NetworkSenders/QueuedNetworkSender.cs
  src/NLog/Internal/NetworkSenders/TcpNetworkSender.cs
  tests/NLog.UnitTests/Internal/NetworkSenders/HttpNetworkSenderTests.cs
  tests/NLog.UnitTests/Mocks/WebRequestMock.cs
Labels: enhancement, network/NLogViewer-target, size/L

#3541 MessageTemplateParameters - Improve validation of parameters when isPositional
  src/NLog/MessageTemplates/MessageTemplateParameters.cs
  tests/NLog.UnitTests/MessageTemplates/MessageTemplateParametersTests.cs
Labels: enhancement, size/M, test

#3184 Added support for dynamic layout renderer in log level filters (e.g. minLevel, maxLevel)
  src/NLog/Config/DynamicLogLevelFilter.cs
  src/NLog/Config/DynamicRangeLevelFilter.cs
  src/NLog/Config/ILoggingRuleLevelFilter.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/LoggingRule.cs
  src/NLog/Config/LoggingRuleLevelFilter.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
Labels: feature, nlog-configuration, size/XL

#3560 WhenMethodFilter - Support dynamic filtering using lambda
  src/NLog/Filters/WhenMethodFilter.cs
  src/NLog/Filters/WhenRepeatedFilter.cs
  tests/NLog.UnitTests/Filters/APITests.cs
Labels: feature, size/M

#3531 Added ${object-path} / ${exception:objectpath=PropertyName}, for rendering a property of an object (e.g. an exception)
  src/NLog/Internal/ObjectPropertyHelper.cs
  src/NLog/LayoutRenderers/EventPropertiesLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/ObjectPathRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WrapperLayoutRendererBase.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/ObjectPathRendererWrapperTests.cs
Labels: feature, merge when passing, needs documentation on wiki, needs documention on nlog-project.org/config, size/L

#3562 XmlLoggingConfiguration - Support ThrowConfigExceptions=true when invalid xml
  src/NLog/Config/ConfigSectionHandler.cs
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/LoggingConfigurationWatchableFileLoader.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
  tests/NLog.UnitTests/LogFactoryTests.cs
Labels: size/L

#3561 Version 4.6.7
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: merge when passing, version
