Repository NLog/NLog, pull requests merged in 2019-05, with the labels that each got.

#3353 StringBuilderPool - Added unit test of MaxCapacity checks
  tests/NLog.UnitTests/Internal/StringBuilderPoolTests.cs
Labels: test

#3354 Enabled SimpleFileDeleteTest on Travis - Verify that FileSystemWatcher works on .NET Core
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: test

#2315 Fix typo in NLogTraceListener.ProcessLogEventInfo
  src/NLog/NLogTraceListener.cs
Labels: breaking change

#2658 Move all WCF targets to NLog.Wcf
  src/NLog.Wcf/NLog.Wcf.csproj
  src/NLog/LogReceiverService/BaseLogReceiverForwardingService.cs
  src/NLog/LogReceiverService/ILogReceiverClient.cs
  src/NLog/LogReceiverService/ILogReceiverOneWayClient.cs
  src/NLog/LogReceiverService/ILogReceiverServer.cs
  src/NLog/LogReceiverService/ILogReceiverTwoWayClient.cs
  src/NLog/LogReceiverService/IWcfLogReceiverClient.cs
  src/NLog/LogReceiverService/LogReceiverForwardingService.cs
  src/NLog/LogReceiverService/LogReceiverOneWayForwardingService.cs
  src/NLog/LogReceiverService/LogReceiverServiceConfig.cs
  src/NLog/LogReceiverService/NLogEvent.cs
  src/NLog/LogReceiverService/NLogEvents.cs
  src/NLog/LogReceiverService/SoapLogReceiverClient.cs
  src/NLog/LogReceiverService/StringCollection.cs
  src/NLog/LogReceiverService/WcfILogReceiverClient.cs
  src/NLog/LogReceiverService/WcfLogReceiverClient.cs
  src/NLog/LogReceiverService/WcfLogReceiverOneWayClient.cs
  src/NLog/NLog.csproj
  src/NLog/Targets/LogReceiverWebServiceTarget.cs
  tests/NLog.UnitTests/LogReceiverService/LogReceiverForwardingServiceTests.cs
  tests/NLog.UnitTests/LogReceiverService/LogReceiverServiceTests.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
Labels: feature, merge when passing

#3356 Check MustBeRethrown for exception in ConfigurationItemFactory
  src/NLog/Config/ConfigurationItemFactory.cs
Labels: breaking change, enhancement, merge when passing

#3358 LoggingConfigurationChangedEventArgs: removed obsolete OldConfiguration and NewConfiguration properties (replaced with ActivatedConfiguration and DeactivatedConfiguration in NLog 4.5)
  src/NLog/Config/LoggingConfigurationChangedEventArgs.cs
Labels: breaking change, enhancement, merge when passing

#3355 ConfigSectionHandler, implement non obsolete base class
  src/NLog/Config/ConfigSectionHandler.cs
Labels: breaking change, nlog-configuration

#2069 LayoutRenderer Initialize should swallow exceptions when configured
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/Targets/MethodCallTarget.cs
  tests/NLog.UnitTests/Targets/MethodCallTests.cs
Labels: breaking change, enhancement, error-handling

#3360 Filetarget: default encoding changed to UTF8 - was Encoding.Default
  src/NLog/Targets/FileTarget.cs
Labels: breaking change, enhancement, file-target, merge when passing

#3357 Removed obsolete ExceptionLoggingOldStyle
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Internal/LoggerConfiguration.cs
  src/NLog/LogFactory.cs
  src/NLog/Logger-generated.cs
  src/NLog/Logger-generated.tt
  src/NLog/NullLogger.cs
  tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs
Labels: breaking change, enhancement, merge when passing

#3364 ${callsite} set clean options default to true
  src/NLog/LayoutRenderers/CallSiteLayoutRenderer.cs
Labels: enhancement, merge when passing

#3368 Removed reference on Microsoft.CSharp for net45 + net40
  src/NLog/NLog.csproj
Labels: refactoring

#2672 Log4JXml - Removed redundant logging of exception, default IncludeNLogData to false
  src/NLog/Internal/XmlHelper.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/Layouts/Log4JXmlEventLayout.cs
  src/NLog/Targets/ChainsawTarget.cs
  src/NLog/Targets/NLogViewerTarget.cs
Labels: enhancement

#3361 Change Simplelayout.ToString - skip additional quotes
  src/NLog/Conditions/ConditionLayoutExpression.cs
  src/NLog/Conditions/ConditionLiteralExpression.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/SimpleLayout.cs
  tests/NLog.UnitTests/Conditions/ConditionParserTests.cs
  tests/NLog.UnitTests/Config/TargetConfigurationTests.cs
  tests/NLog.UnitTests/Layouts/CompoundLayoutTests.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutOutputTests.cs
  tests/NLog.UnitTests/Targets/MailTargetTests.cs
  tools/CheckSourceCode/src/NLog.SourceCodeTests/SourceCodeTests.cs
Labels: breaking change, enhancement, squash when passing

#3369 XML configuration: variables are now case insensitive
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Internal/StringHelpers.cs
  tests/NLog.UnitTests/Config/VariableTests.cs
  tests/NLog.UnitTests/Internal/StringHelpersTests.cs
Labels: breaking behavior change, feature, merge when passing

#3004 Support for aliases for LayoutRenderer, targets, conditions etc. + Added some aliases
  src/NLog/Config/Factory.cs
  src/NLog/Config/NameBaseAttribute.cs
  src/NLog/Filters/FilterAttribute.cs
  src/NLog/Internal/PropertyHelper.cs
  src/NLog/Internal/ReflectionHelpers.cs
  src/NLog/Internal/StackTraceUsageUtils.cs
  src/NLog/LayoutRenderers/AssemblyVersionLayoutRenderer.cs
  src/NLog/LayoutRenderers/DbNullLayoutRenderer.cs
  src/NLog/LayoutRenderers/DocumentUriLayoutRenderer.cs
  src/NLog/LayoutRenderers/EventPropertiesLayoutRenderer.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/LayoutRenderers/LayoutRendererAttribute.cs
  src/NLog/LayoutRenderers/LoggerNameLayoutRenderer.cs
  src/NLog/LayoutRenderers/TraceActivityIdLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/WhenEmptyLayoutRendererWrapper.cs
  src/NLog/Layouts/LayoutAttribute.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/TargetAttribute.cs
  src/NLog/Time/TimeSource.cs
  tests/NLog.UnitTests/LayoutRenderers/EventPropertiesTests.cs
  tests/NLog.UnitTests/LayoutRenderers/LoggerNameTests.cs
  tests/NLog.UnitTests/Targets/TargetTests.cs
Labels: feature, merge when passing, needs documentation on wiki

#3359 Changed default action for filters to ignore when there are filters configured
  src/NLog/Config/LoggingRule.cs
  src/NLog/LoggerImpl.cs
  tests/NLog.UnitTests/Config/CaseSensitivityTests.cs
  tests/NLog.UnitTests/Config/DuplicateConfigurationAttributeTests.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
  tests/NLog.UnitTests/Filters/ConditionBasedFilterTests.cs
  tests/NLog.UnitTests/Filters/WhenContainsTests.cs
  tests/NLog.UnitTests/Filters/WhenEqualTests.cs
  tests/NLog.UnitTests/Filters/WhenNotContainsTests.cs
  tests/NLog.UnitTests/Filters/WhenNotEqualTests.cs
  tests/NLog.UnitTests/Filters/WhenRepeatedTests.cs
Labels: breaking behavior change, enhancement

#3371 Drop NLog.Extended, Introduce NLog.MSMQ
  README-developers.md
  README.md
  appveyor.yml
  build.ps1
  src/Docs/NLog.shfbproj
  src/NLog.Extended/CustomDictionary.xml
  src/NLog.Extended/GlobalSuppressions.cs
  src/NLog.Extended/LayoutRenderers/AppSettingLayoutRenderer.cs
  src/NLog.MSMQ/NLog.MSMQ.csproj
  src/NLog.MSMQ/Properties/AssemblyInfo.cs
  src/NLog.MSMQ/Targets/MessageQueueTarget.cs
  src/NLog.sln
  src/NLog/Config/ConfigurationItemFactory.cs
  tests/NLog.UnitTests/Config/ConfigurationItemFactoryTests.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tools/CheckSourceCode/NLog.SourceCodeTests.exe.config
  tools/CheckSourceCode/src/NLog.SourceCodeTests/App.config
Labels: merge when passing, packages split

#3373 ${when}, support for RawValue on Inner and Else
  src/NLog/LayoutRenderers/Wrappers/WhenLayoutRendererWrapper.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/WhenTests.cs
Labels: feature, merge when passing

#3376 Scan for process specific nlog-config first
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
Labels: breaking behavior change, enhancement, merge when passing

#3389 Log4JXmlEventLayout - Added support for configuration of Parameters
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/Layouts/JsonAttribute.cs
  src/NLog/Layouts/Log4JXmlEventLayout.cs
  src/NLog/Targets/NLogViewerParameterInfo.cs
  tests/NLog.UnitTests/LayoutRenderers/Log4JXmlTests.cs
Labels: feature

#3391 Added ${environment-user}
  src/NLog/LayoutRenderers/EnvironmentUserLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/EnvironmentUserLayoutRendererTests.cs
  tests/NLog.UnitTests/LayoutRenderers/IdentityTests.cs
Labels: feature

#3394 ${when}, support for RawValue on Inner and Else (backport)
  src/NLog/LayoutRenderers/Wrappers/WhenLayoutRendererWrapper.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/WhenTests.cs
Labels: feature

#3393 Update package descriptions to note the issues with <PackageReference>
  src/NuGet/NLog.Config/NLog.Config.nuspec
  src/NuGet/NLog.Schema/NLog.Schema.nuspec
Labels: documentation

#3392 Update xsd: Added defaultAction attribute on filters element
  src/NLog/Config/LoggingRule.cs
  tools/MakeNLogXSD/TemplateXSD.xml
Labels: XSD change

#3398 ${whenEmpty} implemented IRawValue and IStringValueRenderer
  src/NLog/LayoutRenderers/Wrappers/WhenEmptyLayoutRendererWrapper.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/WhenEmptyTests.cs
Labels: feature, squash when passing

#3415 ConcurrentRequestQueue - Fixed deadlock caused by misunderstanding Monitor.Wait
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
Labels: bug

#3411 LoggingConfigurationParser - Recognize LoggingRule.RuleName property
  src/NLog/Config/LoggingConfigurationParser.cs
Labels: feature, nlog-configuration

#3416 Async / buffering wrapper: Improve performance when blocking
  src/NLog/Targets/Wrappers/AsyncRequestQueue-T.cs
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/ConcurrentRequestQueueTests.cs
Labels: performance

#3404 Serialization: improved support for custom expando objects
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/Internal/PropertiesDictionary.cs
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/Internal/XmlHelper.cs
  src/NLog/Layouts/XmlElementBase.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Internal/ExpandoTestDictionary.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: enhancement

#3409 Various XSD improvements (NLog.Schema package)
  tools/MakeNLogXSD/TemplateXSD.xml
Labels: XSD change, documentation, enhancement, merge when passing, nlog-configuration

#3412 BufferingTargetWrapper - Avoid Timer starvation when SlidingTimeout = true
  src/NLog/Common/LogEventInfoBuffer.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
Labels: bug

#3423 ${all-event-properties}: Added IncludeEmptyValues option
  src/NLog/LayoutRenderers/AllEventPropertiesLayoutRenderer.cs
  tests/NLog.UnitTests/Layouts/AllEventPropertiesTests.cs
Labels: feature

#3428 Build projects in Parallel, improve build script
  build.ps1
Labels: build-config

#3434 ObjectReflectionCache - Skip property-reflection for IFormattable
  src/NLog/Internal/ObjectReflectionCache.cs
Labels: enhancement

#3435 Async / buffering wrapper: Improve performance when blocking
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
Labels: performance, refactoring

#3429 Remove obsolete methodes, properties and classes
  src/NLog.Wcf/LogReceiverService/ILogReceiverClient.cs
  src/NLog.Wcf/Targets/LogReceiverWebServiceTarget.cs
  src/NLog/Abstractions/ILogger.cs
  src/NLog/Abstractions/ILoggerBase.cs
  src/NLog/Annotations.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Contexts/GDC.cs
  src/NLog/Contexts/MDC.cs
  src/NLog/Contexts/NDC.cs
  src/NLog/LayoutRenderers/AppSettingLayoutRenderer2.cs
  src/NLog/LayoutRenderers/Contexts/EventContextLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/EventPropertiesLayoutRenderer.cs
  src/NLog/LogEventInfo.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
  src/NLog/Logger-generated.cs
  src/NLog/Logger-generated.tt
  src/NLog/Logger.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/IJsonSerializer.cs
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/TargetWithLayoutHeaderAndFooter.cs
  src/NLog/Targets/Wrappers/ImpersonatingTargetWrapper.cs
  src/NLog/Targets/Wrappers/PostFilteringTargetWrapper.cs
  src/NLog/Targets/Wrappers/SplitGroupTarget.cs
  tests/NLog.UnitTests/Config/CultureInfoTests.cs
  tests/NLog.UnitTests/Contexts/GlobalDiagnosticsContextTests.cs
  tests/NLog.UnitTests/Contexts/MappedDiagnosticsContextTests.cs
  tests/NLog.UnitTests/Contexts/NestedDiagnosticsContextTests.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
  tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs
  tests/NLog.UnitTests/LogFactoryTests.cs
  tests/NLog.UnitTests/LoggerTests.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: breaking behavior change, merge when passing, needs documentation on wiki

#3445 Move ILoggerExtensions.cs out of Abstractions folder
  src/NLog/ILoggerExtensions.cs
Labels: merge when passing, refactoring

#3443 split part of Platformdetector into MutexDetector
  src/NLog/Internal/FileAppenders/BaseMutexFileAppender.cs
  src/NLog/Internal/MutexDetector.cs
  src/NLog/Internal/PlatformDetector.cs
  src/NLog/Targets/FileTarget.cs
Labels: refactoring

#3442 Log4JXmlEventLayout - Added IncludeCallSite + IncludeSourceInfo
  src/NLog/Layouts/Log4JXmlEventLayout.cs
Labels: feature, needs documentation on wiki
