Repository NLog/NLog, pull requests merged in 2019-12, with the labels that each got.

#3714 FileTarget - Added support for MaxArchiveDays
  src/NLog/Targets/FileArchiveModes/FileArchiveModeBase.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDate.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDateAndSequence.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDynamicSequence.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDynamicTemplate.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeFactory.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeRolling.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeSequence.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/IFileArchiveMode.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: feature, file-archiving, file-target, size/L

#3521 XmlLoggingConfiguration - Constructors with ignoreErrors parameter are obsolete
  src/NLog/Config/XmlLoggingConfiguration.cs
Labels: enhancement, size/M

#3730 LogLevel - Recognize LogLevel names that matches Format.FullName
  src/NLog/LogLevel.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
  tests/NLog.UnitTests/LogLevelTests.cs
Labels: enhancement, size/S

#3728 Enable Source Link
  src/NLog/NLog.csproj
Labels: feature, size/XS

#3733 FileTarget - enable test ArchiveAboveSizeWithArchiveNumberingModeDate_maxfiles_o
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: size/XS, test

#3734 FileTarget - Write time details to InternalLogger when file is older than MaxArchiveDays
  src/NLog/Targets/FileArchiveModes/FileArchiveModeBase.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDate.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDateAndSequence.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDynamicSequence.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeSequence.cs
Labels: feature, file-archiving, file-target, size/S

#3735 WebServiceTarget - Skip delegate capture for beginGetRequest + getRequestStream
  src/NLog/Targets/WebServiceTarget.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
Labels: performance, size/M, webservice-target

#3739 NetworkTarget - Copy into buffer to avoid Encoding doing String.ToCharArray
  src/NLog/Targets/NetworkTarget.cs
  tests/NLog.UnitTests/Targets/NetworkTargetTests.cs
Labels: network/NLogViewer-target, performance, size/S

#3732 DatabaseTarget - DbType enum parsing should not be case-sensitive
  src/NLog/Common/ConversionHelpers.cs
  src/NLog/Targets/DatabaseParameterInfo.cs
  tests/NLog.UnitTests/Internal/EnumHelpersTests.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
  tests/NLog.UnitTests/Targets/EventLogTargetTests.cs
Labels: bug, size/L

#3686 LogFactory.Setup to allow fluent configuration of LogFactory options
  src/NLog/Config/ISetupBuilder.cs
  src/NLog/Config/ISetupExtensionsBuilder.cs
  src/NLog/Internal/SetupBuilder.cs
  src/NLog/Internal/SetupExtensionsBuilder.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
  src/NLog/SetupBuilderExtensions.cs
  src/NLog/SetupExtensionsBuilderExtensions.cs
  tests/NLog.UnitTests/Config/LogFactorySetupTests.cs
Labels: enhancement, size/XL, squash when passing

#3736 Drop old Sonar and Open cover integration
  appveyor.yml
  run-sonar.ps1
  run-tests.ps1
Labels: size/M
