Repository NLog/NLog, pull requests merged in 2019-04, with the labels that each got.

#3260 Fix escaping nested close brackets
  src/NLog/Layouts/LayoutParser.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
Labels: bug, nlog-configuration

#3271 NLog config - Fixed bug where empty xml-elements were ignored
  src/NLog/Config/NLogXmlElement.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
Labels: bug

#3272 Version 4.6.2
  CHANGELOG.md
  build.ps1
  src/NLog/Config/NLogXmlElement.cs
  src/NLog/Layouts/LayoutParser.cs
  src/NLog/NLog.csproj
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
  tests/NLog.UnitTests/LayoutRenderers/AssemblyVersionTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
Labels: version

#3265 Refactor WindowsIdentityLayoutRenderer
  src/NLog/LayoutRenderers/WindowsIdentityLayoutRenderer.cs
Labels: refactoring

#3263 SonarLint and CodeFactor warning reduction + better internal logging
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/NLogXmlElement.cs
  src/NLog/ILogger-V1.cs
  src/NLog/LayoutRenderers/NdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/NdlcLayoutRenderer.cs
  src/NLog/Layouts/XmlElementBase.cs
  src/NLog/LogFactory.cs
  src/NLog/Logger-generated.cs
  src/NLog/Logger-generated.tt
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/NetworkTarget.cs
  src/NLog/Targets/TargetWithContext.cs
  src/NLogAutoLoadExtension/AutoLoadTarget.cs
Labels: refactoring

#3279 AsyncTaskTarget_TestThrottleOnTaskDelay - More logging and increase treshold
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: merge when passing, test

#3278 ConsoleTarget & ColoredConsoleTarget - Added AutoFlush and improve default flush behavior
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleTarget.cs
  tests/NLog.UnitTests/Targets/ColoredConsoleTargetTests.cs
  tests/NLog.UnitTests/Targets/ConsoleTargetTests.cs
Labels: console-target, enhancement, feature, merge when passing

#3282 Disable KeepAliveTimeConfigTest on Travis
  tests/NLog.UnitTests/Targets/NetworkTargetTests.cs
Labels: test

#3280 Remove duplicate testcase
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: merge when passing, test

#3285 Added MessageTemplateParameterTests.PositionalIndex unittest
  tests/NLog.UnitTests/MessageTemplates/MessageTemplateParameterTests.cs
Labels: merge when passing, test

#3287 Cleanup unused ctor
  src/NLog/NullLogger.cs
Labels: merge when passing, refactoring

#3291 Added MessageTemplateParametersTests (IsPositionalTest, IndexerTest, EnumeratorTest)
  tests/NLog.UnitTests/MessageTemplates/MessageTemplateParametersTests.cs
Labels: merge when passing, test

#3293 Move to xUnit 2.4 and Microsoft.NET.Test.Sdk 16
  tests/NLog.UnitTests/Internal/PropertiesDictionaryTests.cs
  tests/NLog.UnitTests/LogMessageFormatterTests.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.UnitTests/NLogTestBase.cs
Labels: dependencies, merge when passing, test

#3295 LogFactory - Reduce code complexity of GetLogger
  src/NLog/LogFactory.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Time/TimeSource.cs
Labels: refactoring

#3296 Moved NLogAutoLoadExtension to tests folder & added solution folders
  .travis.yml
  run-tests.ps1
  src/NLog.sln
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLogAutoLoadExtension/AutoLoadTarget.cs
  tests/NLogAutoLoadExtension/NLogAutoLoadExtension.csproj
  tests/NLogAutoLoadExtension/Properties/AssemblyInfo.cs
Labels: Misc, merge when passing

#3299 AsyncTaskTarget_TestThrottleOnTaskDelay - More waiting for timers added
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: merge when passing, unstable test

#3307 AsyncTaskTarget_TestThrottleOnTaskDelay - Changed to ConcurrentQueue
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: unstable test

#3306 XmlLoggingConfiguration - Respect KeepVariablesOnReload for manual reload
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationWatchableFileLoader.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
Labels: enhancement, nlog-configuration

#3305 AppSettingLayoutRenderer - Mark as ThreadSafe and ThreadAgnostic
  src/NLog/LayoutRenderers/AppSettingLayoutRenderer2.cs
  tests/NLog.UnitTests/LayoutRenderers/AppSettingTests.cs
Labels: enhancement

#3309 AsyncTaskTarget - Unit test MDLC
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: test

#3311 Split string - avoid allocation of object array. Added StringHelpers.SplitAndTrimTokens
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Internal/Fakeables/AppDomainWrapper.cs
  src/NLog/Internal/PropertyHelper.cs
  src/NLog/Internal/StackTraceUsageUtils.cs
  src/NLog/Internal/StringHelpers.cs
  src/NLog/LayoutRenderers/AssemblyVersionLayoutRenderer.cs
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  src/NLog/Targets/DatabaseParameterInfo.cs
  src/NLog/Targets/MailTarget.cs
  tests/NLog.UnitTests/Internal/StringHelpersTests.cs
Labels: merge when passing, performance

#3310 Refactor ParseAttributes
  src/NLog/Config/NLogXmlElement.cs
Labels: merge when passing, refactoring

#3316 TargetWithContext - serialize MDC and MDLC values properly
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
Labels: bug, has unittests, merge when passing

#3298 Added WithProperty and SetProperty on Logger
  src/NLog/Internal/LoggerConfiguration.cs
  src/NLog/LogFactory.cs
  src/NLog/Logger-generated.cs
  src/NLog/Logger-generated.tt
  src/NLog/Logger.cs
  src/NLog/LoggerImpl.cs
  tests/NLog.UnitTests/LoggerTests.cs
Labels: feature

#3312 Fix various Sonar warnings
  src/NLog/Config/LoggerNameMatcher.cs
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/Internal/PropertyHelper.cs
  src/NLog/Internal/SortHelpers.cs
  src/NLog/Internal/UrlHelper.cs
  src/NLog/LayoutRenderers/NdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/NdlcLayoutRenderer.cs
  src/NLog/LayoutRenderers/VariableLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/ReplaceNewLinesLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/TrimWhiteSpaceLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/UrlEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/JsonLayout.cs
  src/NLog/MappedDiagnosticsContext.cs
  src/NLog/MappedDiagnosticsLogicalContext.cs
  src/NLog/MessageTemplates/MessageTemplateParameter.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/LogReceiverWebServiceTarget.cs
  src/NLog/Targets/NetworkTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/TargetWithContext.cs
  src/NLog/Targets/WebServiceTarget.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
  src/NLog/Targets/Wrappers/FallbackGroupTarget.cs
  src/NLog/Targets/Wrappers/ImpersonatingTargetWrapper.cs
  src/NLog/Targets/Wrappers/PostFilteringTargetWrapper.cs
  tests/NLog.UnitTests/Internal/UrlHelperTests.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: merge when passing, refactoring

#3325 Fix Travis build
  .travis.yml
Labels: build-config, merge when passing

#3323 Fix typo in documentation of AddRuleForAllLevels
  src/NLog/Config/LoggingConfiguration.cs
Labels: documentation, merge when passing

#3320 FallbackGroupTarget - Fixed spelling of WINDOWS_PHONE define + improvement GarbageCollection2Test() unit test on Travis
  .travis.yml
  src/NLog/Targets/Wrappers/FallbackGroupTarget.cs
  tests/NLog.UnitTests/LogManagerTests.cs
Labels: bug, merge when passing

#3328 Added truncate ambient property, e.g. ${message:truncate=80}
  src/NLog/LayoutRenderers/Wrappers/LeftLayoutRendererWrapper.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/LeftLayoutRendererWrapperTests.cs
Labels: feature

#3329 ${event-properties} - Added ObjectPath for extracting nested object property
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/LayoutRenderers/EventPropertiesLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/EventPropertiesTests.cs
Labels: feature

#3322 FileTarget - Skip FileSystemWatcher unless ConcurrentWrites=true
  src/NLog/Config/LoggingRule.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/CountingSingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/FileAppenders/ICreateFileParameters.cs
  src/NLog/Internal/FileAppenders/SingleProcessFileAppender.cs
  src/NLog/Internal/MultiFileWatcher.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: enhancement, file-target

#3336 CallSiteTests are now working on Mono after Travis upgrade
  tests/NLog.UnitTests/LayoutRenderers/CallSiteTests.cs
Labels: test

#3337 ShortDateLayoutRenderer with support for IRawValue + IStringValueRenderer
  src/NLog/LayoutRenderers/ShortDateLayoutRenderer.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: enhancement

#3338 Update docs of various context classes
  src/NLog/GDC.cs
  src/NLog/LayoutRenderers/GdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/MdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/MdlcLayoutRenderer.cs
  src/NLog/LayoutRenderers/NdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/NdlcLayoutRenderer.cs
  src/NLog/MDC.cs
  src/NLog/MappedDiagnosticsContext.cs
  src/NLog/NDC.cs
  src/NLog/NestedDiagnosticsContext.cs
Labels: documentation

#3339 Small code improvements
  src/NLog/Conditions/ConditionMethodExpression.cs
  src/NLog/Internal/EnvironmentHelper.cs
  src/NLog/Internal/FileAppenders/CountingSingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/SingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs
  src/NLog/Internal/FilePathLayout.cs
  src/NLog/Internal/MruCache.cs
  src/NLog/Internal/NetworkSenders/TcpNetworkSender.cs
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/LayoutRenderers/ProcessNameLayoutRenderer.cs
  src/NLog/Layouts/SimpleLayout.cs
  src/NLog/LogFactory.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeRolling.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/WebServiceTarget.cs
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
Labels: merge when passing, refactoring

#3340 Rename internal EscapeEncodingFlags
  src/NLog/Internal/UrlHelper.cs
  src/NLog/LayoutRenderers/Wrappers/UrlEncodeLayoutRendererWrapper.cs
  src/NLog/Targets/WebServiceTarget.cs
  tests/NLog.UnitTests/Internal/UrlHelperTests.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: merge when passing, refactoring

#3335 LoggingConfiguration - Rollback static Reload-method
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationWatchableFileLoader.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
Labels: enhancement

#3344 Reduce code complexity, small code improvements
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Internal/FilePathLayout.cs
  src/NLog/Internal/PropertiesDictionary.cs
  src/NLog/MessageTemplates/TemplateEnumerator.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/DatabaseTarget.cs
Labels: merge when passing, refactoring

#3345 Fixed potential memory issue with large strings
  src/NLog/Internal/StringBuilderPool.cs
Labels: bug, csv-layout, performance
