Repository NLog/NLog, pull requests merged in 2019-03, with the labels that each got.

#3124 NetworkTarget - Added support for KeepAliveTimeSeconds
  src/NLog/Internal/NetworkSenders/INetworkSenderFactory.cs
  src/NLog/Internal/NetworkSenders/NetworkSenderFactory.cs
  src/NLog/Internal/NetworkSenders/TcpNetworkSender.cs
  src/NLog/Targets/NetworkTarget.cs
  tests/NLog.UnitTests/Targets/NetworkTargetTests.cs
Labels: feature

#3159 AppSettingLayoutRenderer - Include Item for NLog.Extended
  src/NLog.Extended/LayoutRenderers/AppSettingLayoutRenderer.cs
Labels: enhancement

#3160 Refactor filetarget + target to reduce code complexity
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/NLogViewerTarget.cs
  src/NLog/Targets/Target.cs
Labels: file-target, refactoring

#3162 ContextProperty with IncludeEmptyValue means default value for ValueType
  src/NLog/Targets/MethodCallTargetBase.cs
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
Labels: enhancement

#3131 DatabaseTarget - Removed logEvent-parameter from CreateDatabaseParameter
  src/NLog/Targets/DatabaseTarget.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: breaking change (but never released as RTM), database-target, enhancement, refactoring

#3164 ObjectGraphScanner - Reduce complexity for ScanProperties
  src/NLog/Internal/ObjectGraphScanner.cs
Labels: refactoring

#3165 Database target: dropped UseRawValue option on parameters, introduced ${myRenderer:noRawValue=true}
  src/NLog/LayoutRenderers/Wrappers/NoRawValueLayoutRendererWrapper.cs
  src/NLog/Targets/DatabaseParameterInfo.cs
  src/NLog/Targets/DatabaseTarget.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: breaking change (but never released as RTM), database-target, enhancement, feature, needs documentation on wiki

#3169 FileTarget - Reduce code-complexity of DoAutoArchive
  src/NLog/Targets/FileTarget.cs
Labels: file-target, refactoring

#3176 UnitTest - Debug mode should not suppress evil exceptions
  src/NLog/Internal/ExceptionHelper.cs
  tests/NLog.UnitTests/AsyncHelperTests.cs
  tests/NLog.UnitTests/Internal/ExceptionHelperTests.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutOutputTests.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
  tests/NLog.UnitTests/Targets/MailTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/BufferingTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/FallbackGroupTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/RepeatingTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/RetryingTargetWrapperTests.cs
Labels: enhancement

#3175 LoggerTests - Testing reset of parseMessageTemplates state
  tests/NLog.UnitTests/LoggerTests.cs
Labels: unstable test

#3183 Added nuget deploy secret
  appveyor.yml
Labels: build-config

#3187 AsyncTaskTarget - Fixed unwanted delay caused by slow writer
  src/NLog/Targets/AsyncTaskTarget.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: enhancement

#3188 Release 4.6
  CHANGELOG.md
  build.ps1
  src/NLog.Extended/NLog.Extended.csproj
  src/NLog.Wcf/NLog.Wcf.csproj
  src/NLog.WindowsEventLog/NLog.WindowsEventLog.csproj
  src/NLog.WindowsIdentity/NLog.WindowsIdentity.csproj
  src/NLog/NLog.csproj
  src/NLog/Targets/AsyncTaskTarget.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: version

#3196 Fix link
  src/NLog/NLog.csproj
Labels: documentation

#3191 VariableLayoutRenderer - Fixed format-string for internal logger warning
  src/NLog/LayoutRenderers/VariableLayoutRenderer.cs
Labels: enhancement

#3198 XmlLayout - Fixed missing encode of xml element value
  src/NLog/Layouts/XmlAttribute.cs
  src/NLog/Layouts/XmlElement.cs
  src/NLog/Layouts/XmlElementBase.cs
  src/NLog/Layouts/XmlLayout.cs
  tests/NLog.UnitTests/Layouts/XmlLayoutTests.cs
Labels: bug, xml-layout

#3195 SimpleStringReader: fix DebuggerDisplay value
  src/NLog/Internal/SimpleStringReader.cs
  tests/NLog.UnitTests/Internal/SimpleStringReaderTests.cs
Labels: documentation

#3189 AsyncTaskTarget - Respect TaskDelayMilliseconds on low activity
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: enhancement

#3199 LoggingConfigurationParser - Fixed bug in handling of extensions prefix
  src/NLog/Config/LoggingConfigurationParser.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
Labels: bug, nlog-configuration

#3202 NLogTraceListener - Reduce code complexity of ProcessLogEventInfo
  src/NLog/NLogTraceListener.cs
Labels: refactoring

#3201 ${GDC} reading is now lockfree
  src/NLog/GlobalDiagnosticsContext.cs
  src/NLog/LogEventInfo.cs
Labels: enhancement, performance

#3256 ${NDLC} + ${NDC} - Faster checking when TopFrames = 1
  src/NLog/LayoutRenderers/NdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/NdlcLayoutRenderer.cs
Labels: performance

#3255 Auto-flush on process exit improvements
  src/NLog/Common/AsyncHelpers.cs
  src/NLog/Internal/AsyncHelpersTask.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: enhancement

#3253 Fix wrong warnings on <nlog> element + refactoring
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/NLogXmlElement.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
Labels: bug, nlog-configuration, refactoring

#3258 Fix error with Embedded Assembly in LogAssemblyVersion
  src/NLog/Common/InternalLogger.cs
Labels: bug

#3259 FileTarget refactoring removing CodeFactor issues
  src/NLog/Targets/FileTarget.cs
Labels: file-target, refactoring
