Repository NLog/NLog, pull requests merged in 2019-09, with the labels that each got.

#3566 DatabaseTarget: escape specials chars password properly, handle empty username and database correctly
  src/NLog/Targets/DatabaseTarget.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: bug, database-target, size/L

#3575 Fix some typos in comments
  src/NLog.sln.DotSettings
  src/NLog/Annotations.cs
  src/NLog/Common/AsyncHelpers.cs
  src/NLog/Common/InternalLogger.cs
  src/NLog/Conditions/ConditionRelationalExpression.cs
  src/NLog/Config/AppDomainFixedOutputAttribute.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/ILoggingConfigurationLoader.cs
  src/NLog/Config/LoggerNameMatcher.cs
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingRule.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/GlobalDiagnosticsContext.cs
  src/NLog/Internal/ExceptionHelper.cs
  src/NLog/Internal/FileAppenders/BaseMutexFileAppender.cs
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/FileAppenders/MutexMultiProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs
  src/NLog/Internal/FilePathLayout.cs
  src/NLog/Internal/LayoutHelpers-generated.cs
  src/NLog/Internal/LayoutHelpers-generated.tt
  src/NLog/Internal/NetworkSenders/INetworkSenderFactory.cs
  src/NLog/Internal/NetworkSenders/TcpNetworkSender.cs
  src/NLog/Internal/PropertyHelper.cs
  src/NLog/Internal/StackTraceUsageUtils.cs
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/Internal/StringSplitter.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/Layouts/CsvLayout.cs
  src/NLog/Layouts/LayoutParser.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
  src/NLog/LoggerImpl.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/NestedDiagnosticsLogicalContext.cs
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/ConsoleTargetHelper.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/EventLogTarget.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/JsonSerializeOptions.cs
  src/NLog/Targets/LogReceiverWebServiceTarget.cs
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/WebServiceTarget.cs
  src/NLog/Targets/Wrappers/AsyncRequestQueueBase.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
  src/NLog/Targets/Wrappers/LogEventQueueGrowEventArgs.cs
  tests/NLog.UnitTests/Targets/ConcurrentFileTargetTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: enhancement, size/L

#3579 PerformanceCounterLayoutRenderer - Added Layout support for Instance
  src/NLog/LayoutRenderers/PerformanceCounterLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/PerformanceCounterLayoutRendererTests.cs
Labels: size/L

#3578 LogFactory - AutoShutdown to allow users to control shutdown logic
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
  tests/NLog.UnitTests/Config/InternalLoggingTests.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
Labels: XSD change, feature, size/M

#3574 Added adapter for layout transformations
  src/NLog/Internal/TransformedLayout.cs
  src/NLog/Targets/DatabaseTarget.cs
Labels: refactoring, size/L

#3584 LoggingRule.SetLoggingLevels() fixed IndexOutOfRangeException when using LogLevel.Off
  src/NLog/Config/DynamicLogLevelFilter.cs
  src/NLog/Config/LoggingRuleLevelFilter.cs
  tests/NLog.UnitTests/Config/ConfigApiTests.cs
Labels: bug, size/M

#3585 Improve docs for Loggertype
  src/NLog/LogFactory-T.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
Labels: documentation, size/M

#3593 AllEventPropertiesLayoutRenderer - Added support for Exclude with OrdinalIgnoreCase
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/Internal/PropertyHelper.cs
  src/NLog/Internal/ReflectionHelpers.cs
  src/NLog/LayoutRenderers/AllEventPropertiesLayoutRenderer.cs
  tests/NLog.UnitTests/Layouts/AllEventPropertiesTests.cs
Labels: feature, needs documentation on wiki, size/L, squash when passing

#3583 Added ${local-ip} and cachedSeconds ambient property
  src/NLog/LayoutRenderers/HostNameLayoutRenderer.cs
  src/NLog/LayoutRenderers/INetworkInterfaceRetriever.cs
  src/NLog/LayoutRenderers/LocalIpAddressLayoutRenderer.cs
  src/NLog/LayoutRenderers/NetworkInterfaceRetriever.cs
  src/NLog/LayoutRenderers/Wrappers/CachedLayoutRendererWrapper.cs
  tests/NLog.UnitTests/LayoutRenderers/LocalIpAddressLayoutRendererTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/CachedTests.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
Labels: feature, needs documentation on wiki, needs documention on nlog-project.org/config, size/XL, squash when passing

#3586 JSON layout and ${json-encode}, added EscapeForwardSlash (default false).
  src/NLog/LayoutRenderers/Wrappers/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/JsonAttribute.cs
  src/NLog/Layouts/JsonLayout.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/JsonSerializeOptions.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/JsonEncodeTests.cs
Labels: feature, size/L
