Repository NLog/NLog, pull requests merged in 2020-08, with the labels that each got.

#4065 Nlog 4.7.3 to dev
  src/.editorconfig
  src/NLog.sln
  src/NLog/Config/LoggingRule.cs
  src/NLog/Internal/Collections/MruCache.cs
  src/NLog/Internal/Reflection/ObjectReflectionCache.cs
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  src/NLog/LayoutRenderers/Machine/LocalIpAddressLayoutRenderer.cs
  src/NLog/LogFactory.cs
  src/NLog/MessageTemplates/Literal.cs
  src/NLog/MessageTemplates/TemplateEnumerator.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/Wrappers/FilteringTargetWrapper.cs
  src/NLog/Targets/Wrappers/PostFilteringTargetWrapper.cs
  tests/NLog.UnitTests/Config/ConfigApiTests.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
  tests/NLog.UnitTests/LayoutRenderers/LocalIpAddressLayoutRendererTests.cs
Labels: size/L

#4068 FileTarget - Improve diagnostic logging to see reason for archiving
  src/NLog/Targets/FileTarget.cs
Labels: file-archiving, file-target, size/XS

#4069 Fluent LogBuilder should suppress exception on invalid callerFilePath
  src/NLog/Fluent/Log.cs
Labels: bug, size/S

#4071 Merge ChangeLog for Version 4.7.3 into dev
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: size/M

#4079 Log4JXmlEventLayoutRenderer should use be injected withIAppEnvironmen…
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
Labels: size/XS

#4078 BufferingWrapper should use AsyncRequestQueue instead of LogEventInfo…
  src/NLog.Wcf/Targets/LogReceiverWebServiceTarget.cs
  src/NLog/Common/LogEventInfoBuffer.cs
  src/NLog/Targets/Wrappers/AsyncRequestQueue-T.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
Labels: size/S

#4073 FileTarget - Extra validation of the LogEvent-timestamp before checking time to archive
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: enhancement, file-archiving, file-target, size/M

#4082 BufferingTargetWrapper - Minor cleanup after changing to AsyncRequestQueue
  src/NLog/Targets/Wrappers/AsyncRequestQueue-T.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
Labels: refactoring, size/S

#4076 DatabaseTarget - Added AllowDbNull for easier support for nullable pa…
  src/NLog/Targets/DatabaseParameterInfo.cs
  src/NLog/Targets/DatabaseTarget.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: database-target, feature, size/L

#4102 LoggingConfiguration - ValidateConfig should only throw when enabled
  src/NLog/Common/AsyncHelpers.cs
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/Wrappers/WrapperTargetBase.cs
  tests/NLog.UnitTests/Config/TargetConfigurationTests.cs
  tests/NLog.UnitTests/LayoutRenderers/EnvironmentTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/WhenTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
Labels: enhancement, size/L
