Repository NLog/NLog, pull requests merged in 2020-01, with the labels that each got.

#3743 JsonLayout - EscapeForwardSlash should be nullable
  src/NLog/LayoutRenderers/Wrappers/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/JsonAttribute.cs
  src/NLog/Layouts/JsonLayout.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
Labels: enhancement, json / json-layout, size/M

#3742 TraceTarget - Introduced EnableTraceFail=false to avoid Environment.FailFast
  src/NLog/Targets/TraceTarget.cs
  tests/NLog.UnitTests/NLogTraceListenerTests.cs
Labels: breaking behavior change, enhancement, size/S

#3745 Renamed folder StringBuilderPools to ObjectPools
  src/NLog/Internal/AsyncHelpersTask.cs
  src/NLog/Internal/AsyncOperationCounter.cs
  src/NLog/Internal/Collections/CollectionExtensions.cs
  src/NLog/Internal/Collections/MruCache.cs
  src/NLog/Internal/Collections/ThreadSafeDictionary.cs
  src/NLog/Internal/ObjectPools/AppendBuilderCreator.cs
  src/NLog/Internal/ObjectPools/ReusableAsyncLogEventList.cs
  src/NLog/Internal/ObjectPools/ReusableBufferCreator.cs
  src/NLog/Internal/ObjectPools/ReusableBuilderCreator.cs
  src/NLog/Internal/ObjectPools/ReusableObjectCreator.cs
  src/NLog/Internal/ObjectPools/ReusableStreamCreator.cs
  src/NLog/Internal/ObjectPools/StringBuilderPool.cs
  src/NLog/Internal/Reflection/ObjectPropertyHelper.cs
  src/NLog/Internal/SingleCallContinuation.cs
  src/NLog/Internal/TimeoutContinuation.cs
  src/NLog/LayoutRenderers/Machine/INetworkInterfaceRetriever.cs
  src/NLog/LayoutRenderers/Machine/LocalIpAddressLayoutRenderer.cs
  src/NLog/LayoutRenderers/Machine/NetworkInterfaceRetriever.cs
Labels: refactoring

#3750 ExceptionLayoutRenderer - Improve Format-token parsing error message
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
Labels: enhancement, size/S

#3748 AsyncTaskTarget - Skip AsyncWrapper since already having internal queue
  src/NLog/Config/LoggingConfigurationParser.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: performance, size/L

#3747 AutoFlushWrapper - Set AutoFlush=false for AsyncTaskTarget by default
  src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: enhancement, new default (breaking), performance, size/M

#3758 LogFactory - Fix deadlock issue with AutoReload
  src/NLog/Config/LoggingConfigurationWatchableFileLoader.cs
  src/NLog/Internal/MultiFileWatcher.cs
Labels: bug, nlog-configuration, size/M

#3754 LocalIpAddressLayoutRenderer - Higher priority when valid gateway
  src/NLog/LayoutRenderers/LocalIpAddressLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/LocalIpAddressLayoutRendererTests.cs
Labels: enhancement, size/L

#3766 Layout - ThreadAgnostic should also verify nested Layouts
  src/NLog/Layouts/Layout.cs
  src/NLog/Targets/Target.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
Labels: bug, json / json-layout, size/S

#3767 Mark Condition Expressions as ThreadSafe. Improves concurrency
  src/NLog/Conditions/ConditionExpression.cs
Labels: performance, size/XS

#3764 DatabaseTarget: Added IsolationLevel option - activates transactions for batch writes
  src/NLog/Targets/DatabaseTarget.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
  tools/DumpApiXml/DocFileBuilder.cs
Labels: database-target, feature, performance, size/L

#3762 LogFactory - Flush should report to InternalLogger what targets produces timeout
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Internal/SingleCallContinuation.cs
  src/NLog/Internal/TimeoutContinuation.cs
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/LogFactoryTests.cs
Labels: enhancement, size/L, squash when passing

#3680 DI: Optimize constructor calls
  src/NLog/Config/ServiceRepository.cs
  src/NLog/Internal/Reflection/ReflectionHelpers.cs
Labels: size/L

#3771 Added Layout.CreateFromString with throwConfigExceptions parameter
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/LayoutParser.cs
  src/NLog/Layouts/SimpleLayout.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
Labels: API, enhancement, size/L, squash when passing

#3774 Added missing docgen for public config items
  src/NLog/LayoutRenderers/AllEventPropertiesLayoutRenderer.cs
  src/NLog/LayoutRenderers/BaseDirLayoutRenderer.cs
  src/NLog/LayoutRenderers/LocalIpAddressLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/LeftLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/ObjectPathRendererWrapper.cs
  src/NLog/Layouts/JsonAttribute.cs
  src/NLog/Layouts/XmlElement.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/NetworkTarget.cs
  src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs
Labels: documentation, size/S

#3773 LoggingConfiguration - Initialize should warn when LogManager.ThrowExceptions=true
  src/NLog/Config/LoggingConfiguration.cs
Labels: enhancement, size/XS

#3785 WebServiceTarget - Debug mode should not die because of System.Net.WebException
  src/NLog/Internal/ExceptionHelper.cs
  src/NLog/Internal/NetworkSenders/HttpNetworkSender.cs
Labels: enhancement, size/XS, squash when passing

#3786 ConditionMethodExpression - Skip array-allocation when calling method with no args
  src/NLog/Conditions/ConditionMethodExpression.cs
Labels: performance, size/S

#3784 Changed sort order for NDC of Log4JXmlEventLayoutRenderer
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/Log4JXmlTests.cs
Labels: bug, size/L

#3783 Rename Create methods on Layout - don't introduce obsoletes
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/LayoutRenderOptions.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
Labels: enhancement, size/M
