Repository NLog/NLog, pull requests merged in 2020-05, with the labels that each got.

#3940 ${Exception} - Added BaseException option
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
Labels: feature, needs documentation on wiki, size/M

#3921 BaseDirLayoutRenderer - Improve FixTempDir on Linux when TMPDIR is not set
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Internal/PathHelpers.cs
  src/NLog/LayoutRenderers/BaseDirLayoutRenderer.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
Labels: enhancement, size/M

#3949 Support for Replacing Windows Line Endings under Unix
  src/NLog/LayoutRenderers/Wrappers/ReplaceNewLinesLayoutRendererWrapper.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/ReplaceNewLinesTests.cs
Labels: feature, size/M

#3950 BufferingTargetWrapperTests - Make unit test more stable
  tests/NLog.UnitTests/Targets/Wrappers/BufferingTargetWrapperTests.cs
Labels: size/L, test

#3941 Removed ProcessIDHelper and extended AppEnvironment with current process details
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/LoggingConfigurationWatchableFileLoader.cs
  src/NLog/Config/NLogXmlElement.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/Internal/Fakeables/AppEnvironmentWrapper.cs
  src/NLog/Internal/Fakeables/IAppEnvironment.cs
  src/NLog/Internal/NativeMethods.cs
  src/NLog/Internal/PortableProcessIDHelper.cs
  src/NLog/Internal/ProcessIDHelper.cs
  src/NLog/Internal/Win32ProcessIDHelper.cs
  src/NLog/LayoutRenderers/BaseDirLayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/LayoutRenderers/ProcessDirLayoutRenderer.cs
  src/NLog/LayoutRenderers/ProcessIdLayoutRenderer.cs
  src/NLog/LayoutRenderers/ProcessNameLayoutRenderer.cs
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
  tests/NLog.UnitTests/LogFactoryTests.cs
  tests/NLog.UnitTests/Mocks/AppEnvironmentMock.cs
Labels: enhancement, refactoring, size/XL

#3639 WrapperLayoutRendererBuilderBase - Obsolete and no longer used
  src/NLog/LayoutRenderers/Wrappers/Encodings/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/Encodings/Rot13LayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/FileSystemNormalizeLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/String transformations/LowercaseLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/String transformations/ReplaceNewLinesLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/String transformations/TrimWhiteSpaceLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/String transformations/UppercaseLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WhenEmptyLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WhenLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WrapperLayoutRendererBuilderBase.cs
Labels: size/M

#3953 Added internal ExceptionMustBeRethrown helper to Target
  src/NLog/Common/IInternalLoggerContext.cs
  src/NLog/Internal/ExceptionHelper.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/LogReceiverWebServiceTarget.cs
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/MethodCallTarget.cs
  src/NLog/Targets/MethodCallTargetBase.cs
  src/NLog/Targets/PerformanceCounterTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/WebServiceTarget.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: enhancement, size/M

#3924 Version 4.7.1
  CHANGELOG.md
  appveyor.yml
  build.ps1
  src/NLog/NLog.csproj
Labels: size/L, version

#3962 XSD: Added Enabled attribute for <logger> + small description improvement
  tools/MakeNLogXSD/TemplateXSD.xml
Labels: XSD change, size/XS

#3967 FileTarget - ArchiveOldFileOnStartup not working together with ArchiveAboveSize
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: bug, file-archiving, file-target, size/M

#3969 FileTarget - ArchiveOldFileOnStartup not working together with ArchiveAboveSize
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: bug, file-archiving, file-target, size/M, squash when passing

#3968 Version 4.7.2
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: size/M, version

#3970 NLog 4.7.2 to dev
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
  tools/MakeNLogXSD/TemplateXSD.xml
Labels: merge when passing, size/M

#3972 Editor config with File header template
  src/.editorconfig
  src/NLog.sln
Labels: build-config, size/S

#3975 Capture CallSite ClassName only when WithCallSiteClassName enabled
  src/NLog/Config/StackTraceUsage.cs
  src/NLog/Internal/StackTraceUsageUtils.cs
  src/NLog/Internal/TargetWithFilterChain.cs
  src/NLog/LayoutRenderers/CallSite/CallSiteFileNameLayoutRenderer.cs
  src/NLog/LayoutRenderers/CallSite/CallSiteLayoutRenderer.cs
  src/NLog/LayoutRenderers/CallSite/CallSiteLineNumberLayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite and stacktraces/CallSiteTests.cs
Labels: enhancement, size/M

#3964 Delete codecov.yml
  codecov.yml
Labels: size/S

#3977 FilteringTargetWrapper - Remove delegate allocation
  src/NLog/Targets/Wrappers/FilteringTargetWrapper.cs
  src/NLog/Targets/Wrappers/PostFilteringTargetWrapper.cs
Labels: performance, size/XS

#3982 BaseDirLayoutRenderer - Remove Constructor with IAppDomain
  src/NLog/LayoutRenderers/Directories/BaseDirLayoutRenderer.cs
Labels: breaking change, size/S

#3985 Remove IDisposable from LayoutRenderer
  src/NLog/LayoutRenderers/LayoutRenderer.cs
Labels: breaking change, enhancement, size/S
