Repository NLog/NLog, pull requests merged in 2020-09, with the labels that each got.

#4106 FileTarget - New current file should write start header after archive of previous file
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: bug, file-archiving, file-target, size/M

#4115 Removed EmptyDefaultDictionary from MappedDiagnosticsContext
  src/NLog/MappedDiagnosticsContext.cs
  src/NLog/NestedDiagnosticsContext.cs
Labels: performance, size/M

#4109 Fix root .editorconfig to use end_of_line = CRLF. Remove local .editorconfig
  .editorconfig
  src/.editorconfig
  src/NLog.sln
Labels: refactoring, size/XS

#4114 Fix VerificationException Operation could destabilize the runtime
  src/NLog/Internal/AppendBuilderCreator.cs
  src/NLog/Internal/SortHelpers.cs
  src/NLog/MessageTemplates/Literal.cs
  src/NLog/MessageTemplates/LiteralHole.cs
  src/NLog/MessageTemplates/TemplateEnumerator.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
Labels: enhancement, size/S

#3990 Added new() contraint on LogFactory<T> and to GetLogger<T> / GetCurrentClassLogger<T>
  src/NLog/LogFactory-T.cs
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/GetLoggerTests.cs
Labels: breaking change, enhancement, size/S

#4113 Detect Microsoft.Data.SqlClient in DatabaseTarget
  src/NLog/Targets/DatabaseTarget.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: database-target, feature, size/M

#4120 Release 4.7.5
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: size/M, version

#4121 Merge NLog 4.7.5 to dev
  .editorconfig
  CHANGELOG.md
  build.ps1
  src/.editorconfig
  src/NLog.sln
  src/NLog/Common/AsyncHelpers.cs
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Contexts/MappedDiagnosticsContext.cs
  src/NLog/Contexts/NestedDiagnosticsContext.cs
  src/NLog/Internal/Collections/SortHelpers.cs
  src/NLog/Internal/ObjectPools/AppendBuilderCreator.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/Encodings/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/JSON/JsonAttribute.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/MessageTemplates/Literal.cs
  src/NLog/MessageTemplates/LiteralHole.cs
  src/NLog/MessageTemplates/TemplateEnumerator.cs
  src/NLog/NLog.csproj
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs
  src/NLog/Targets/Wrappers/WrapperTargetBase.cs
  tests/NLog.UnitTests/Config/TargetConfigurationTests.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
  tests/NLog.UnitTests/LayoutRenderers/EnvironmentTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/WhenTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: size/L

#4123 BucketSort - StringComparer.Ordinal should be faster than EqualityComparer.Default
  src/NLog/Internal/Collections/ThreadSafeDictionary.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/MailTarget.cs
Labels: performance, size/S
