Repository NLog/NLog, pull requests merged in 2020-02, with the labels that each got.

#3779 `null` layout should marked as FixedText
  src/NLog/Layouts/SimpleLayout.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
Labels: enhancement, performance, size/M

#3790 AsyncTargetWrapper - Do not schedule lazy writer timer, when other active writer
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: enhancement, size/M

#3793 Added ${dir-separator}
  src/NLog/LayoutRenderers/DirectorySeparatorLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/DirectorySeparatorLayoutRendererTests.cs
Labels: feature, size/L

#3794 Added Three Target tests for handling error situations
  tests/NLog.UnitTests/Targets/TargetTests.cs
Labels: has unittests, size/L

#3787 LogFactory.Setup with fluent registration of condition methods
  src/NLog/Conditions/ConditionMethodExpression.cs
  src/NLog/Conditions/ConditionParser.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/Factory.cs
  src/NLog/Config/MethodFactory.cs
  src/NLog/Internal/NetStandardHelpers.cs
  src/NLog/SetupExtensionsBuilderExtensions.cs
  tests/NLog.UnitTests/Config/LogFactorySetupTests.cs
Labels: API, enhancement, needs documentation on wiki, size/L

#3679 If Load of Extension-Assembly fails, try AppDomain before rethrowing Exception
  .travis.yml
  src/NLog.sln
  src/NLog/Internal/AssemblyHelpers.cs
  tests/ManuallyLoadedExtension/ManuallyLoadedExtension.csproj
  tests/ManuallyLoadedExtension/ManuallyLoadedTarget.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
Labels: enhancement, has unittests, size/M

#3755 Add support for optional size threshold to archive log file on startup
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/FileAppenders/IFileAppenderCache.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: feature, file-archiving, file-target, needs documentation on wiki, size/L

#3796 InternalLogger: added LogMessageReceived event
  src/NLog/Common/InternalLogger.cs
  src/NLog/Common/InternalLoggerMessageEventArgs.cs
  tests/NLog.UnitTests/Common/InternalLoggerTests.cs
Labels: feature, size/L

#3772 NLog ver. 4.7 changelog + 4.7-rc1 version
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: documentation, size/M, version

#3821 Logger should not crash when platform cannot capture StackTrace
  src/NLog/LoggerImpl.cs
Labels: bug, enhancement, size/M, squash when passing
