Repository NLog/NLog, pull requests merged in 2020-07, with the labels that each got.

#4031 FileTarget - MaxArchiveDays should also work with ArchiveNumbering=Sequence
  src/NLog/Targets/FileArchiveModes/FileArchiveModeBase.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDynamicSequence.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeSequence.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: enhancement, file-archiving, file-target, size/L

#4039 Removed obsolete DictionaryAdapter after LogEventInfo.Context was removed
  src/NLog/Internal/Collections/DictionaryAdapter.cs
  src/NLog/Internal/Collections/PropertiesDictionary.cs
  src/NLog/LogEventInfo.cs
Labels: refactoring, size/L

#4043 ObjectReflectionCache - Skip reflection for Stream objects
  src/NLog/Internal/ObjectReflectionCache.cs
Labels: enhancement, size/XS

#4053 MessageTemplates - Changed Literal.Skip to be Int32 for long message templates
  src/NLog/MessageTemplates/Literal.cs
  src/NLog/MessageTemplates/TemplateEnumerator.cs
Labels: bug, size/XS

#4023 LoggingConfiguration with support for automatic target re-initialize
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/ServiceRepositoryExtensions.cs
  src/NLog/Config/ServiceRepositoryInternal.cs
  src/NLog/Internal/LogMessageTemplateFormatter.cs
  src/NLog/Internal/Reflection/ObjectReflectionCache.cs
  src/NLog/LayoutRenderers/Contexts/EventPropertiesLayoutRenderer.cs
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/ObjectPathRendererWrapper.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
  src/NLog/LogFactory.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/SetupSerializationBuilderExtensions.cs
  src/NLog/Targets/Target.cs
  tests/NLog.UnitTests/Config/ServiceRepositoryTests.cs
Labels: feature, size/L

#4046 Set properties of ProcessStartInfo correctly
  tests/NLog.UnitTests/ProcessRunner.cs
Labels: enhancement, size/XS

#4055 AsyncTargetWrapper and AsyncTaskTarget will enqueue when missing dependency
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
Labels: feature, size/L

#4057 ObjectReflectionCache - Reduce noise from properties that throws exceptions
  src/NLog/Internal/ObjectReflectionCache.cs
Labels: enhancement, json / json-layout, size/XS

#4058 FileTarget - Skip delegate capture in GetFileCreationTimeSource
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/FileAppenders/RetryingMultiProcessFileAppender.cs
  src/NLog/Internal/FileInfoExt.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDynamicSequence.cs
Labels: file-archiving, file-target, performance, size/S

#4064 Release 4.7.3
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: merge when passing, size/M, version
