Repository NLog/NLog, pull requests merged in 2020-12, with the labels that each got.

#4182 Failing to lookup ProcessName because of Access Denied should fallback to Win32-API
  src/NLog/Internal/Fakeables/AppEnvironmentWrapper.cs
  src/NLog/Internal/NativeMethods.cs
Labels: bug, size/L

#4190 Added DebuggerDisplay for custom dictionary-collections
  src/NLog/Internal/PropertiesDictionary.cs
  src/NLog/Internal/ThreadSafeDictionary.cs
Labels: enhancement, size/XS

#4185 Version 4.7.6
  CHANGELOG.md
  build.ps1
  src/NLog.sln
  src/NLog/NLog.csproj
Labels: size/M, squash when passing, version

#4193 Merge NLog 4.7.6 to dev
  CHANGELOG.md
  appveyor.yml
  build.ps1
  src/NLog.sln
  src/NLog/Conditions/Expressions/ConditionLayoutExpression.cs
  src/NLog/Conditions/Parsing/ConditionParser.cs
  src/NLog/Internal/AppEnvironmentWrapper.cs
  src/NLog/Internal/Collections/PropertiesDictionary.cs
  src/NLog/Internal/Collections/ThreadSafeDictionary.cs
  src/NLog/Internal/NativeMethods.cs
  src/NLog/Internal/NetworkSenders/NetworkSender.cs
  src/NLog/Internal/NetworkSenders/UdpNetworkSender.cs
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/CachedLayoutRendererWrapper.cs
  src/NLog/NLog.csproj
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Conditions/ConditionEvaluatorTests.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/CachedTests.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: merge when passing, size/XL

#4202 Generate correct json for keys that contain quote
  src/NLog/Layouts/JsonLayout.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
Labels: size/S

#4205 Improved 4.7.6 Changelog
  CHANGELOG.md
Labels: documentation, size/XS

#4124 ScopeContext to replace MDLC and NDLC
  src/NLog/Abstractions/IIncludeContext.cs
  src/NLog/Contexts/MappedDiagnosticsLogicalContext.cs
  src/NLog/Contexts/NestedDiagnosticsLogicalContext.cs
  src/NLog/Contexts/ScopeContext.cs
  src/NLog/LayoutRenderers/Contexts/NdlcTimingLayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/Layouts/Log4JXmlEventLayout.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
  src/NLog/Targets/NLogViewerTarget.cs
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.UnitTests/Contexts/MappedDiagnosticsLogicalContextTests.cs
  tests/NLog.UnitTests/Contexts/ScopeContextTest.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
  tests/NLog.UnitTests/Internal/Reflection/PropertyHelperTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/NDLCTests.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
  tests/NLog.UnitTests/Layouts/XmlLayoutTests.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
Labels: breaking behavior change, context, feature, refactoring, size/XXL

#4210 ScopeContext - Protect against memory-leak when pushing the same property again and again
  src/NLog/Contexts/MappedDiagnosticsLogicalContext.cs
  src/NLog/Contexts/ScopeContext.cs
  tests/NLog.UnitTests/Contexts/ScopeContextTest.cs
Labels: feature, size/L

#4211 ScopeContext - Renamed IncludeScopeOperationStates to IncludeScopeNestedStates
  src/NLog/Abstractions/IIncludeContext.cs
  src/NLog/Contexts/NestedDiagnosticsLogicalContext.cs
  src/NLog/Contexts/ScopeContext.cs
  src/NLog/LayoutRenderers/Contexts/NdlcTimingLayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/Layouts/Log4JXmlEventLayout.cs
  src/NLog/Targets/NLogViewerTarget.cs
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.UnitTests/Contexts/ScopeContextTest.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
Labels: feature, size/XL

#4212 ScopeContext - Moved CallContext logic into ScopeContext
  src/NLog/Contexts/MappedDiagnosticsLogicalContext.cs
  src/NLog/Contexts/NestedDiagnosticsLogicalContext.cs
  src/NLog/Contexts/ScopeContext.cs
Labels: feature, size/XL

#4213 ScopeContext - Added Logger-methods and layoutrenderers
  src/NLog/LayoutRenderers/Contexts/ScopeContextNestedStatesLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/ScopeContextPropertyLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/ScopeContextTimingLayoutRenderer.cs
  src/NLog/Logger.cs
  tests/NLog.UnitTests/Contexts/ScopeContextTest.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/NDLCTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/ScopePropertyTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/ScopeStackTests.cs
Labels: feature, size/XL

#4207 Skip allocation of SingleCallContinuation when ThrowExceptions = false
  src/NLog/Internal/SingleCallContinuation.cs
  src/NLog/LoggerImpl.cs
Labels: performance, size/XS

#4184 Removed InternalLogger static constructor and added extension method SetupFromEnvironmentVariables
  src/NLog/Common/InternalLogger.cs
  src/NLog/SetupInternalLoggerBuilderExtensions.cs
  tests/NLog.UnitTests/Config/LogFactorySetupTests.cs
Labels: breaking behavior change, size/M

#4218 ScopeContext - Merged with NDC + MDC
  .travis.yml
  src/NLog.sln
  src/NLog/Abstractions/IIncludeContext.cs
  src/NLog/Contexts/MappedDiagnosticsContext.cs
  src/NLog/Contexts/MappedDiagnosticsLogicalContext.cs
  src/NLog/Contexts/NestedDiagnosticsContext.cs
  src/NLog/Contexts/NestedDiagnosticsLogicalContext.cs
  src/NLog/Contexts/ScopeContext.cs
  src/NLog/Internal/ThreadLocalStorageHelper.cs
  src/NLog/LayoutRenderers/Contexts/MdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/MdlcLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/NdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/NdlcLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/NdlcTimingLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/ScopeContextNestedStatesLayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/Layouts/Log4JXmlEventLayout.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
  src/NLog/Logger.cs
  src/NLog/Targets/NLogViewerTarget.cs
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.UnitTests/Contexts/MappedDiagnosticsContextTests.cs
  tests/NLog.UnitTests/Contexts/MappedDiagnosticsLogicalContextTests.cs
  tests/NLog.UnitTests/Contexts/NestedDiagnosticsContextTests.cs
  tests/NLog.UnitTests/Contexts/ScopeContextTest.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
  tests/NLog.UnitTests/Internal/Reflection/PropertyHelperTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/MDCTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/MdlcLayoutRendererTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/NDCTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/NDLCTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/ScopeNestedTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Log4JXmlTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/Encodings/JsonEncodeTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/Encodings/Rot13Tests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/Encodings/XmlEncodeTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/FileSystemNormalizeTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/String transformations/ReplaceNewLinesTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/String transformations/TrimWhiteSpaceTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/String transformations/WrapLineTests.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
  tests/NLog.UnitTests/Layouts/XmlLayoutTests.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
  tests/NLog.UnitTests/Targets/MailTargetTests.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
  tests/NLog.UnitTests/Targets/Wrappers/FallbackGroupTargetTests.cs
Labels: breaking behavior change, feature, size/XXL
