Repository NLog/NLog, pull requests merged in 2020-06, with the labels that each got.

#3999 LogFactory Shutdown is public so it can be used from NLogLoggerProvider
  src/NLog/LogFactory.cs
Labels: size/XS

#3991 DirectorySeparatorLayoutRenderer - Removed public TryGetValue
  src/NLog/LayoutRenderers/DirectorySeparatorLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/DirectorySeparatorLayoutRendererTests.cs
Labels: size/S

#3974 ${exception) - Improved logging AggregrateException's Data
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
Labels: enhancement, size/L

#3997 Support RawValue with [AppDomainFixedOutput]
  src/NLog/LayoutRenderers/LiteralWithRawValueLayoutRenderer.cs
  src/NLog/Layouts/LayoutParser.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
Labels: enhancement, size/L, squash when passing

#3987 FileTarget: set writing BOM initial to true for UTF-16 and UTF-32
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: enhancement, file-target, new default (breaking), size/M

#4018 Added 'Reverse' option to StackTraceLayoutRenderer
  src/NLog/LayoutRenderers/CallSite/StackTraceLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite and stacktraces/StackTraceRendererTests.cs
Labels: size/L

#4017 Allow to change the RuleName of a LoggingRule
  src/NLog/Config/LoggingRule.cs
  tests/NLog.UnitTests/Config/ConfigApiTests.cs
Labels: enhancement, size/M

#4021 ObjectReflectionCache - Reduce initial memory allocation until needed
  src/NLog/Internal/MruCache.cs
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
Labels: performance, size/S

#4019 SetupExtensionsBuilderExtensions.RegisterLayoutRenderer supports LayoutRenderOptions
  src/NLog/Layouts/Layout.cs
  src/NLog/SetupExtensionsBuilderExtensions.cs
  tests/NLog.UnitTests/Config/LogFactorySetupTests.cs
Labels: size/L
