Repository NLog/NLog, pull requests merged in 2020-10, with the labels that each got.

#4126 Fix LogReceiverWebServiceTarget should remove its use of LogEventInfoBuffer
  src/NLog.Wcf/LogEventInfoBuffer.cs
  src/NLog.Wcf/Targets/LogReceiverWebServiceTarget.cs
Labels: refactoring, size/L

#4131 Improved docs for LogEventInfo constructor parameter loggerName
  src/NLog/LogEventInfo.cs
Labels: documentation, size/S

#4134 Fix LayoutParser should throw ConfigExceptions on unknown properties
  src/NLog/Layouts/LayoutParser.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/WhenEmptyTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
Labels: breaking behavior change, enhancement, size/M

#4143 LoggingConfigurationParser - Small refactoring to improve code-layout
  src/NLog/Config/LoggingConfigurationParser.cs
Labels: refactoring, size/S

#4142 JsonSerializer - Ensure invariant formatting of DateTimeOffset
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: bug, json / json-layout, size/M

#4132 Improve thead concurrency with Cache wrapper
  src/NLog/LayoutRenderers/Wrappers/CachedLayoutRendererWrapper.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/CachedTests.cs
Labels: performance, size/M

#4141 NetworkTarget - Improve handling of synchronous exceptions from UdpClient.SendAsync
  src/NLog/Internal/NetworkSenders/NetworkSender.cs
  src/NLog/Internal/NetworkSenders/UdpNetworkSender.cs
Labels: enhancement, network/NLogViewer-target, size/M

#4138 ProcessNameLayoutRenderer - Use ProcessName instead of MainModule.FileName
  src/NLog/Internal/AppEnvironmentWrapper.cs
  tests/NLog.UnitTests/LayoutRenderers/Processes/ProcessNameLayoutRendererTests.cs
Labels: breaking behavior change, enhancement, size/M
