Repository NLog/NLog, pull requests merged in 2020-03, with the labels that each got.

#3826 InternalLogger - Added Target context to LogMessageReceived event (more capture)
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/MethodCallTarget.cs
  src/NLog/Targets/MethodCallTargetBase.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: enhancement, size/XS

#3835 StringSplitter - Removed helper methods only used by unit-tests + small bugfix
  src/NLog/Internal/StringSplitter.cs
  tests/NLog.UnitTests/Internal/StringSplitterTests.cs
Labels: bug, refactoring, size/XL

#3834 Moved LoggingConfigurationElementExtensions into its own file
  src/NLog/Config/LoggingConfigurationElementExtensions.cs
  src/NLog/Config/LoggingConfigurationParser.cs
Labels: refactoring, size/L

#3829 DatabaseTarget - Added support for Connection Properties (e.g. for Azure AD Access Token)
  src/NLog/Internal/PropertySetter.cs
  src/NLog/Targets/DatabaseCommandInfo.cs
  src/NLog/Targets/DatabaseObjectPropertyInfo.cs
  src/NLog/Targets/DatabaseParameterInfo.cs
  src/NLog/Targets/DatabaseTarget.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: database-target, feature, size/L

#3832 Improved performance of ${replace} (10 times in tests)
  src/NLog/Internal/RegexHelper.cs
  src/NLog/LayoutRenderers/Wrappers/ReplaceLayoutRendererWrapper.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleWordHighlightingRule.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/ReplaceTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
Labels: performance, size/L

#3839 DatabaseTarget - Added support for DbCommand Properties
  src/NLog/Targets/DatabaseObjectPropertyInfo.cs
  src/NLog/Targets/DatabaseTarget.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: database-target, feature, size/M

#3840 LogLevel - Compare operators should not throw, translate null into LogLevel.Off
  src/NLog/LogLevel.cs
  tests/NLog.UnitTests/LogLevelTests.cs
Labels: breaking behavior change, refactoring, size/L

#3842 LogLevel - Compare operators should not throw, translate null into LogLevel.Off
  src/NLog/LogLevel.cs
Labels: refactoring, size/XS

#3830 Addded LateBoundMethodSingle
  src/NLog/Internal/PropertySetter.cs
  src/NLog/Internal/ReflectionHelpers.cs
  src/NLog/Targets/DatabaseParameterInfo.cs
Labels: performance, size/L

#3843 DatabaseTarget - RenderObjectValue should not lookup Type-name for InternalLogger.Trace
  src/NLog/Targets/DatabaseTarget.cs
Labels: database-target, performance, size/XS

#3833 Added ${OnHasProperties} - for easier custom output
  src/NLog/LayoutRenderers/AllEventPropertiesLayoutRenderer.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/OnHasPropertiesLayoutRendererWrapper.cs
  src/NLog/LogEventInfo.cs
  src/NLog/MessageTemplates/MessageTemplateParameters.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/OnHasPropertiesTests.cs
Labels: feature, needs documentation on wiki, size/L

#3828 Skip need for Activator.CreateInstance in DbTypeSetter + fix Enum.TryParse for whitespace
  src/NLog/Common/ConversionHelpers.cs
  src/NLog/Targets/DatabaseParameterInfo.cs
  src/NLog/Targets/MailTarget.cs
  tests/NLog.UnitTests/Internal/ConversionHelpersTests.cs
Labels: bug, needs unittests, performance, refactoring, size/L

#3819 Version 4.7.0
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: size/XS, version

#3849 Version 4.7.0 changelog to dev
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: merge when passing, size/M

#3860 Fix Changelog for SetupExtensions (NLog 4.7)
  CHANGELOG.md
Labels: size/XS

#3867 InternalLogger - Logging NLog version should include whether it is from GlobalAssemblyCache
  src/NLog/Common/InternalLogger.cs
Labels: enhancement, internal-log, size/XS

#3861 NLog InternalLogger Setup: added AddLogSubscription and RemoveLogSubscription
  src/NLog/SetupInternalLoggerBuilderExtensions.cs
  tests/NLog.UnitTests/Common/InternalLoggerTests.cs
Labels: enhancement, internal-log, size/S
