Repository NLog/NLog, pull requests merged in 2020-11, with the labels that each got.

#4153 ExceptionLayoutRenderer - Added FlattenException option
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
Labels: feature, size/M

#4172 AsyncTaskTarget - Flush when buffer is full should not block forever
  src/NLog/Targets/AsyncTaskTarget.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: bug, size/M

#4171 ConditionLayoutExpression - Skip allocating StringBuilder for every condition check
  src/NLog/Conditions/ConditionLayoutExpression.cs
  src/NLog/Conditions/ConditionLiteralExpression.cs
  src/NLog/Conditions/ConditionParser.cs
  tests/NLog.UnitTests/Conditions/ConditionEvaluatorTests.cs
Labels: performance, size/M

#4176 AsyncTaskTarget - Include TaskScheduler in ContinueWith
  src/NLog/Targets/AsyncTaskTarget.cs
Labels: enhancement, size/S

#4180 Update NuGet API key
  appveyor.yml
Labels: size/XS
