Repository NLog/NLog, pull requests merged in 2020-04, with the labels that each got.

#3868 SplitGroupTarget - Target write failure should not skip remaining targets
  src/NLog/Targets/Wrappers/SplitGroupTarget.cs
  tests/NLog.UnitTests/Targets/Wrappers/SplitGroupTargetTests.cs
Labels: bug, size/L

#3862 Support for ${ProcessDir} in internalLogFile when parsing nlog.config
  src/NLog/Config/LoggingConfigurationParser.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
Labels: enhancement, internal-log, size/S

#3876 Added .NET Core 3 to issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/XS

#3877 Added ${processdir} layoutrenderer to match InternalLogger path-token
  src/NLog/LayoutRenderers/BaseDirLayoutRenderer.cs
  src/NLog/LayoutRenderers/ProcessDirLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/ProcessDirTests.cs
Labels: enhancement, needs documentation on wiki, needs documention on nlog-project.org/config, size/L

#3879 Fix NLog 4.7 release date
  CHANGELOG.md
Labels: documentation, size/XS

#3855 FileTarget - Skip checking file-length on every file write, when using ArchiveEvery
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/LogFactoryTests.cs
Labels: file-archiving, file-target, performance, size/L

#3884 InternalLogger - Include FilePath when logging config is being initialized
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
Labels: enhancement, size/S

#3853 LogFactory - Marked broken constructor as obsolete. It is a trap.
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/Config/CultureInfoTests.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
  tests/NLog.UnitTests/LayoutRenderers/VariableLayoutRendererTests.cs
Labels: size/M

#3890 Update SHFB config
  src/Docs/NLog.shfbproj
Labels: build-config, size/M

#3904 ObjectReflectionCache - Skip reflection for Module objects
  src/NLog/Internal/ObjectReflectionCache.cs
Labels: enhancement, size/XS

#3902 LogEventInfo - PropertiesDictionary should not clone internal generated param list
  src/NLog/Internal/PropertiesDictionary.cs
  src/NLog/LogEventInfo.cs
Labels: performance, size/S

#3896 Write internallog warning for unrecognized properties used in config on layout renderers
  src/NLog/Internal/SimpleStringReader.cs
  src/NLog/Layouts/LayoutParser.cs
Labels: enhancement, nlog-configuration, size/L

#3894 ConditionExpression - Fixed boxing for Condition relational. Ex. equals
  src/NLog/Conditions/ConditionAndExpression.cs
  src/NLog/Conditions/ConditionExpression.cs
  src/NLog/Conditions/ConditionNotExpression.cs
  src/NLog/Conditions/ConditionOrExpression.cs
  src/NLog/Conditions/ConditionParser.cs
  src/NLog/Conditions/ConditionRelationalExpression.cs
Labels: performance, size/S

#3898 ObjectGraphScanner - Reuse reflection cache from PropertyHelper
  src/NLog/Internal/ObjectGraphScanner.cs
  src/NLog/Internal/PropertyHelper.cs
  src/NLog/Targets/Target.cs
Labels: nlog-configuration, performance, size/L

#3903 Layout - Object scanning should only check class-attributes for LayoutRenderers
  src/NLog/Conditions/ConditionExpression.cs
  src/NLog/Layouts/CsvColumn.cs
  src/NLog/Layouts/JsonAttribute.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/XmlAttribute.cs
  src/NLog/Layouts/XmlElement.cs
  src/NLog/Targets/NLogViewerParameterInfo.cs
  src/NLog/Targets/TargetPropertyWithContext.cs
Labels: performance, size/M

#3901 MappedDiagnosticsLogicalContext - SetScoped with IReadOnlyList for Xamarin
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Internal/ReflectionHelpers.cs
  src/NLog/LayoutRenderers/AllEventPropertiesLayoutRenderer.cs
  src/NLog/MappedDiagnosticsLogicalContext.cs
Labels: enhancement, size/S

#3857 FileTarget - Batch write to filestream in max chunksize of 100 times BufferSize
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: file-target, performance, size/L

#3881 ObjectReflectionCache - Added support for IReadOnlyDictionary as Expando-object
  src/NLog/Internal/ObjectReflectionCache.cs
  tests/NLog.UnitTests/Internal/ReadOnlyExpandoTestDictionary.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: enhancement, size/L

#3891 ColoredConsoleTarget - Allow using Condition-logic for word highlighting rules
  src/NLog/Targets/ColoredConsoleAnsiPrinter.cs
  src/NLog/Targets/ColoredConsoleSystemPrinter.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleWordHighlightingRule.cs
  src/NLog/Targets/IColoredConsolePrinter.cs
  tests/NLog.UnitTests/Targets/ColoredConsoleTargetTests.cs
Labels: console-target, feature, needs documentation on wiki, performance, size/L

#3895 Property type converter: fix converting to nullable value + lot of unit tests
  src/NLog/Config/PropertyTypeConverter.cs
  tests/NLog.UnitTests/Config/PropertyTypeConverterTests.cs
Labels: enhancement, size/L, test

#3909 LogManager - Setup - Added GetCurrentClassLogger and GetLogger
  src/NLog/SetupBuilderExtensions.cs
  tests/NLog.UnitTests/Config/LogFactorySetupTests.cs
Labels: enhancement, size/M

#3915 CaptureStackTrace=false to disable implicit callsite capture
  src/NLog/Internal/CallSiteInformation.cs
  src/NLog/LayoutRenderers/CallSiteFileNameLayoutRenderer.cs
  src/NLog/LayoutRenderers/CallSiteLayoutRenderer.cs
  src/NLog/LayoutRenderers/CallSiteLineNumberLayoutRenderer.cs
  src/NLog/LayoutRenderers/StackTraceLayoutRenderer.cs
  src/NLog/LogEventInfo.cs
  src/NLog/LoggerImpl.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteFileNameLayoutTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteLineNumberTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteTests.cs
  tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs
Labels: enhancement, size/L

#3918 ColoredConsoleTarget - Fix bug in handling of newlines without word-highlight
  src/NLog/Targets/ColoredConsoleTarget.cs
  tests/NLog.UnitTests/Targets/ColoredConsoleTargetTests.cs
Labels: bug, size/S

#3928 NetworkTarget - Respect MaxQueueSize in case of http(s)
  src/NLog/Internal/NetworkSenders/NetworkSenderFactory.cs
Labels: documentation on wiki done, enhancement, needs documentation on wiki, network/NLogViewer-target, size/S

#3934 NLogViewerTarget - Fixed Log4JXmlEventLayout
  src/NLog/Targets/NLogViewerTarget.cs
Labels: refactoring, size/XS

#3935 StreamHelpers - CopyAndSkipBom should check bytes read
  src/NLog/Internal/StreamHelpers.cs
Labels: refactoring, size/XS

#3933 EventLogTarget - Implement IDisposable for EventLogWrapper
  src/NLog/Targets/EventLogTarget.cs
Labels: enhancement, size/XS

#3932 XmlLayout - Avoid warning about IDisposable until we can remove it
  src/NLog/Layouts/XmlElement.cs
  src/NLog/Layouts/XmlElementBase.cs
  src/NLog/Layouts/XmlLayout.cs
Labels: refactoring, size/M

#3930 Report the searched paths when the config file can't be found
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/Config/LogFactorySetupTests.cs
Labels: enhancement, size/M
