Repository NLog/NLog, pull requests merged in 2021-12, with the labels that each got.

#4693 Update NuGet API key
  appveyor.yml
Labels: build-config, size/XS

#4697 Bump to Visual Studio 2022 on AppVeyor + Updated tools to .NET 4.7
  appveyor.yml
  tools/CheckSourceCode/src/NLog.SourceCodeTests/NLog.SourceCodeTests.csproj
  tools/DumpApiXml/DumpApiXml.csproj
  tools/MakeNLogXSD/MakeNLogXSD.csproj
  tools/MergeApiXml/MergeApiXml.csproj
Labels: build-config, size/S

#4698 FileTarget - EnableFileDeleteSimpleMonitor changed to Environment.TickCount
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/CountingSingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/SingleProcessFileAppender.cs
Labels: performance, file-target, size/S

#4700 AsyncTargetWrapper - Better performance when using OverflowAction Block
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: performance, size/XS

#4699 AsyncTargetWrapper - Better performance when using OverflowAction Block
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: performance, size/XS

#4701 NLog version 4.7.13
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version, size/S

#4703 Update appveyor.yml
  appveyor.yml
Labels: build-config, size/XS

#4704 ChangeLog for 4.7.13
  CHANGELOG.md
Labels: size/XS

#4705 LogEventInfo - Optimize copy messageTemplateParameters by caching Count
  src/NLog/LogEventInfo.cs
Labels: performance, size/XS

#4706 LogEventInfo - Optimize copy messageTemplateParameters by caching Count
  src/NLog/LogEventInfo.cs
Labels: performance, size/S

#4563 Added alias toupper and tolower
  src/NLog/LayoutRenderers/LevelLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/LowercaseLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/UppercaseLayoutRendererWrapper.cs
Labels: size/S

#4695 Ignore dash (-) when parsing (e.g. layouts, layout renderers, targets)
  src/NLog/Config/Factory.cs
  src/NLog/LayoutRenderers/Contexts/TraceActivityIdLayoutRenderer.cs
  src/NLog/LayoutRenderers/DbNullLayoutRenderer.cs
  src/NLog/LayoutRenderers/LoggerNameLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/WhenEmptyLayoutRendererWrapper.cs
  tests/ManuallyLoadedExtension/ManuallyLoadedExtension.csproj
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/WhenEmptyTests.cs
  tests/NLog.UnitTests/LogFactoryTests.cs
Labels: feature, size/L

#4713 Logger - SetProperty marked obsolete as it is unsafe
  src/NLog/Logger.cs
  tests/NLog.UnitTests/LoggerTests.cs
Labels: refactoring, size/XS

#4714 Hide obsolete methods from intellisense
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/Layouts/Log4JXmlEventLayout.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
  src/NLog/Logger.cs
  src/NLog/SetupExtensionsBuilderExtensions.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/JsonSerializeOptions.cs
  src/NLog/Targets/MethodCallParameter.cs
  src/NLog/Targets/NLogViewerTarget.cs
  src/NLog/Targets/NetworkTargetConnectionsOverflowAction.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/TargetWithContext.cs
Labels: refactoring, size/M

#4715 AsyncTargetWrapper - Exception on flush should still schedule timer
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: refactoring, size/M

#4677 NLog 5.0 Release Candidate 1
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version, size/M

#4711 Added WithProperties-method for Logger-class
  src/NLog/Logger.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/AllEventPropertiesTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
Labels: enhancement, size/L

#4719 NLog 5.0 RC1 ChangeLog
  CHANGELOG.md
Labels: version, size/M
