Repository NLog/NLog, pull requests merged in 2021-05, with the labels that each got.

#4426 WrapperLayoutRenderer - Undo Move Into Folders
  src/NLog/LayoutRenderers/Wrappers/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/LeftLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/LowercaseLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/PaddingHorizontalAlignment.cs
  src/NLog/LayoutRenderers/Wrappers/PaddingLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/ReplaceLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/ReplaceNewLinesLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/RightLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/SubstringLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/TrimWhiteSpaceLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/UppercaseLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/UrlEncodeLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/XmlEncodeLayoutRendererWrapper.cs
Labels: refactoring

#4422 Reduce InternalLogger debug-output when no targets configured for loglevel
  src/NLog/LogFactory.cs
Labels: enhancement, nlog-configuration, size/M

#4401 JsonSerializer - Fixed bug when handling custom IConvertible returning TypeCode.Empty
  src/NLog/Internal/XmlHelper.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: bug, json / json-layout, size/M

#4427 Release 4.7.10
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: size/S, version

#4428 Merge NLog 4.7.10 to dev
  CHANGELOG.md
  build.ps1
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Internal/XmlHelper.cs
  src/NLog/NLog.csproj
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: size/M, version

#4430 Unnamed Target inside AsyncWrapper should inherit the name
  src/NLog/Config/LoggingConfigurationParser.cs
  tests/NLog.UnitTests/Config/TargetConfigurationTests.cs
Labels: enhancement, nlog-configuration, size/M

#4431 Improve InternalLogger output for unnamed targets
  src/NLog/Config/LoggerNameMatcher.cs
  src/NLog/Config/LoggingRule.cs
  src/NLog/Targets/Target.cs
  tests/NLog.UnitTests/Config/ConfigApiTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/RetryingTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/SplitGroupTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/WrapperTargetBaseTests.cs
Labels: enhancement, size/M

#4433 Marked LogFactory.CurrentAppDomain as obsolete
  src/NLog/Config/ConfigSectionHandler.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Internal/Abstractions/IAppDomain.cs
  src/NLog/Internal/Abstractions/IAppEnvironment.cs
  src/NLog/Internal/AppDomains/AppDomainWrapper.cs
  src/NLog/Internal/AppDomains/FakeAppDomain.cs
  src/NLog/Internal/AppEnvironmentWrapper.cs
  src/NLog/Internal/Files/FilePathLayout.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/AppDomainLayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/LogFactory.cs
  src/NLog/Targets/EventLogTarget.cs
  tests/NLog.UnitTests/ApiTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Directories/BaseDirTests.cs
  tests/NLog.UnitTests/Mocks/AppDomainMock.cs
  tests/NLog.UnitTests/Mocks/AppEnvironmentMock.cs
  tests/NLog.UnitTests/Targets/EventLogTargetTests.cs
Labels: breaking change, refactoring, size/L

#4435 MailTarget - Apply Typed Layout for SmtpPort + Timeout
  src/NLog/Targets/MailTarget.cs
  tests/NLog.UnitTests/Targets/MailTargetTests.cs
Labels: breaking change, feature, size/L

#4436 Layout Typed - Removed StaticValue and implicit conversion to avoid surprises
  src/NLog/Layouts/Typed/Layout.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/WebServiceTarget.cs
  tests/NLog.UnitTests/Layouts/LayoutTypedTests.cs
  tests/NLog.UnitTests/Targets/TargetTests.cs
Labels: enhancement, size/L

#4437 PropertyTypeConverter - Direct mapping when nullable type matches value-type
  src/NLog/Config/PropertyTypeConverter.cs
  src/NLog/Layouts/Typed/Layout.cs
  tests/NLog.UnitTests/Layouts/LayoutTypedTests.cs
Labels: size/M

#4444 Layout Typed - Unassigned layout matches unassigned underlying value
  src/NLog/Layouts/Typed/Layout.cs
  tests/NLog.UnitTests/Layouts/LayoutTypedTests.cs
Labels: size/M
