Repository NLog/NLog, pull requests merged in 2021-07, with the labels that each got.

#4481 FileTarget - Validate the FileName when fixed value
  src/NLog/Internal/Files/FilePathLayout.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/LogManagerTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: enhancement, file-target, size/L

#4482 dependabot ignore System.Reflection.TypeExtensions ver. 4.7
  .github/dependabot.yml
  src/NLog.Database/NLog.Database.csproj
  src/NLog.sln
Labels: build-config, size/M

#4483 Reverted: FileTarget - Validate the FileName when fixed value
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: size/M

#4484 Fixed SimpleLayout TryGetRawValue() when LiteralWithRawValueLayoutRenderer
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/SimpleLayout.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
Labels: enhancement, size/S

#4485 Layout Typed - Fixed support for StackTraceUsage
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/Typed/Layout.cs
  tests/NLog.UnitTests/Layouts/LayoutTypedTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
Labels: enhancement, size/M

#4487 Disable xUnit1004 warning
  tests/NLog.UnitTests/NLog.UnitTests.csproj
Labels: build-config, refactoring, size/XS

#4488 ConfigureAwait(false) for all awaits
  src/NLog/Logger.cs
Labels: enhancement, size/S

#4501 TargetWithFilterChain - FilterChain becomes empty array, when no filters
  appveyor.yml
  src/NLog/Internal/TargetWithFilterChain.cs
  src/NLog/LogFactory.cs
  src/NLog/LoggerImpl.cs
Labels: performance, refactoring, size/S

#4504 DatabaseTarget - Close active connection before reporting Exception
  src/NLog.Database/DatabaseTarget.cs
Labels: database-target, refactoring, size/S
