Repository NLog/NLog, pull requests merged in 2021-11, with the labels that each got.

#4649 Fix broken XML doc comment
  src/NLog/Config/LoggingRule.cs
Labels: documentation, size/XS

#4656 FallbackGroupTarget - Added support for EnableBatchWrite
  src/NLog/Targets/Wrappers/FallbackGroupTarget.cs
  tests/NLog.UnitTests/Targets/Wrappers/BufferingTargetWrapperTests.cs
Labels: enhancement, size/L

#4655 JsonLayout - ExcludeProperties should also handle IncludeScopeProperties
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
Labels: enhancement, json / json-layout, size/XS

#4645 TargetPropertyWithContext - IncludeEmptyValue false by default
  src/NLog/Layouts/JSON/JsonAttribute.cs
  src/NLog/Layouts/Typed/ValueTypeLayoutInfo.cs
  src/NLog/Layouts/XML/XmlAttribute.cs
  src/NLog/Targets/NLogViewerParameterInfo.cs
  src/NLog/Targets/TargetPropertyWithContext.cs
  src/NLog/Targets/TargetWithContext.cs
Labels: enhancement, breaking behavior change, size/M, new default (breaking)

#4648 LogFactory fluent Setup with FilterDynamicIgnore + FilterDynamicLog
  src/NLog/Filters/WhenMethodFilter.cs
  src/NLog/SetupLoadConfigurationExtensions.cs
  tests/NLog.UnitTests/Config/LogFactorySetupTests.cs
Labels: enhancement, size/L

#4646 PropertiesDictionary - Generate unique message-template-names on duplicate keys
  src/NLog/Internal/Collections/PropertiesDictionary.cs
  src/NLog/LogEventBuilder.cs
  src/NLog/LogEventInfo.cs
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.UnitTests/Internal/PropertiesDictionaryTests.cs
Labels: enhancement, breaking behavior change, size/L

#4661 LoggingRule - Fix XML documentation
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/LoggingRule.cs
Labels: refactoring, size/S

#4644 Handle OutOfMemoryException instead of crashing the application
  src/NLog/Internal/ExceptionHelper.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
Labels: enhancement, size/S

#4662 LogFactory Setup fluent with SetupLogFactory for general options
  src/NLog/Config/ISetupLogFactoryBuilder.cs
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/ServiceRepositoryExtensions.cs
  src/NLog/Internal/SetupLogFactoryBuilder.cs
  src/NLog/LogFactory.cs
  src/NLog/SetupBuilderExtensions.cs
  src/NLog/SetupLogFactoryBuilderExtensions.cs
  tests/NLog.UnitTests/Config/LogFactorySetupTests.cs
Labels: feature, size/L

#4671 Fixed RegisterObjectTransformation to handle conversion to simple values
  src/NLog/Internal/Reflection/ObjectReflectionCache.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerClassTests.cs
Labels: breaking behavior change, size/M

#4672 PaddingLayoutRendererWrapper - Pad operation directly on StringBuilder
  src/NLog/LayoutRenderers/Wrappers/PaddingLayoutRendererWrapper.cs
Labels: performance, size/M

#4669 LogLevel - Replaced IConvertible with IFormattable for better Json serialization
  src/NLog/Attributes/LogLevelTypeConverter.cs
  src/NLog/Config/PropertyTypeConverter.cs
  src/NLog/LogLevel.cs
  tests/NLog.UnitTests/Internal/ExpandoTestDictionary.cs
  tests/NLog.UnitTests/LayoutRenderers/LogLevelTests.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: breaking change, refactoring, size/L

#4673 AsyncTargetWrapper - Improve logging around timer being scheduled
  src/NLog/LogLevel.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: refactoring, size/S

#4675 FileTarget - Improve fallback logic when running on Linux without File BirthTime
  src/NLog/Targets/FileTarget.cs
Labels: file-target, size/S, file-archiving

#4676 Updated nuget dependencies to System.ServiceModel ver. 4.4.4
  src/NLog.Wcf/NLog.Wcf.csproj
Labels: size/S

#4680 FileTarget - Updated SimpleFileDeleteTest to verify relative paths works
  src/NLog/Internal/Files/MultiFileWatcher.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: size/M

#4681 FileTarget - Updated SimpleFileDeleteTest to no delay on win32
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: test, refactoring, size/XS

#4682 FileTarget - Verify WriteBom when assigning Encoding
  src/NLog/Targets/FileTarget.cs
Labels: file-target, size/S

#4684 ConfigurationItemFactory - Added hint for MicrosoftConsoleJsonLayout
  src/NLog/Config/ConfigurationItemFactory.cs
Labels: refactoring, size/XS

#4686 Update CONTRIBUTING.md with default compiler defines for platforms
  .github/CONTRIBUTING.md
Labels: size/S

#4687 Removed Silverlight documentation projects
  src/Docs/Docs.csproj
  src/Docs/Frameworks/.NET Compact Framework 2.0.shfbproj
  src/Docs/Frameworks/.NET Compact Framework 3.5.shfbproj
  src/Docs/Frameworks/Mono 2.x.shfbproj
  src/Docs/Frameworks/Silverlight 2.0.shfbproj
  src/Docs/Frameworks/Silverlight 3.0.shfbproj
  src/Docs/Frameworks/Silverlight 4.0.shfbproj
Labels: refactoring, size/L

#4688 Removed NLog.Extended BuildMergedDocumentation from NLog.proj
  src/NLog.proj
Labels: size/S

#4689 Restore AppSettingLayoutRenderer since NLog.Extended is gone
  src/NLog/Internal/Abstractions/IConfigurationManager.cs
  src/NLog/Internal/ConfigurationManager.cs
  src/NLog/Internal/ConfigurationManager2.cs
  src/NLog/Internal/IConfigurationManager2.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/AppSettingLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/AppSettingTests.cs
Labels: breaking change, refactoring, size/L

#4690 ReflectionHelpers - Removed unused methods
  src/NLog/Internal/FactoryHelper.cs
  src/NLog/Internal/Reflection/ReflectionHelpers.cs
Labels: refactoring, size/M

#4691 Moved internal IIncludeContext into NLog.Config namespace
  src/NLog/Config/IIncludeContext.cs
Labels: refactoring, size/XS

#4692 Update README-developers.md about change in targets for NLog 5.0
  README-developers.md
Labels: documentation, size/XS
