Repository NLog/NLog, pull requests merged in 2021-02, with the labels that each got.

#4271 Testing appveyor.yml with Ubuntu
  appveyor.yml
  build.ps1
  run-tests.ps1
  src/NLog.sln
  src/NLog/Config/LoggingConfiguration.cs
  tests/NLog.UnitTests/Config/CultureInfoTests.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
  tests/NLog.UnitTests/Fluent/LogBuilderTests.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/EventPropertiesTests.cs
  tests/NLog.UnitTests/LayoutRenderers/IdentityTests.cs
  tests/NLog.UnitTests/LogManagerTests.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.UnitTests/NLogTestBase.cs
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
  tests/NLog.UnitTests/Targets/NetworkTargetTests.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
Labels: size/L

#4279 Extracted NLog.WindowsRegistry.Tests from NLog.UnitTests
  build.ps1
  run-tests.ps1
  src/NLog.PerformanceCounter/PerformanceCounterLayoutRenderer.cs
  src/NLog.WindowsRegistry/NLog.WindowsRegistry.csproj
  src/NLog.WindowsRegistry/Properties/AssemblyInfo.cs
  src/NLog.WindowsRegistry/RegistryLayoutRenderer.cs
  src/NLog.sln
  tests/NLog.WindowsRegistry.Tests/NLog.WindowsRegistry.Tests.csproj
  tests/NLog.WindowsRegistry.Tests/NLogTests.snk
  tests/NLog.WindowsRegistry.Tests/RegistryTests.cs
Labels: breaking change

#4282 WebServiceTargetTests - Isolate each OWIN by removing static properties
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
Labels: size/L, unstable test

#4284 NLog.UnitTests - Renamed LayoutRenderers subfolders to match the Nlog-project
  tests/NLog.UnitTests/LayoutRenderers/ApplicationEnvironment/AppDomainLayoutRendererTests.cs
  tests/NLog.UnitTests/LayoutRenderers/ApplicationEnvironment/AssemblyVersionTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/CallSiteFileNameLayoutTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/CallSiteLineNumberTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/CallSiteTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/StackTraceRendererTests.cs
  tests/NLog.UnitTests/LayoutRenderers/DateTime/DateTests.cs
  tests/NLog.UnitTests/LayoutRenderers/DateTime/LongDateTests.cs
  tests/NLog.UnitTests/LayoutRenderers/DateTime/NLogDirRendererTests.cs
  tests/NLog.UnitTests/LayoutRenderers/DateTime/ShortDateTests.cs
  tests/NLog.UnitTests/LayoutRenderers/DateTime/TicksLayoutRendererTests.cs
  tests/NLog.UnitTests/LayoutRenderers/DateTime/TimeTests.cs
Labels: refactoring, test

#4285 Removed QueryPerformanceCounterLayoutRenderer ${qpc}
  src/NLog/Internal/NativeMethods.cs
  src/NLog/LayoutRenderers/DateTime/QueryPerformanceCounterLayoutRenderer.cs
Labels: breaking change, size/L

#4295 NLogViewerTarget - Minor refactoring to remove use of internal properties
  src/NLog.sln
  src/NLog/Internal/INetworkInterfaceRetriever.cs
  src/NLog/Internal/NetworkInterfaceRetriever.cs
  src/NLog/Internal/NetworkSenders/NetworkSenderFactory.cs
  src/NLog/LayoutRenderers/Directories/ProcessDirLayoutRenderer.cs
  src/NLog/LayoutRenderers/Machine/HostNameLayoutRenderer.cs
  src/NLog/LayoutRenderers/Machine/LocalIpAddressLayoutRenderer.cs
  src/NLog/Targets/NLogViewerTarget.cs
  tests/NLog.UnitTests/LayoutRenderers/Directories/ProcessDirTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Machine/EnvironmentTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Machine/LocalIpAddressLayoutRendererTests.cs
  tests/NLog.UnitTests/RegressionTests.cs
  tests/NLog.UnitTests/Targets/NetworkTargetTests.cs
Labels: refactoring

#4296 WebServiceTarget - Returned back to its place for convenience
  build.ps1
  run-tests.ps1
  src/NLog.WebRequest/NLog.WebRequest.csproj
  src/NLog.WebRequest/Properties/AssemblyInfo.cs
  src/NLog.sln
  src/NLog/Targets/WebServiceProtocol.cs
  src/NLog/Targets/WebServiceProxyType.cs
  src/NLog/Targets/WebServiceTarget.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
  tests/NLog.WebRequest.Tests/NLog.WebRequest.Tests.csproj
  tests/NLog.WebRequest.Tests/NLogTests.snk
Labels: refactoring

#4298 MailTarget - Returned back to its place for convenience
  build.ps1
  run-tests.ps1
  src/NLog.sln
  src/NLog/Internal/ISmtpClient.cs
  src/NLog/Internal/MySmtpClient.cs
  src/NLog/NLog.csproj
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/SmtpAuthenticationMode.cs
  tests/NLog.SmtpClient.Tests/App.config
  tests/NLog.SmtpClient.Tests/NLog.SmtpClient.Tests.csproj
  tests/NLog.SmtpClient.Tests/NLogTests.snk
  tests/NLog.UnitTests/Targets/MailTargetTests.cs
Labels: refactoring

#4300 LoggingConfigurationParser - Added support for using assembly-name in type-name
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/Factory.cs
  src/NLog/Config/IFactory.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/MethodFactory.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/Targets/MailTargetTests.cs
Labels: feature, nlog-configuration, size/L

#4273 Handle Breaking change with string.IndexOf(string) in .NET 5
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/LayoutRenderers/AppSettingLayoutRenderer2.cs
  src/NLog/LayoutRenderers/RegistryLayoutRenderer.cs
  src/NLog/Targets/EventLogTarget.cs
Labels: enhancement, platform support, size/S

#4301 Update docs, remove out dated "ArrayList"
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/MemoryTarget.cs
Labels: documentation, size/XS

#4303 Merge branch 'master' 4.7.8 into 'dev'
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/AppSettingLayoutRenderer2.cs
  src/NLog/Targets/EventLogTarget.cs
Labels: size/S

#4251 When Condition Filters should recognize LogLevel-Type
  src/NLog/Conditions/Expressions/ConditionExceptionExpression.cs
  src/NLog/Conditions/Expressions/ConditionRelationalExpression.cs
  src/NLog/Conditions/Parsing/ConditionParser.cs
  tests/NLog.UnitTests/Filters/ConditionBasedFilterTests.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
Labels: enhancement, needs documentation on wiki, nlog-configuration, size/L

#4308 LoggingConfigurationParser - Added support for using assembly-name in type-name (comma delimiter)
  src/NLog/Config/Factory.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/MethodFactory.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
Labels: feature, needs documentation on wiki, nlog-configuration, size/M

#4311 Add 'testhost' as a valid process name in unit test
  tests/NLog.UnitTests/LayoutRenderers/Processes/ProcessNameLayoutRendererTests.cs
Labels: size/XS

#4312 Fix AsyncTaskTarget retry timings
  src/NLog/Targets/AsyncTaskTarget.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: bug, size/M

#4313 Make TargetWithContextNdcSerializeTest more stable
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
Labels: size/XS, test, unstable test

#4316 Fix TrimDirectorySeparators to handle root-path on Windows and Linux
  src/NLog/Internal/PathHelpers.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
Labels: bug, nlog-configuration, size/S

#4305 Release 4.7.8
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: size/S

#4320 Merge NLog 4.7.8 to dev
  CHANGELOG.md
  build.ps1
  src/NLog/Internal/Files/PathHelpers.cs
  src/NLog/NLog.csproj
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/MemoryTarget.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
Labels: size/M

#4321 LogFactory.Setup with RegisterSingletonService
  src/NLog/Config/ServiceRepositoryInternal.cs
  src/NLog/Config/ServiceRepositoryUpdateEventArgs.cs
  src/NLog/LogFactory.cs
  src/NLog/SetupExtensionsBuilderExtensions.cs
  tests/NLog.UnitTests/Config/LogFactorySetupTests.cs
  tests/NLog.UnitTests/Config/ServiceRepositoryTests.cs
Labels: feature, needs documentation on wiki, size/L

#4248 Fix NetworkTargetConnectionsOverflowAction to match normal OverflowAction-values
  src/NLog/Targets/NetworkTarget.cs
  src/NLog/Targets/NetworkTargetConnectionsOverflowAction.cs
Labels: breaking change, size/S

#4322 Removed NLog.config-package from build
  Test-XmlFile.ps1
  build.ps1
  src/InstallNLogConfig/InstallNLogConfig.mono2.csproj
  src/InstallNLogConfig/InstallNLogConfig.netfx20.csproj
  src/InstallNLogConfig/InstallNLogConfig.netfx35.csproj
  src/InstallNLogConfig/InstallNLogConfig.netfx40.csproj
  src/InstallNLogConfig/InstallNLogConfig.netfx45.csproj
  src/InstallNLogConfig/Program.cs
  src/InstallNLogConfig/Properties/AssemblyInfo.cs
  src/InstallNLogConfig/app.config
  src/NLog.proj
  src/NuGet/NLog.Config/NLog.Config.nuspec
  src/NuGet/NLog.Config/content/NLog.config
  src/NuGet/NLog.Config/tools/Install.ps1
  src/NuGet/NLog.Snippets/NLog.Snippets.nuspec
  src/NuGet/NLog.Snippets/content/empty.txt
  src/NuGet/NLog.Snippets/tools/install.ps1
  src/NuGet/NLog.Snippets/tools/uninstall.ps1
  src/SmartDeviceTestRun.testrunConfig
  src/VSIntegration/ItemTemplates/CSharpConsoleNLogConfig.zip
  src/VSIntegration/ItemTemplates/CSharpEmptyNLogConfig.zip
  src/VSIntegration/ItemTemplates/CSharpFileNLogConfig.zip
  src/VSIntegration/ItemTemplates/CSharpLogReceiverNLogConfig.zip
  src/VSIntegration/ItemTemplates/CSharpNLogViewerNLogConfig.zip
  src/VSIntegration/ItemTemplates/VisualBasicConsoleNLogConfig.zip
  src/VSIntegration/ItemTemplates/VisualBasicEmptyNLogConfig.zip
  src/VSIntegration/ItemTemplates/VisualBasicFileNLogConfig.zip
  src/VSIntegration/ItemTemplates/VisualBasicLogReceiverNLogConfig.zip
  src/VSIntegration/ItemTemplates/VisualBasicNLogViewerNLogConfig.zip
  src/VSIntegration/ItemTemplates/WebCSharpConsoleNLogConfig.zip
  src/VSIntegration/ItemTemplates/WebCSharpEmptyNLogConfig.zip
  src/VSIntegration/ItemTemplates/WebCSharpFileNLogConfig.zip
  src/VSIntegration/ItemTemplates/WebCSharpLogReceiverNLogConfig.zip
  src/VSIntegration/ItemTemplates/WebCSharpNLogViewerNLogConfig.zip
  src/VSIntegration/ItemTemplates/WebVisualBasicConsoleNLogConfig.zip
  src/VSIntegration/ItemTemplates/WebVisualBasicEmptyNLogConfig.zip
  src/VSIntegration/ItemTemplates/WebVisualBasicFileNLogConfig.zip
  src/VSIntegration/ItemTemplates/WebVisualBasicLogReceiverNLogConfig.zip
  src/VSIntegration/ItemTemplates/WebVisualBasicNLogViewerNLogConfig.zip
  src/VSIntegration/ItemTemplatesGenerator/ConsoleNLogConfig/MyTemplate.vstemplate
  src/VSIntegration/ItemTemplatesGenerator/ConsoleNLogConfig/NLog.config
  src/VSIntegration/ItemTemplatesGenerator/ConsoleNLogConfig/__TemplateIcon.ico
  src/VSIntegration/ItemTemplatesGenerator/EmptyNLogConfig/MyTemplate.vstemplate
  src/VSIntegration/ItemTemplatesGenerator/EmptyNLogConfig/NLog.config
  src/VSIntegration/ItemTemplatesGenerator/EmptyNLogConfig/__TemplateIcon.ico
  src/VSIntegration/ItemTemplatesGenerator/FileNLogConfig/MyTemplate.vstemplate
  src/VSIntegration/ItemTemplatesGenerator/FileNLogConfig/NLog.config
  src/VSIntegration/ItemTemplatesGenerator/FileNLogConfig/__TemplateIcon.ico
  src/VSIntegration/ItemTemplatesGenerator/LogReceiverNLogConfig/MyTemplate.vstemplate
  src/VSIntegration/ItemTemplatesGenerator/LogReceiverNLogConfig/NLog.config
  src/VSIntegration/ItemTemplatesGenerator/LogReceiverNLogConfig/__TemplateIcon.ico
  src/VSIntegration/ItemTemplatesGenerator/NLogViewerNLogConfig/MyTemplate.vstemplate
  src/VSIntegration/ItemTemplatesGenerator/NLogViewerNLogConfig/NLog.config
  src/VSIntegration/ItemTemplatesGenerator/NLogViewerNLogConfig/__TemplateIcon.ico
  src/VSIntegration/ItemTemplatesGenerator/generate_variants.pl
  src/VSIntegration/Snippets/CSharpLogger.snippet
  src/VSIntegration/Snippets/VBLogger.snippet
  src/VSIntegration/Snippets/VJSharpLogger.snippet
  src/publisher_policy.config.template
Labels: breaking change, build-config

#4326 Make it possible to register a own FuncLayoutRenderer
  src/NLog/LayoutRenderers/FuncLayoutRenderer.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/FuncLayoutRendererTests.cs
Labels: enhancement, size/L

#4327 Renamed NLogResolveException to NLogDependencyResolveException
  src/NLog.sln
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/NLogDependencyResolveException.cs
  src/NLog/Config/ServiceRepositoryExtensions.cs
  src/NLog/Config/ServiceRepositoryInternal.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  tests/NLog.UnitTests/Config/ServiceRepositoryTests.cs
  tests/NLog.UnitTests/GetLoggerTests.cs
Labels: refactoring, size/M

#4328 Fail fast on AppVeyor
  appveyor.yml
Labels: build-config, size/XS

#4329 Move to PackageIcon and PackageLicenseExpression for NuGet packages
  src/NLog.MSMQ/NLog.MSMQ.csproj
  src/NLog.OutputDebugString/NLog.OutputDebugString.csproj
  src/NLog.PerformanceCounter/NLog.PerformanceCounter.csproj
  src/NLog.Wcf/NLog.Wcf.csproj
  src/NLog.WindowsEventLog/NLog.WindowsEventLog.csproj
  src/NLog.WindowsIdentity/NLog.WindowsIdentity.csproj
  src/NLog.WindowsRegistry/NLog.WindowsRegistry.csproj
  src/NLog/NLog.csproj
Labels: build-config, size/L

#4332 Fail fast on AppVeyor #2
  appveyor.yml
Labels: build-config, size/XS

#4330 Remove Travis integration
  .travis.yml
  README.md
  howto-build-your-fork.md
  packages-and-status.md
  src/NLog.sln
Labels: build-config, size/M

#4331 Move types in the .Internal namespace to internal & move IUsesStackTrace to NLog.Config namespace
  src/NLog/Config/IUsesStackTrace.cs
  src/NLog/Internal/Abstractions/IAppDomain.cs
  src/NLog/Internal/Abstractions/IConfigurationManager.cs
  src/NLog/Internal/ConfigurationManager.cs
  src/NLog/Internal/StreamHelpers.cs
  src/NLog/Internal/Strings/StringHelpers.cs
  src/NLog/Internal/XmlHelper.cs
  tests/NLog.UnitTests/ApiTests.cs
Labels: breaking change, size/M

#4324 Visual studio 2019 on AppVeyor
  appveyor.yml
  tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs
Labels: build-config, size/S

#4333 Improvements in docs and added code annotation attributes
  src/NLog/Config/AppDomainFixedOutputAttribute.cs
  src/NLog/Config/ServiceRepositoryExtensions.cs
  src/NLog/Internal/Abstractions/IRawValue.cs
  src/NLog/Internal/Abstractions/IStringValueRenderer.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/LogFactory.cs
Labels: documentation, size/S

#4334 LoggingConfiguration - FindTargetByName with better WrapperTarget handling
  src/NLog/Config/LoggingConfiguration.cs
  tests/NLog.UnitTests/Config/TargetConfigurationTests.cs
Labels: enhancement, size/S
