Repository NLog/NLog, pull requests merged in 2021-03, with the labels that each got.

#4336 MailTarget - Returned back to its place for convenience (cleanup)
  src/NLog.SmtpClient/NLog.SmtpClient.csproj
  src/NLog.SmtpClient/Properties/AssemblyInfo.cs
Labels: refactoring, size/L

#4337 JsonLayout - Avoid constant string-escape of JsonAttribute Name-property
  src/NLog/Layouts/JsonAttribute.cs
  src/NLog/Layouts/JsonLayout.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
Labels: json / json-layout, performance, size/M

#4344 ScopeContextNestedStatesLayoutRenderer - Support Format with FormatAsJson
  src/NLog/Contexts/ScopeContext.cs
  src/NLog/LayoutRenderers/Contexts/ScopeContextNestedStatesLayoutRenderer.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/Targets/NLogViewerTarget.cs
  tests/NLog.UnitTests/Contexts/ScopeContextTest.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/ScopeNestedTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
Labels: feature, needs documentation on wiki, size/L

#4306 Typed Layout for easy conversion from Layout to actual value
  src/NLog/Config/PropertyTypeConverter.cs
  src/NLog/Internal/Reflection/PropertyHelper.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/SimpleLayout.cs
  src/NLog/Layouts/Typed/Layout.cs
  src/NLog/Layouts/Typed/LayoutTypedExtensions.cs
  src/NLog/Targets/EventLogTarget.cs
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/WebServiceTarget.cs
  tests/NLog.UnitTests/Layouts/LayoutTypedTests.cs
  tests/NLog.UnitTests/Targets/EventLogTargetTests.cs
  tests/NLog.UnitTests/Targets/TargetTests.cs
  tools/MakeNLogXSD/XsdFileGenerator.cs
Labels: feature, size/XXL

#4349 Fix TrimDirectorySeparators to skip Linux-root-path since off limits
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Internal/PathHelpers.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
Labels: bug, size/S

#4352 Fixed FileTarget archive cleanup when using short filename
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDynamicSequence.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: bug, file-archiving, file-target, size/XS

#4355 Fix sonar cube warning about not using value in property-setter
  src/NLog/Filters/WhenRepeatedFilter.cs
  src/NLog/Internal/ObjectPools/ReusableObjectCreator.cs
  src/NLog/Targets/Target.cs
Labels: refactoring, size/S

#4353 FileTarget improved archive cleanup at startup for same folder archive
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: bug, file-archiving, file-target, size/M

#4358 Merge NLog 4.7.9 to dev
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Internal/Files/PathHelpers.cs
  src/NLog/LayoutRenderers/FuncLayoutRenderer.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/Layouts/JSON/JsonAttribute.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDynamicSequence.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
  tests/NLog.UnitTests/LayoutRenderers/FuncLayoutRendererTests.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: size/L

#4361 NdlcItemSeparator + NdcItemSeparator revert breaking change
  src/NLog/LayoutRenderers/Contexts/ScopeContextNestedStatesLayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/Targets/NLogViewerTarget.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/ScopeNestedTests.cs
Labels: breaking change (but never released as RTM), size/S

#4362 SimpleLayout - Faster parsing of simple values and reduced allocation
  src/NLog/Internal/Reflection/ObjectGraphScanner.cs
  src/NLog/Layouts/LayoutParser.cs
  src/NLog/Layouts/SimpleLayout.cs
  src/NLog/Layouts/Typed/Layout.cs
  tests/NLog.UnitTests/Layouts/LayoutTypedTests.cs
Labels: performance, size/L

#4365 LiteralLayoutRenderer - Marked Text as DefaultParameter and fixed parser
  src/NLog/LayoutRenderers/LiteralLayoutRenderer.cs
  src/NLog/Layouts/LayoutParser.cs
  tests/NLog.UnitTests/LayoutRenderers/DateTime/DateTests.cs
  tests/NLog.UnitTests/LayoutRenderers/LiteralTests.cs
Labels: enhancement, size/L

#4366 GlobalDiagnosticsContext - GDC - OrdinalIgnoreCase
  src/NLog/Config/MethodFactory.cs
  src/NLog/Contexts/GlobalDiagnosticsContext.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/GDCTests.cs
Labels: breaking behavior change, context, needs documentation on wiki, size/S

#4367 DateLayoutRenderer - Detect invalid configuration of Format-property
  src/NLog/Layouts/LayoutParser.cs
  tests/NLog.UnitTests/LayoutRenderers/DateTime/DateTests.cs
Labels: enhancement, nlog-configuration, size/M

#4368 Fixed simple code warnings reported by Sonar
  src/NLog.Wcf/LogReceiverService/WcfLogReceiverClient.cs
  src/NLog/Attributes/LogLevelTypeConverter.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Internal/AppDomains/FakeAppDomain.cs
  src/NLog/Internal/UrlHelper.cs
  src/NLog/LayoutRenderers/Wrappers/String transformations/ReplaceLayoutRendererWrapper.cs
  src/NLog/Targets/LineEndingMode.cs
  tests/PackageLoaderTestAssembly/NLogPackageLoaders.cs
  tests/SampleExtensions/FooLayout.cs
  tests/SampleExtensions/FooLayoutRenderer.cs
  tests/SampleExtensions/WhenFooFilter.cs
Labels: refactoring, size/L

#4371 Fixed simple code warnings reported by Sonar
  src/NLog/Internal/NetworkSenders/SslSocketProxy.cs
  src/NLog/LogFactory.cs
  src/NLog/Targets/NetworkTarget.cs
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
  tests/NLog.UnitTests/Internal/NetworkSenders/TcpNetworkSenderTests.cs
Labels: refactoring, size/L

#4372 Fixed simple code warnings reported by Sonar
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/FileAppenders/IFileAppenderCache.cs
  src/NLog/Internal/StreamHelpers.cs
  src/NLog/LayoutRenderers/Wrappers/String transformations/ReplaceNewLinesLayoutRendererWrapper.cs
  src/NLog/LogLevel.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Internal/FileAppenders/FileAppenderCacheTests.cs
Labels: refactoring, size/M

#4369 LoggingConfigurationParser - Recognize LoggingRule.DefaultFilterAction
  src/NLog/Config/LoggingConfigurationParser.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
Labels: enhancement, nlog-configuration, size/M

#4375 Renamed setting from defaultFilterAction to filterDefaultAction
  src/NLog/Config/LoggingConfigurationParser.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
Labels: enhancement, size/M

#4376 Version 4.7.9
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: size/M, version

#4377 Merge NLog 4.7.9 to dev
  CHANGELOG.md
  build.ps1
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/NLog.csproj
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
Labels: size/M

#4378 LoggingRule - Marked DefaultFilterResult as obsolete, and replaced by FilterDefaultAction
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/LoggingRule.cs
  src/NLog/Filters/ConditionBasedFilter.cs
  src/NLog/LogFactory.cs
  src/NLog/LoggerImpl.cs
  src/NLog/Targets/Wrappers/FilteringTargetWrapper.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
Labels: breaking behavior change, size/S

#4379 ScopeContext - Extracted ScopeContextAsyncState into NLog.Internal
  src/NLog/Contexts/ScopeContext.cs
  src/NLog/Internal/ScopeContextAsyncState.cs
  src/NLog/Internal/ScopeContextPropertyEnumerator.cs
  src/NLog/LayoutRenderers/Contexts/ScopeContextNestedStatesLayoutRenderer.cs
Labels: refactoring, size/XXL

#4380 StackTraceLayoutRenderer - Include Separator when explicitly specified for raw Format
  src/NLog/LayoutRenderers/CallSite/StackTraceLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/StackTraceRendererTests.cs
Labels: enhancement, size/M

#4363 TargetWithLayout - Skip parsing of default Layout
  src/NLog/LayoutRenderers/LevelLayoutRenderer.cs
  src/NLog/Targets/TargetWithLayout.cs
  tests/NLog.UnitTests/Config/TargetConfigurationTests.cs
  tests/NLog.UnitTests/LayoutRenderers/LogLevelTests.cs
Labels: performance, size/L

#4381 LogManager.Setup() - Fix FilterDynamic to use FilterDefaultAction
  src/NLog/SetupLoadConfigurationExtensions.cs
Labels: refactoring, size/XS

#4382 Fixed simple code warnings reported by Sonar
  src/NLog.MSMQ/Targets/MessageQueueTarget.cs
  src/NLog/Common/AsyncHelpers.cs
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/NetworkSenders/NetworkSender.cs
  src/NLog/Layouts/LayoutParser.cs
Labels: refactoring, size/M

#4383 Fixed simple code warnings reported by Sonar
  src/NLog/Fluent/Log.cs
  src/NLog/Internal/Files/MultiFileWatcher.cs
  src/NLog/Internal/Reflection/ObjectHandleSerializer.cs
  src/NLog/Internal/TimeoutContinuation.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDynamicSequence.cs
  src/NLog/Targets/ZipArchiveFileCompressor.cs
Labels: refactoring, size/L

#4384 Fixed simple code warnings reported by Sonar
  src/NLog.WindowsIdentity/ImpersonatingTargetWrapper.cs
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/CountingSingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/SingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs
Labels: size/M

#4374 Enable deterministic build and SourceLink for all projects
  build.ps1
  src/NLog.MSMQ/NLog.MSMQ.csproj
  src/NLog.OutputDebugString/NLog.OutputDebugString.csproj
  src/NLog.PerformanceCounter/NLog.PerformanceCounter.csproj
  src/NLog.Wcf/NLog.Wcf.csproj
  src/NLog.WindowsEventLog/NLog.WindowsEventLog.csproj
  src/NLog.WindowsIdentity/NLog.WindowsIdentity.csproj
  src/NLog.WindowsRegistry/NLog.WindowsRegistry.csproj
Labels: size/M
