Repository NLog/NLog, pull requests merged in 2021-01, with the labels that each got.

#4222 StringBuilderExt ClearBuilder with better handling of low memory
  .travis.yml
  src/NLog.sln
  src/NLog/Conditions/ConditionLayoutExpression.cs
  src/NLog/Internal/ReusableAsyncLogEventList.cs
  src/NLog/Internal/ReusableBufferCreator.cs
  src/NLog/Internal/ReusableBuilderCreator.cs
  src/NLog/Internal/ReusableObjectCreator.cs
  src/NLog/Internal/ReusableStreamCreator.cs
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/Internal/StringBuilderPool.cs
  src/NLog/Targets/ConsoleTarget.cs
Labels: enhancement, size/M

#4221 Added a new ExcludeEmptyProperties to JsonLayout as to avoid GDC/MDC/MLDC properties with null or empty values from output (this time, against master)
  src/NLog/Layouts/JsonLayout.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
Labels: feature, json / json-layout, needs documentation on wiki, size/L

#4230 ScopeContext - Logger PushScopeProperties with covariance support
  src/NLog/Contexts/ScopeContext.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
  src/NLog/Logger.cs
  src/NLog/Targets/TargetWithContext.cs
  tests/ManuallyLoadedExtension/ManuallyLoadedExtension.csproj
  tests/NLog.UnitTests/Contexts/ScopeContextTest.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/ScopeNestedTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Processes/ProcessNameLayoutRendererTests.cs
  tests/NLogAutoLoadExtension/NLogAutoLoadExtension.csproj
  tests/PackageLoaderTestAssembly/PackageLoaderTestAssembly.csproj
  tests/SampleExtensions/SampleExtensions.csproj
Labels: feature, size/L

#4233 Throw NLogConfigurationException for unknown properties when parsing config
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/NLogXmlElement.cs
  tests/NLog.UnitTests/Config/ServiceRepositoryTests.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
  tests/NLog.UnitTests/LogFactoryTests.cs
Labels: breaking behavior change, size/L

#4236 Adding support for const NLog Config Variables
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationElementExtensions.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Internal/Reflection/PropertyHelper.cs
  src/NLog/LayoutRenderers/VariableLayoutRenderer.cs
  src/NLog/Layouts/LayoutParser.cs
  tests/NLog.UnitTests/Config/VariableTests.cs
  tests/NLog.UnitTests/Internal/Reflection/PropertyHelperTests.cs
  tests/NLog.UnitTests/LayoutRenderers/VariableLayoutRendererTests.cs
Labels: enhancement, size/L

#4237 Adding support for const NLog Config Variables (case-insensitive)
  src/NLog/Config/LoggingConfiguration.cs
  tests/NLog.UnitTests/LayoutRenderers/VariableLayoutRendererTests.cs
Labels: bug, never-released bug, size/XS

#4229 Skip lookup MainModule.FileName on Android platform to avoid crash
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
Labels: bug, platform support, size/L

#4245 JsonLayout - Unwind after invalid property value to avoid invalid Json
  src/NLog/Layouts/JsonLayout.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
Labels: bug, json / json-layout, size/M

#3048 FileTarget - ConcurrentWrites=false by default for better compatibility
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/ICreateFileParameters.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/ConcurrentFileTargetTests.cs
Labels: discussion, file-target, new default (breaking), size/S

#4226 Added ExceptionDataLayoutRenderer and unit tests for it.
  src/NLog/LayoutRenderers/ExceptionDataLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionDataLayoutRendererTests.cs
Labels: feature, size/L

#4249 JsonLayout - Changed EscapeForwardSlash default to false
  src/NLog/LayoutRenderers/Wrappers/Encodings/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/JSON/JsonAttribute.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/Targets/JsonSerializeOptions.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/Encodings/JsonEncodeTests.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: json / json-layout, new default (breaking), size/S

#4253 Target OptimizeBufferReuse marked as obsolete and now always returns true
  src/NLog.Wcf/Targets/LogReceiverWebServiceTarget.cs
  src/NLog/Common/LogEventInfoBuffer.cs
  src/NLog/Config/StackTraceUsage.cs
  src/NLog/Contexts/ScopeContext.cs
  src/NLog/Filters/WhenRepeatedFilter.cs
  src/NLog/Internal/ObjectPools/ReusableObjectCreator.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/ChainsawTarget.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/DebugTarget.cs
  src/NLog/Targets/DebuggerTarget.cs
  src/NLog/Targets/EventLogTarget.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/MemoryTarget.cs
  src/NLog/Targets/NLogViewerTarget.cs
  src/NLog/Targets/NetworkTarget.cs
  src/NLog/Targets/NullTarget.cs
  src/NLog/Targets/OutputDebugStringTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/TargetWithContext.cs
  src/NLog/Targets/TraceTarget.cs
  src/NLog/Targets/WebServiceTarget.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/FallbackGroupTarget.cs
  src/NLog/Targets/Wrappers/FilteringTargetWrapper.cs
  src/NLog/Targets/Wrappers/LimitingTargetWrapper.cs
  src/NLog/Targets/Wrappers/PostFilteringTargetWrapper.cs
  src/NLog/Targets/Wrappers/RandomizeGroupTarget.cs
  src/NLog/Targets/Wrappers/RepeatingTargetWrapper.cs
  src/NLog/Targets/Wrappers/RetryingTargetWrapper.cs
  src/NLog/Targets/Wrappers/RoundRobinGroupTarget.cs
  src/NLog/Targets/Wrappers/SplitGroupTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/PostFilteringTargetWrapperTests.cs
Labels: breaking behavior change, needs documentation on wiki, new default (breaking), size/L

#4255 LoggingConfigurationParser - Updated xml-docs for LoadConfig-mehod
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
Labels: refactoring, size/S

#4247 LogEventInfo - Lazy initialize SequenceID when requested
  src/NLog/LogEventInfo.cs
Labels: breaking behavior change, performance, size/S

#4257 Version 4.7.7
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: size/M, squash when passing, version

#4258 Merge NLog 4.7.7 to dev
  CHANGELOG.md
  build.ps1
  src/NLog/Conditions/Expressions/ConditionLayoutExpression.cs
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Internal/ObjectPools/ReusableAsyncLogEventList.cs
  src/NLog/Internal/ObjectPools/ReusableBufferCreator.cs
  src/NLog/Internal/ObjectPools/ReusableBuilderCreator.cs
  src/NLog/Internal/ObjectPools/ReusableObjectCreator.cs
  src/NLog/Internal/ObjectPools/ReusableStreamCreator.cs
  src/NLog/Internal/ObjectPools/StringBuilderPool.cs
  src/NLog/Internal/SingleCallContinuation.cs
  src/NLog/Internal/Strings/StringBuilderExt.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/LoggerImpl.cs
  src/NLog/NLog.csproj
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
Labels: merge when passing, size/XL

#4259 Merge NLog 4.7.7 to dev*
  CHANGELOG.md
  build.ps1
  src/NLog/Conditions/Expressions/ConditionLayoutExpression.cs
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Internal/ObjectPools/ReusableAsyncLogEventList.cs
  src/NLog/Internal/ObjectPools/ReusableBufferCreator.cs
  src/NLog/Internal/ObjectPools/ReusableBuilderCreator.cs
  src/NLog/Internal/ObjectPools/ReusableObjectCreator.cs
  src/NLog/Internal/ObjectPools/ReusableStreamCreator.cs
  src/NLog/Internal/ObjectPools/StringBuilderPool.cs
  src/NLog/Internal/SingleCallContinuation.cs
  src/NLog/Internal/Strings/StringBuilderExt.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/LoggerImpl.cs
  src/NLog/NLog.csproj
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
Labels: size/XL

#4262 WebServiceTarget - Removed unnecessary delegate-capture for EndGetResponse
  src/NLog/Targets/WebServiceTarget.cs
Labels: performance, size/L, webservice-target

#4261 FileTarget - Coalesce ArchiveAboveSize-property into ArchiveAboveSizeDisabled
  src/NLog/Targets/FileTarget.cs
Labels: enhancement, file-target, size/M

#4256 Target.ToString cached and used as InternalLogger parameter
  src/NLog.Wcf/Targets/LogReceiverWebServiceTarget.cs
  src/NLog/Common/InternalLogger.cs
  src/NLog/Internal/ExceptionHelper.cs
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/BaseMutexFileAppender.cs
  src/NLog/Internal/FileAppenders/CountingSingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/FileAppenders/MutexMultiProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/DatabaseTarget.cs
  src/NLog/Targets/DebuggerTarget.cs
  src/NLog/Targets/EventLogTarget.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/MailTarget.cs
  src/NLog/Targets/MethodCallTarget.cs
  src/NLog/Targets/MethodCallTargetBase.cs
  src/NLog/Targets/NetworkTarget.cs
  src/NLog/Targets/PerformanceCounterTarget.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/TargetWithContext.cs
  src/NLog/Targets/WebServiceTarget.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
  src/NLog/Targets/Wrappers/CompoundTargetBase.cs
  src/NLog/Targets/Wrappers/FallbackGroupTarget.cs
  src/NLog/Targets/Wrappers/LimitingTargetWrapper.cs
  src/NLog/Targets/Wrappers/PostFilteringTargetWrapper.cs
  src/NLog/Targets/Wrappers/RetryingTargetWrapper.cs
  src/NLog/Targets/Wrappers/SplitGroupTarget.cs
  src/NLog/Targets/Wrappers/WrapperTargetBase.cs
  tests/NLog.UnitTests/Targets/Wrappers/RetryingTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/SplitGroupTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/WrapperTargetBaseTests.cs
Labels: breaking behavior change, refactoring, size/XL

#4263 FileTarget - Removed WrappedFileTargetTests since not improving test-coverage
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: file-target, refactoring, size/L, test

#4264 Extracted NLog.MSMQ.Tests from NLog.UnitTests
  run-tests.ps1
  src/NLog.MSMQ/Properties/AssemblyInfo.cs
  src/NLog.sln
  tests/NLog.MSMQ.Tests/MessageQueueTargetTests.cs
  tests/NLog.MSMQ.Tests/NLog.MSMQ.Tests.csproj
  tests/NLog.MSMQ.Tests/NLogTests.snk
  tests/NLog.UnitTests/NLog.UnitTests.csproj
Labels: refactoring, test

#4265 Extracted NLog.Wcf.Tests from NLog.UnitTests
  run-tests.ps1
  src/NLog.Wcf/Properties/AssemblyInfo.cs
  src/NLog.sln
  tests/NLog.UnitTests/LayoutRenderers/IdentityTests.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.Wcf.Tests/LogReceiverForwardingServiceTests.cs
  tests/NLog.Wcf.Tests/LogReceiverServiceTests.cs
  tests/NLog.Wcf.Tests/LogReceiverWebServiceTargetTests.cs
  tests/NLog.Wcf.Tests/NLog.Wcf.Tests.csproj
  tests/NLog.Wcf.Tests/NLogTests.snk
Labels: refactoring, test

#4269 Trying to make RenderProcessTimeLayoutRenderer less unstable
  tests/NLog.UnitTests/LayoutRenderers/Processes/ProcessTimeLayoutRendererTests.cs
Labels: size/XS, test, unstable test
