Repository NLog/NLog, pull requests merged in 2022-06, with the labels that each got.

#4953 FileTarget - Zip compression should not truncate when zip-file already exists
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/ZipArchiveFileCompressor.cs
Labels: enhancement, file-target, size/M, file-archiving

#4956 FileTarget - Zip compression should not truncate when zip-file already exists (skip retry)
  src/NLog/Targets/FileTarget.cs
Labels: enhancement, file-target, size/XS, file-archiving

#4958 MakeNLogXSD - Improve xml-docs when summary contains cref
  tools/MakeNLogXSD/XsdFileGenerator.cs
Labels: size/S

#4939 Replaced item-name and symbol-name with type-alias
  src/NLog/Config/Factory.cs
  src/NLog/Config/NameBaseAttribute.cs
  src/NLog/LayoutRenderers/Attributes/LayoutRendererAttribute.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/Layouts/LayoutAttribute.cs
  src/NLog/SetupExtensionsBuilderExtensions.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/TargetAttribute.cs
  src/NLog/Time/TimeSourceAttribute.cs
Labels: documentation, size/M

#4959 Extract NLog extensions to their own repository
  build.ps1
  run-tests.ps1
  src/NLog.MSMQ/NLog.MSMQ.csproj
  src/NLog.MSMQ/Properties/AssemblyInfo.cs
  src/NLog.MSMQ/Targets/MessageQueueTarget.cs
  src/NLog.PerformanceCounter/NLog.PerformanceCounter.csproj
  src/NLog.PerformanceCounter/PerformanceCounterLayoutRenderer.cs
  src/NLog.PerformanceCounter/PerformanceCounterTarget.cs
  src/NLog.PerformanceCounter/Properties/AssemblyInfo.cs
  src/NLog.Wcf/LogEventInfoBuffer.cs
  src/NLog.Wcf/LogReceiverService/BaseLogReceiverForwardingService.cs
  src/NLog.Wcf/LogReceiverService/ILogReceiverOneWayClient.cs
  src/NLog.Wcf/LogReceiverService/ILogReceiverOneWayServer.cs
  src/NLog.Wcf/LogReceiverService/ILogReceiverServer.cs
  src/NLog.Wcf/LogReceiverService/ILogReceiverTwoWayClient.cs
  src/NLog.Wcf/LogReceiverService/IWcfLogReceiverClient.cs
  src/NLog.Wcf/LogReceiverService/LogReceiverForwardingService.cs
  src/NLog.Wcf/LogReceiverService/LogReceiverOneWayForwardingService.cs
  src/NLog.Wcf/LogReceiverService/LogReceiverServiceConfig.cs
  src/NLog.Wcf/LogReceiverService/NLogEvent.cs
  src/NLog.Wcf/LogReceiverService/NLogEvents.cs
  src/NLog.Wcf/LogReceiverService/StringCollection.cs
  src/NLog.Wcf/LogReceiverService/WcfLogReceiverClient.cs
  src/NLog.Wcf/LogReceiverService/WcfLogReceiverClientBase.cs
  src/NLog.Wcf/LogReceiverService/WcfLogReceiverOneWayClient.cs
  src/NLog.Wcf/LogReceiverService/WcfLogReceiverTwoWayClient.cs
  src/NLog.Wcf/NLog.Wcf.csproj
  src/NLog.Wcf/Properties/AssemblyInfo.cs
  src/NLog.Wcf/Targets/LogReceiverWebServiceTarget.cs
  src/NLog.WindowsIdentity/ImpersonatingTargetWrapper.cs
  src/NLog.WindowsIdentity/LogOnProviderType.cs
  src/NLog.WindowsIdentity/NLog.WindowsIdentity.csproj
  src/NLog.WindowsIdentity/NativeMethods.cs
  src/NLog.WindowsIdentity/Properties/AssemblyInfo.cs
  src/NLog.WindowsIdentity/SecurityImpersonationLevel.cs
  src/NLog.WindowsIdentity/SecurityLogOnType.cs
  src/NLog.WindowsIdentity/WindowsIdentityLayoutRenderer.cs
  src/NLog.proj
  src/NLog.sln
  tests/NLog.MSMQ.Tests/MessageQueueTargetTests.cs
  tests/NLog.MSMQ.Tests/NLog.MSMQ.Tests.csproj
  tests/NLog.MSMQ.Tests/NLogTests.snk
  tests/NLog.PerformanceCounter.Tests/NLog.PerformanceCounter.Tests.csproj
  tests/NLog.PerformanceCounter.Tests/NLogTests.snk
  tests/NLog.PerformanceCounter.Tests/PerformanceCounterLayoutRendererTests.cs
  tests/NLog.Wcf.Tests/LogReceiverForwardingServiceTests.cs
  tests/NLog.Wcf.Tests/LogReceiverServiceTests.cs
  tests/NLog.Wcf.Tests/LogReceiverWebServiceTargetTests.cs
  tests/NLog.Wcf.Tests/NLog.Wcf.Tests.csproj
  tests/NLog.Wcf.Tests/NLogTests.snk
  tests/NLog.WindowsIdentity.Tests/ImpersonatingTargetWrapperTests.cs
  tests/NLog.WindowsIdentity.Tests/NLog.WindowsIdentity.Tests.csproj
  tests/NLog.WindowsIdentity.Tests/NLogTests.snk
  tests/NLog.WindowsIdentity.Tests/WindowsIdentityTests.cs
Labels: build-config, size/XXL

#4960 FileTarget - First acquire file-handle to compress before creating zip-file (test)
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: test, size/M

#4961 JsonAttribute - Updated xml-docs for Encode-property
  src/NLog/LayoutRenderers/Wrappers/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/XmlEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/JSON/JsonAttribute.cs
  src/NLog/Layouts/XML/XmlAttribute.cs
  src/NLog/Layouts/XML/XmlElement.cs
Labels: documentation, refactoring, size/S

#4965 Max StackTraceUsage should be computed using bitwise OR
  src/NLog/Layouts/Layout.cs
Labels: bug, size/XS

#4966 Max StackTraceUsage should be computed using bitwise OR (test)
  src/NLog/LayoutRenderers/CallSite/CallSiteLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/CallSiteTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/StackTraceRendererTests.cs
Labels: bug, test, size/S

#4938 LoggingConfigurationParser should alert when LoggingRule filters are bad
  src/NLog/Config/LoggingConfigurationParser.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
  tests/NLog.UnitTests/Filters/WhenContainsTests.cs
Labels: enhancement, size/M

#4940 CompoundLayout with layout from config variable
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  tests/NLog.UnitTests/Layouts/CompoundLayoutTests.cs
Labels: enhancement, size/L

#4963 Fix typo in comment
  src/NLog/Common/AsyncHelpers.cs
  src/NLog/LayoutRenderers/Directories/BaseDirLayoutRenderer.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: size/S

#4941 Replaced netcoreapp2.1 with netcoreapp3.1 to fix obsolete test warnings
  run-tests.ps1
  tests/NLog.Database.Tests/NLog.Database.Tests.csproj
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.UnitTests/Properties/AssemblyInfo.cs
  tests/NLog.WindowsRegistry.Tests/NLog.WindowsRegistry.Tests.csproj
Labels: test, size/M

#4967 Release NLog 5.0.1
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version, size/S

#4969 Fixed link to NLog 5 release notes
  src/NLog/NLog.csproj
Labels: size/XS

#4970 Updated links to targets and layout-overview to use nlog-project.org/config
  README.md
Labels: size/XS

#4971 Added link to API reference
  README.md
Labels: size/XS

#4972 Added link to API reference
  README.md
Labels: size/XS

#4973 NLog 5.0.1 - ChangeLog
  CHANGELOG.md
Labels: size/S

#4976 AddRule: add overload for LoggingRule object
  src/NLog/Config/LoggingConfiguration.cs
  tests/NLog.UnitTests/Config/ConfigApiTests.cs
Labels: enhancement, size/S

#4981 AssemblyVersionLayoutRenderer - Support override of Default value
  src/NLog/LayoutRenderers/ApplicationEnvironment/AssemblyVersionLayoutRenderer.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/AssemblyVersionType.cs
  tests/NLog.UnitTests/LayoutRenderers/ApplicationEnvironment/AssemblyVersionTests.cs
Labels: enhancement, size/M

#4987 ConfigurationItemFactory - Include original type-alias when CreateInstance fails
  src/NLog/Config/Factory.cs
  src/NLog/Layouts/LayoutParser.cs
  tests/NLog.Database.Tests/NLog.Database.Tests.csproj
  tests/NLog.UnitTests/Config/ConfigurationItemFactoryTests.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.WindowsRegistry.Tests/NLog.WindowsRegistry.Tests.csproj
Labels: enhancement, size/M

#4988 Reformatting ChangeLog to help dependency update bots
  CHANGELOG.md
Labels: size/L

#4989 Reformatted ChangeLog to help dependency update bots
  CHANGELOG.md
Labels: size/L

#4990 Added Version 5.0-Preview 3 to ChangeLog
  CHANGELOG.md
Labels: size/S

#4947 Docs for preferring RenderLogEvent on Target
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/Typed/LayoutTypedExtensions.cs
Labels: documentation, size/XS
