Repository NLog/NLog, pull requests merged in 2022-05, with the labels that each got.

#4905 NLog.OutputDebugString - Added NetStandard2.0 target platform
  src/NLog.OutputDebugString/NLog.OutputDebugString.csproj
Labels: enhancement, size/XS

#4906 LogFactory GlobalThreshold setter with extra logging
  src/NLog/LogFactory.cs
Labels: enhancement, size/XS

#4919 PlatformDetector.IsMono is only for legacy .NET Framework
  src/NLog/Internal/MutexDetector.cs
  src/NLog/Internal/PlatformDetector.cs
  src/NLog/LogFactory.cs
  src/NLog/Targets/ConsoleTargetHelper.cs
  tests/NLog.UnitTests/Internal/PlatformDetectorTests.cs
Labels: size/M, platform support

#4912 Replaced question.md issue-template with contact_links to StackOverflow
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: size/M

#4920 Replaced question.md issue-template with contact_links (Fix config.yml)
  .github/ISSUE_TEMPLATE/config.yml
Labels: size/XS

#4884 dotnet list package --vulnerable --include-transitive
  run-tests.ps1
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.WindowsIdentity.Tests/NLog.WindowsIdentity.Tests.csproj
Labels: build-config, size/S

#4921 Replaced question.md issue-template with contact_links (fix bom)
  .github/ISSUE_TEMPLATE/config.yml
Labels: size/XS

#4922 NetworkTarget - Dual Mode IPv4 mapped addresses over IPv6
  src/NLog/Internal/NetworkSenders/SocketProxy.cs
  src/NLog/Internal/NetworkSenders/UdpNetworkSender.cs
Labels: network/NLogViewer-target, size/XS

#4924 ChainsawTarget - IncludeEventProperties = true since IncludeNLogData = false
  src/NLog/Targets/ChainsawTarget.cs
Labels: network/NLogViewer-target, size/XS

#4926 Improved documentation for SandCastle
  src/NLog/Config/AssemblyLoadingEventArgs.cs
  src/NLog/Config/NLogDependencyResolveException.cs
  src/NLog/Config/ServiceRepositoryUpdateEventArgs.cs
  src/NLog/Contexts/ScopeContext.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/NLogViewerTarget.cs
  src/NLog/Targets/TargetWithContext.cs
  src/NLog/Targets/Wrappers/LogEventDroppedEventArgs.cs
  src/NLog/Targets/Wrappers/LogEventQueueGrowEventArgs.cs
Labels: documentation, size/L

#4802 NLog 5.0 Ready for delivery
  CHANGELOG.md
  README.md
  build.ps1
  src/NLog.sln
  src/NLog/NLog.csproj
Labels: version, size/M

#4929 NLog 5.0 - ChangeLog
  CHANGELOG.md
Labels: size/M

#4932 Update SECURITY.md - NLog 5
  SECURITY.md
Labels: documentation, size/XS

#4933 Removed NLog.Windows.Forms examples as moved to their own project
  examples/targets/Configuration API/FormControl/Example.cs
  examples/targets/Configuration API/FormControl/Form1.Designer.cs
  examples/targets/Configuration API/FormControl/Form1.cs
  examples/targets/Configuration API/FormControl/Form1.resx
  examples/targets/Configuration API/FormControl/FormControl.csproj
  examples/targets/Configuration API/FormControl/FormControl.sln
  examples/targets/Configuration API/FormControl/Properties/AssemblyInfo.cs
  examples/targets/Configuration API/FormControl/Properties/Resources.Designer.cs
  examples/targets/Configuration API/FormControl/Properties/Resources.resx
  examples/targets/Configuration API/FormControl/Properties/Settings.Designer.cs
  examples/targets/Configuration API/FormControl/Properties/Settings.settings
  examples/targets/Configuration API/MessageBox/Simple/Example.cs
  examples/targets/Configuration API/MessageBox/Simple/MessageBox.csproj
  examples/targets/Configuration API/MessageBox/Simple/MessageBox.sln
  examples/targets/Configuration API/RichTextBox/RowColoring/Example.cs
  examples/targets/Configuration API/RichTextBox/RowColoring/Form1.Designer.cs
  examples/targets/Configuration API/RichTextBox/RowColoring/Form1.cs
  examples/targets/Configuration API/RichTextBox/RowColoring/Form1.resx
  examples/targets/Configuration API/RichTextBox/RowColoring/Properties/AssemblyInfo.cs
  examples/targets/Configuration API/RichTextBox/RowColoring/Properties/Resources.Designer.cs
  examples/targets/Configuration API/RichTextBox/RowColoring/Properties/Resources.resx
  examples/targets/Configuration API/RichTextBox/RowColoring/Properties/Settings.Designer.cs
  examples/targets/Configuration API/RichTextBox/RowColoring/Properties/Settings.settings
  examples/targets/Configuration API/RichTextBox/RowColoring/RichTextBox.RowColoring.csproj
  examples/targets/Configuration API/RichTextBox/RowColoring/RichTextBox.RowColoring.sln
  examples/targets/Configuration API/RichTextBox/Simple/Example.cs
  examples/targets/Configuration API/RichTextBox/Simple/Form1.Designer.cs
  examples/targets/Configuration API/RichTextBox/Simple/Form1.cs
  examples/targets/Configuration API/RichTextBox/Simple/Form1.resx
  examples/targets/Configuration API/RichTextBox/Simple/Properties/AssemblyInfo.cs
  examples/targets/Configuration API/RichTextBox/Simple/Properties/Resources.Designer.cs
  examples/targets/Configuration API/RichTextBox/Simple/Properties/Resources.resx
  examples/targets/Configuration API/RichTextBox/Simple/Properties/Settings.Designer.cs
  examples/targets/Configuration API/RichTextBox/Simple/Properties/Settings.settings
  examples/targets/Configuration API/RichTextBox/Simple/RichTextBox.csproj
  examples/targets/Configuration API/RichTextBox/Simple/RichTextBox.sln
  examples/targets/Configuration API/RichTextBox/WordColoring/Example.cs
  examples/targets/Configuration API/RichTextBox/WordColoring/Form1.Designer.cs
  examples/targets/Configuration API/RichTextBox/WordColoring/Form1.cs
  examples/targets/Configuration API/RichTextBox/WordColoring/Form1.resx
  examples/targets/Configuration API/RichTextBox/WordColoring/Properties/AssemblyInfo.cs
  examples/targets/Configuration API/RichTextBox/WordColoring/Properties/Resources.Designer.cs
  examples/targets/Configuration API/RichTextBox/WordColoring/Properties/Resources.resx
  examples/targets/Configuration API/RichTextBox/WordColoring/Properties/Settings.Designer.cs
  examples/targets/Configuration API/RichTextBox/WordColoring/Properties/Settings.settings
  examples/targets/Configuration API/RichTextBox/WordColoring/RichTextBox.WordColoring.csproj
  examples/targets/Configuration API/RichTextBox/WordColoring/RichTextBox.WordColoring.sln
  src/NLog.proj
  tools/BuildDocPages/BuildDocPages.csproj
  tools/BuildDocPages/BuildDocPages.sln
  tools/BuildDocPages/DocPageGenerator.cs
  tools/BuildDocPages/Program.cs
  tools/Stylesheets/style.css
  tools/Stylesheets/style.xsl
Labels: size/XXL

#4925 Updated SandCastle project to use packagereferences + added Readme
  src/Docs/.gitignore
  src/Docs/BuildDoc.cmd
  src/Docs/Docs.csproj
  src/Docs/NLog.shfbproj
  src/Docs/README.md
  src/Docs/dll_to_doc/App.config
  src/Docs/dll_to_doc/Program.cs
  src/Docs/dll_to_doc/dll_to_doc.csproj
  src/Docs/dll_to_doc/dll_to_doc.sln
  src/Docs/dll_to_doc/packages.config
Labels: documentation, size/L

#4934 SandCastle Docs should always use nuget-packages
  src/Docs/BuildDoc.cmd
  src/Docs/NLog.shfbproj
  src/Docs/README.md
  src/Docs/dll_to_doc/dll_to_doc.csproj
  src/Docs/dll_to_doc/packages.config
Labels: size/L

#4935 DLL to Docs - in csproj SDK
  src/Docs/BuildDoc.cmd
  src/Docs/dll_to_doc/App.config
  src/Docs/dll_to_doc/Place_dll_and_xml_here_for_SHFB.txt
  src/Docs/dll_to_doc/dll_to_doc.csproj
  src/Docs/dll_to_doc/dll_to_doc.sln
  src/Docs/dll_to_doc/packages.config
Labels: size/L

#4943 Include NLog.Database + NLog.WindowsIdentity in NLog.xsd
  src/NLog.proj
  tools/DumpApiXml/Program.cs
Labels: size/S

#4944 Mark LayoutWithLock as obsolete, since only temporary workaround
  src/NLog/Targets/Target.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: refactoring, size/XS

#4945 MakeNLogXSD - Improve xml-docs when summary contains cref
  src/NLog/Targets/NetworkTarget.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  tools/MakeNLogXSD/XsdFileGenerator.cs
Labels: documentation, size/S

#4950 FileTarget - First acquire file-handle to compress before creating zip-file
  src/NLog/Targets/ZipArchiveFileCompressor.cs
Labels: enhancement, file-target, size/XS, file-archiving

#4951 FileTarget - First acquire file-handle to compress before creating zip-file
  src/NLog/Targets/ZipArchiveFileCompressor.cs
Labels: enhancement, file-target, size/XS, file-archiving
