Repository NLog/NLog, pull requests merged in 2022-03, with the labels that each got.

#4819 Improve loading of nlog-config with .NET6 single file publish
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Internal/AppEnvironmentWrapper.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
Labels: enhancement, size/M

#4820 Improve loading of nlog-config with .NET6 single file publish
  src/NLog/Internal/Fakeables/AppEnvironmentWrapper.cs
Labels: enhancement, size/S

#4821 LogEventInfo - Optimize copy messageTemplateParameters by caching Count
  src/NLog/LogEventInfo.cs
Labels: performance, size/S

#4823 Improve InternalLogger output when testing candidate config file locations
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Internal/AssemblyHelpers.cs
Labels: enhancement, nlog-configuration, size/S

#4824 LogFactory - Avoid loading candidate NLog-config files for every Logger created
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
Labels: performance, nlog-configuration, breaking behavior change, size/M

#4825 LogFactory - Write to InternalLogger when NLog configuration has not been loaded
  src/NLog/LogFactory.cs
Labels: enhancement, nlog-configuration, size/XS

#4826 LogFactory - Write to InternalLogger when NLog configuration has not been loaded
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/LogFactory.cs
Labels: enhancement, nlog-configuration, size/XS

#4829 Refactor LogFactory by extracting building of TargetWithFilterChain-array
  src/NLog/Internal/TargetWithFilterChain.cs
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
Labels: refactoring, size/L

#4830 Refactor AsyncTargetWrapper to reduce code complexity
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: refactoring, size/M

#4831 Make the unit-test SwallowTest more stable
  tests/NLog.UnitTests/LoggerTests.cs
Labels: test, size/S

#4835 Fixed missing initialization of layout-parameters for ConditionMethodExpression
  src/NLog/Conditions/Expressions/ConditionMethodExpression.cs
  tests/NLog.UnitTests/Filters/ConditionBasedFilterTests.cs
Labels: bug, size/XS

#4836 Fixed missing initialization of layout-parameters for ConditionMethodExpression
  src/NLog/Conditions/ConditionMethodExpression.cs
  tests/NLog.UnitTests/Filters/ConditionBasedFilterTests.cs
Labels: bug, size/S

#4838 Added required null checks
  src/NLog/Config/ServiceRepositoryInternal.cs
  src/NLog/Internal/Collections/PropertiesDictionary.cs
  src/NLog/Internal/FormatHelper.cs
Labels: size/XS

#4837 MethodFactory - Only include static methods when scanning types
  src/NLog/Conditions/Expressions/ConditionMethodExpression.cs
  src/NLog/Config/MethodFactory.cs
Labels: enhancement, size/XS

#4840 Changed GlobalThresholdTest to use isolated LogFactory (Not skipped)
  tests/NLog.UnitTests/LogManagerTests.cs
Labels: test, size/S

#4842 LogFactory - Renamed _logsEnabled to _supendLoggingCounter
  src/NLog/LogFactory.cs
Labels: refactoring, size/S

#4843 Loading candidate config files with better support for nlog.dll.nlog
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Internal/AppEnvironmentWrapper.cs
  src/NLog/Internal/AssemblyHelpers.cs
  src/NLog/LayoutRenderers/Directories/NLogDirLayoutRenderer.cs
Labels: enhancement, nlog-configuration, size/M

#4850 Revert changes to GetAssemblyFileLocation and simplify loading of nlog.dll.nlog
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Internal/AppEnvironmentWrapper.cs
  src/NLog/Internal/AssemblyHelpers.cs
  src/NLog/LayoutRenderers/Directories/NLogDirLayoutRenderer.cs
Labels: refactoring, size/L

#4849 LogFactory - Updated XML docs after rename _logsEnabled to _supendLoggingCounter
  src/NLog/Config/ServiceRepositoryInternal.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
Labels: refactoring, size/M

#4851 Reverted AppDomain BaseDirectory as fallback when loading nlog.dll.nlog
  src/NLog/Common/InternalLogger.cs
  src/NLog/Config/LoggingConfigurationFileLoader.cs
Labels: refactoring, size/S

#4853 LogFactory Setup LoadConfiguration should skip refresh Loggers when config unchanged
  src/NLog/SetupBuilderExtensions.cs
Labels: enhancement, size/XS

#4852 Release 4.7.15
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version, size/S

#4854 FilteringTargetWrapper - Skip calling WrappedTarget when no events
  src/NLog/Targets/Wrappers/FilteringTargetWrapper.cs
  src/NLog/Targets/Wrappers/PostFilteringTargetWrapper.cs
Labels: refactoring, size/S

#4855 LoggingConfigurationParser - Improve logging when auto-loading Assembly from type-name
  src/NLog/Config/LoggingConfigurationParser.cs
Labels: enhancement, size/XS

#4858 BufferingTargetWrapper - Changed BufferSize + FlushTimeout to typed Layout
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
Labels: enhancement, breaking change, size/M

#4859 RetryingTargetWrapper - Changed RetryCount and RetryDelay to typed Layout
  src/NLog/Targets/Wrappers/RetryingTargetWrapper.cs
Labels: enhancement, breaking change, size/S

#4857 LimitingTargetWrapper - Changed MessageLimit + Interval to typed Layout
  src/NLog/Targets/Wrappers/LimitingTargetWrapper.cs
Labels: enhancement, breaking change, size/M
