Repository NLog/NLog, pull requests merged in 2023-03, with the labels that each got.

#5168 MethodCallTarget - Compile Method Invoke as Expression Trees
  src/NLog/Targets/MethodCallTarget.cs
  tests/NLog.UnitTests/Targets/MethodCallTests.cs
Labels: performance, size/L

#5169 Remove TODO as FakeAppDomain is obsolete, and also automatic assembly loading
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Internal/AppDomains/FakeAppDomain.cs
Labels: refactoring, size/XS

#5175 ScopeContext - Replace rescursive lookup with enumeration
  src/NLog/Contexts/ScopeContext.cs
  src/NLog/Internal/ScopeContextAsyncState.cs
  src/NLog/Internal/ScopeContextPropertyEnumerator.cs
  src/NLog/LayoutRenderers/Contexts/ScopeContextIndentLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/ScopeContextNestedStatesLayoutRenderer.cs
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.UnitTests/Contexts/ScopeContextTest.cs
Labels: enhancement, size/XL

#5177 MailTarget - Added support for email message headers
  src/NLog/Targets/MailTarget.cs
  tests/NLog.UnitTests/Targets/MailTargetTests.cs
Labels: feature, mail-target, size/M

#5178 LogLevelTests - Fixed code smells for assert values
  tests/NLog.UnitTests/LogLevelTests.cs
Labels: unit-tests, refactoring, size/L

#5174 Add layout support for FinalMinLevel
  src/NLog/Config/DynamicLogLevelFilter.cs
  src/NLog/Config/DynamicRangeLevelFilter.cs
  src/NLog/Config/ILoggingRuleLevelFilter.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/LoggingRule.cs
  src/NLog/Config/LoggingRuleLevelFilter.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
Labels: enhancement, size/L

#5181 Faster refresh of TargetWithFilterChain from LoggingRule
  src/NLog/Internal/TargetWithFilterChain.cs
Labels: performance, size/S

#5182 LoggingRule - Improve error logging when failing to parse LogLevel from Layout
  src/NLog/Config/DynamicLogLevelFilter.cs
  src/NLog/Config/DynamicRangeLevelFilter.cs
Labels: refactoring, size/XS

#5179 Version 5.1.3
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version, size/S

#5185 Xamarin PreserveAttribute with default values
  src/NLog/Internal/Xamarin/PreserveAttribute.cs
  src/NLog/Properties/AssemblyInfo.cs
Labels: platform support
