Repository NLog/NLog, pull requests merged in 2023-06, with the labels that each got.

#5241 Update CHANGELOG.md
  CHANGELOG.md
  src/NLog/MappedDiagnosticsLogicalContext.cs
Labels: size/S

#5240 Fixed Sonar code smells about missing assert in unit-test
  tests/NLog.UnitTests/Common/InternalLoggerTests.cs
  tests/NLog.UnitTests/Conditions/ConditionParserTests.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/Config/LogFactorySetupTests.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
  tests/NLog.UnitTests/Config/TargetConfigurationTests.cs
  tests/NLog.UnitTests/GetLoggerTests.cs
  tests/NLog.UnitTests/Internal/FileAppenders/FileAppenderCacheTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Directories/BaseDirTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
  tests/NLog.UnitTests/LogFactoryTests.cs
  tests/NLog.UnitTests/MessageTemplates/ParserTests.cs
  tests/NLog.UnitTests/RegressionTests.cs
  tests/NLog.UnitTests/Targets/ColoredConsoleTargetTests.cs
  tests/NLog.UnitTests/Targets/ConsoleTargetTests.cs
  tests/NLog.UnitTests/Targets/DebugSystemTargetTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
  tests/NLog.UnitTests/Targets/MailTargetTests.cs
  tests/NLog.UnitTests/Targets/TargetTests.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
Labels: unit-tests, refactoring, size/XL

#5248 WrapperTarget - Derive Name from wrappedTarget
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
  src/NLog/Targets/Wrappers/FilteringTargetWrapper.cs
  src/NLog/Targets/Wrappers/GroupByTargetWrapper.cs
  src/NLog/Targets/Wrappers/LimitingTargetWrapper.cs
  src/NLog/Targets/Wrappers/PostFilteringTargetWrapper.cs
  src/NLog/Targets/Wrappers/RetryingTargetWrapper.cs
Labels: size/S

#5249 ConfigurationReloaded replaced by ConfigurationChanged but check ActivatedConfiguration
  src/NLog/Config/LoggingConfigurationReloadedEventArgs.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
Labels: refactoring, size/S

#5253 ConfigurationItemFactory - Resolve array configuration items from factory
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/Factory.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/ServiceRepositoryInternal.cs
  src/NLog/Targets/Wrappers/GroupByTargetWrapper.cs
Labels: enhancement, size/M

#5254 ConfigurationItemFactory - Include ConditionExpression in registration
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Config/AssemblyExtensionTypes.tt
  src/NLog/Internal/Reflection/PropertyHelper.cs
  src/NLog/Internal/TargetWithFilterChain.cs
Labels: enhancement, size/M

#5255 LogFactory - Obsoleted GetLogger should not throw exceptions when invalid logger-type
  src/NLog/LogFactory.cs
Labels: enhancement, size/S

#5257 ConfigurationItemFactory - Skip assembly-loading should also check prefix-option
  src/NLog/Config/AssemblyExtensionLoader.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Internal/ExceptionHelper.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/Internal/ExceptionHelperTests.cs
Labels: bug, size/L

#5259 Added PublishReadyToRun to TestTrimPublish
  tests/TestTrimPublish/TestTrimPublish.csproj
Labels: size/XS

#5263 AssemblyExtensionLoader - Logging assembly-prefix when auto-loading
  src/NLog/Common/InternalLogger.cs
  src/NLog/Config/AssemblyExtensionLoader.cs
Labels: size/M

#5264 StringBuilderExt - AppendInvariant is safe
  src/NLog/Internal/Strings/StringBuilderExt.cs
Labels: size/XS

#5266 Remove irrelevant StructuredMessageTemplateAttribute
  src/NLog/Abstractions/ILogger.cs
Labels: size/XS

#5267 Updated ILogger obsolete message
  src/NLog/Abstractions/ILogger.cs
  src/NLog/Abstractions/ILoggerBase.cs
  src/NLog/Logger-V1Compat.cs
Labels: size/M

#5269 PropertyHelper - TryGetEnumValue should throw when invalid string-value
  src/NLog/Internal/Reflection/PropertyHelper.cs
Labels: enhancement, size/XS
