Repository NLog/NLog, pull requests merged in 2023-07, with the labels that each got.

#5268 ConfigurationItemFactory - Include ConditionMethods in registration
  src/NLog/Conditions/Expressions/ConditionMethodExpression.cs
  src/NLog/Conditions/Parsing/ConditionParser.cs
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Config/AssemblyExtensionTypes.tt
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/MethodFactory.cs
  src/NLog/SetupExtensionsBuilderExtensions.cs
  src/NLog/SetupLoadConfigurationExtensions.cs
  tests/NLog.UnitTests/Conditions/ConditionEvaluatorTests.cs
  tests/NLog.UnitTests/Conditions/ConditionParserTests.cs
Labels: enhancement, size/XL

#5273 TargetWithContext - Fix InternalLogger output about Object reflection needed
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Config/AssemblyExtensionTypes.tt
  src/NLog/Layouts/CSV/CsvLayout.cs
  src/NLog/Targets/TargetWithContext.cs
Labels: size/XS

#5274 Version 5.2.1
  CHANGELOG.md
  build.ps1
  src/NLog/Config/AssemblyExtensionTypes.tt
  src/NLog/NLog.csproj
Labels: version, size/M

#5276 ConfigurationItemFactory - Fix NullReferenceException when skipping already loaded assembly
  src/NLog/Config/AssemblyExtensionLoader.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
Labels: bug, size/M

#5278 Version 5.2.2
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version, size/XS

#5282 Update unit-test-projects to net6
  run-tests.ps1
  tests/NLog.Database.Tests/NLog.Database.Tests.csproj
  tests/NLog.UnitTests/Conditions/ConditionEvaluatorTests.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/Config/LogFactorySetupTests.cs
  tests/NLog.UnitTests/Internal/NetworkSenders/HttpNetworkSenderTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Contexts/EventPropertiesTests.cs
  tests/NLog.UnitTests/Mocks/WebRequestFactoryMock.cs
  tests/NLog.UnitTests/Mocks/WebRequestMock.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
  tests/NLog.WindowsRegistry.Tests/NLog.WindowsRegistry.Tests.csproj
  tests/NLog.WindowsRegistry.Tests/RegistryTests.cs
Labels: unit-tests, refactoring, size/L, platform support

#5283 Fixed sonar smells from net6 roslyn
  src/NLog/Targets/FileTarget.cs
  tests/NLog.Database.Tests/DatabaseTargetTests.cs
  tests/NLog.UnitTests/ApiTests.cs
  tests/NLog.UnitTests/AsyncHelperTests.cs
  tests/NLog.UnitTests/Common/InternalLoggerTests.cs
  tests/NLog.UnitTests/Common/InternalLoggerTests_Trace.cs
  tests/NLog.UnitTests/Conditions/ConditionParserTests.cs
  tests/NLog.UnitTests/Config/ConfigApiTests.cs
  tests/NLog.UnitTests/Config/InternalLoggingTests.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
  tests/NLog.UnitTests/Config/TimeConfigurationTests.cs
  tests/NLog.UnitTests/Contexts/MappedDiagnosticsLogicalContextTests.cs
  tests/NLog.UnitTests/Internal/FileAppenders/FileAppenderCacheTests.cs
  tests/NLog.UnitTests/Internal/PropertiesDictionaryTests.cs
  tests/NLog.UnitTests/Internal/SortHelpersTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/CallSiteFileNameLayoutTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/CallSiteTests.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Machine/LocalIpAddressLayoutRendererTests.cs
  tests/NLog.UnitTests/LayoutRenderers/VariableLayoutRendererTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutOutputTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
  tests/NLog.UnitTests/NLogTraceListenerTests.cs
  tests/NLog.UnitTests/Targets/ConsoleTargetTests.cs
  tests/NLog.UnitTests/Targets/MemoryTargetTests.cs
  tests/NLog.UnitTests/Targets/NetworkTargetTests.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/FallbackGroupTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/SplitGroupTargetTests.cs
  tests/NLog.UnitTests/TimeSourceTests.cs
Labels: refactoring, size/L

#5284 Fixed sonar smells from net6 roslyn
  tests/NLog.Database.Tests/DatabaseTargetTests.cs
  tests/NLog.UnitTests/Config/CultureInfoTests.cs
  tests/NLog.UnitTests/Config/IncludeTests.cs
  tests/NLog.UnitTests/Internal/SortHelpersTests.cs
  tests/NLog.UnitTests/Internal/Strings/StringSplitterTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
  tests/TestTrimPublish/Program.cs
Labels: refactoring, size/S

#5281 Refactor ConditionBasedFilter when filter to use ternary operator
  src/NLog/Filters/ConditionBasedFilter.cs
Labels: refactoring, size/XS

#5285 Update unit-test-projects to net6
  run-tests.ps1
  tests/ManuallyLoadedExtension/ManuallyLoadedExtension.csproj
  tests/NLog.UnitTests/Conditions/ConditionEvaluatorTests.cs
  tests/NLog.UnitTests/Internal/NetworkSenders/HttpNetworkSenderTests.cs
  tests/NLog.UnitTests/LayoutRenderers/EventPropertiesTests.cs
  tests/NLog.UnitTests/LayoutRenderers/RegistryTests.cs
  tests/NLog.UnitTests/Mocks/WebRequestFactoryMock.cs
  tests/NLog.UnitTests/Mocks/WebRequestMock.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
Labels: unit-tests, refactoring, size/M, platform support

#5287 FileTarget - FilePathLayout with fixed-filename can translate to absolute path
  src/NLog/Internal/AppDomains/FakeAppDomain.cs
  src/NLog/Internal/Files/FilePathLayout.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: performance, file-target, size/S

#5279 FileTarget - Cleanup FileSystemWatcher correctly when ArchiveFilePatternToWatch changes
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
Labels: bug, file-target, size/XS, file-archiving

#5289 Check RequiredParameter should also validate nullable types
  src/NLog/Internal/Reflection/PropertyHelper.cs
  tests/NLog.UnitTests/Config/TargetConfigurationTests.cs
Labels: bug, nlog-configuration, size/M

#5290 PropertyHelper - SetPropertyFromString allow empty string for nullable-value
  src/NLog/Internal/Reflection/PropertyHelper.cs
  tests/NLog.UnitTests/Config/TargetConfigurationTests.cs
Labels: enhancement, nlog-configuration, size/M

#5291 Report NLog version on initial configuration assignment
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/ServiceRepositoryExtensions.cs
  src/NLog/LogFactory.cs
Labels: enhancement, size/S

#5293 Report NLog version on initial configuration assignment
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
Labels: enhancement, size/S

#5296 Target precalculate should handle duplicate layouts
  src/NLog/Targets/Target.cs
  src/NLog/Targets/Wrappers/PostFilteringTargetWrapper.cs
Labels: performance, size/S

#5298 ConfigurationItemFactory - Improve obsolete message for obsoleted factory-properties
  src/NLog/Config/ConfigurationItemFactory.cs
Labels: refactoring, size/XS

#5299 MessageLayoutRenderer - Skip Flatten when simple AggregateException
  src/NLog/LayoutRenderers/MessageLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs
Labels: refactoring, size/M
