Repository NLog/NLog, pull requests merged in 2023-04, with the labels that each got.

#5187 Revert Xamarin PreserveAttribute with default values
  src/NLog/Internal/Xamarin/PreserveAttribute.cs
  src/NLog/Properties/AssemblyInfo.cs
Labels: size/XS

#5186 ScopeContext - Uniform initial small array sizes
  src/NLog/Contexts/ScopeContext.cs
  src/NLog/Internal/ScopeContextAsyncState.cs
Labels: refactoring, size/M

#5188 AppDomainWrapper - Unhandled exception on Linux without ICU package
  src/NLog/Internal/AppDomains/AppDomainWrapper.cs
Labels: refactoring, size/M

#5189 Sealed private classes to fix Sonar smells
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Filters/WhenRepeatedFilter.cs
  src/NLog/Internal/Collections/PropertiesDictionary.cs
  src/NLog/Layouts/CSV/CsvLayout.cs
  src/NLog/SetupSerializationBuilderExtensions.cs
  tests/PackageLoaderTestAssembly/NLogPackageLoaders.cs
Labels: refactoring, size/M

#5193 AsyncTaskTarget - Include task exception on completed event
  src/NLog/Targets/AsyncTaskTarget.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
Labels: enhancement, size/M

#5195 ConfigurationItemFactory - Handle concurrent registration with single lock
  src/NLog/Config/Factory.cs
  src/NLog/Config/MethodFactory.cs
Labels: enhancement, size/S

#5197 Log4jXmlEvent - Fix dummyNamespace when using IncludeScopeProperties
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/Log4JXmlTests.cs
Labels: bug, size/M

#5205 Add variables element to NLog.xsd and extend schema tests
  Test-XmlFile.ps1
  examples/targets/Configuration File/File/CSV/NLog.config
  examples/targets/Configuration File/Null/NLog.config
  examples/targets/Configuration File/Variables/NLog.config
  examples/targets/Configuration File/WebService/NLog.config
  tools/MakeNLogXSD/TemplateXSD.xml
Labels: size/M

#5206 FileTarget - Improve InternalLogger-output when re-creating after File.Exists fails
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/CountingSingleProcessFileAppender.cs
  src/NLog/Internal/FileAppenders/SingleProcessFileAppender.cs
Labels: file-target, size/XS

#5207 FileTarget - Recover from file-deleted when same archive-folder
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
  src/NLog/Internal/Files/MultiFileWatcher.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: enhancement, file-target, size/L, file-archiving

#5208 FileTarget - Only react to file-created-event when archive-folder
  src/NLog/Internal/FileAppenders/FileAppenderCache.cs
Labels: enhancement, file-target, size/M, file-archiving

#5200 JsonLayout - Added IndentJson for pretty format
  src/NLog/Layouts/JSON/JsonLayout.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
Labels: enhancement, json / json-layout, size/M

#5209 Version 5.1.4
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version, size/S
