Repository NLog/NLog, pull requests merged in 2023-11, with the labels that each got.

#5396 Added Setup-extension-method WriteToColoredConsole (Improve colors)
  src/NLog/SetupLoadConfigurationExtensions.cs
Labels: enhancement, console-target, size/S

#5397 Changed WebserviceTest_restapi_httppost from 1000 to 101 logevents
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
Labels: unit-tests, size/L

#5398 Marked obsolete members with EditorBrowsableState.Never
  src/NLog/Common/AsyncHelpers.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
  src/NLog/SetupExtensionsBuilderExtensions.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/Target.cs
Labels: refactoring, size/M

#5407 FileTarget: Add option WriteHeaderOnInitialFileOpen
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: feature, file-target, size/L

#5409 MemoryTarget - Make Logs-property thread-safe to enumerate
  src/NLog/Targets/MemoryTarget.cs
  tests/NLog.UnitTests/Targets/MemoryTargetTests.cs
Labels: enhancement, size/L

#5412 Change TargetFrameworks to net461 when old VisualStudioVersion
  tests/NLog.Database.Tests/NLog.Database.Tests.csproj
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.WindowsRegistry.Tests/NLog.WindowsRegistry.Tests.csproj
  tests/TestTrimPublish/TestTrimPublish.csproj
Labels: size/S

#5413 MultiFileWatcher - Improve InternalLogger output to match on start and stop
  src/NLog/Internal/Files/MultiFileWatcher.cs
Labels: refactoring, size/M

#5414 Bump Microsoft.SourceLink.GitHub from 1.1.1 to 8.0.0
  src/NLog.Database/NLog.Database.csproj
  src/NLog.OutputDebugString/NLog.OutputDebugString.csproj
  src/NLog.WindowsEventLog/NLog.WindowsEventLog.csproj
  src/NLog.WindowsRegistry/NLog.WindowsRegistry.csproj
  tests/NLog.Database.Tests/NLog.Database.Tests.csproj
  tests/NLog.WindowsRegistry.Tests/NLog.WindowsRegistry.Tests.csproj
Labels: dependencies

#5408 FileTarget - Rename option to WriteHeaderWhenInitialFileNotEmpty
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: file-target, refactoring, size/S

#5415 Version 5.2.6
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version, size/M

#5417 Added mark as IsTrimmable
  src/NLog.OutputDebugString/AssemblyMetadataAttribute.cs
  src/NLog.OutputDebugString/NLog.OutputDebugString.csproj
  src/NLog.WindowsEventLog/AssemblyMetadataAttribute.cs
  src/NLog.WindowsEventLog/NLog.WindowsEventLog.csproj
  src/NLog.WindowsRegistry/AssemblyMetadataAttribute.cs
  src/NLog.WindowsRegistry/NLog.WindowsRegistry.csproj
Labels: refactoring, build-config, size/L

#5420 Added IncludeSourceRevisionInInformationalVersion to fix InformationalVersion
  tests/NLogAutoLoadExtension/NLogAutoLoadExtension.csproj
Labels: build-config, size/XS

#5421 Fixed code smells by using Assert.Contains
  src/NLog/LayoutRenderers/ApplicationEnvironment/AppDomainLayoutRenderer.cs
  tests/NLog.UnitTests/Config/CultureInfoTests.cs
  tests/NLog.UnitTests/Config/XmlConfigTests.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
  tests/NLog.UnitTests/Internal/PropertiesDictionaryTests.cs
  tests/NLog.UnitTests/LayoutRenderers/ApplicationEnvironment/AppDomainLayoutRendererTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/CallSiteLineNumberTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/CallSiteTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Directories/BaseDirTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Directories/ProcessDirTests.cs
  tests/NLog.UnitTests/LayoutRenderers/IdentityTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Log4JXmlTests.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
  tests/NLog.UnitTests/Targets/AsyncTaskTargetTest.cs
  tests/NLog.UnitTests/Targets/ConsoleTargetTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
  tests/NLog.UnitTests/Targets/MemoryTargetTests.cs
  tests/NLog.UnitTests/Targets/NetworkTargetTests.cs
  tests/NLog.UnitTests/Targets/TargetTests.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
  tests/NLog.UnitTests/Targets/Wrappers/PostFilteringTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/RetryingTargetWrapperTests.cs
Labels: unit-tests, refactoring, size/L

#5419 Improved XML docs for MDC, MDLC, NDC, NDLC about being replaced by ScopeContext
  src/NLog/Abstractions/ILogger.cs
  src/NLog/Abstractions/ILoggerBase.cs
  src/NLog/Config/AssemblyLoadingEventArgs.cs
  src/NLog/Config/ConfigurationItemCreator.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/INamedItemFactory.cs
  src/NLog/Config/LoggingConfigurationChangedEventArgs.cs
  src/NLog/Config/LoggingConfigurationReloadedEventArgs.cs
  src/NLog/Config/LoggingRule.cs
  src/NLog/Config/SimpleConfigurator.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/Contexts/MappedDiagnosticsContext.cs
  src/NLog/Contexts/MappedDiagnosticsLogicalContext.cs
  src/NLog/Contexts/NestedDiagnosticsContext.cs
  src/NLog/Contexts/NestedDiagnosticsLogicalContext.cs
  src/NLog/Fluent/Log.cs
  src/NLog/Fluent/LogBuilder.cs
  src/NLog/Fluent/LoggerExtensions.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/AppSettingLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/MdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/MdlcLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/NdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/NdlcLayoutRenderer.cs
  src/NLog/LayoutRenderers/Contexts/NdlcTimingLayoutRenderer.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/Log4JXmlEventLayout.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
  src/NLog/Logger.cs
  src/NLog/NLogConfigurationException.cs
  src/NLog/NLogRuntimeException.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/MethodCallParameter.cs
  src/NLog/Targets/NLogViewerTarget.cs
  src/NLog/Targets/NetworkTargetConnectionsOverflowAction.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/TargetWithContext.cs
Labels: documentation, size/L

#5422 AppEnvironmentWrapper - Added fallback to EntryAssemblyFileName
  src/NLog/Internal/AppEnvironmentWrapper.cs
Labels: enhancement, refactoring, size/S

#5427 FileTarget - Fix Windows FileSystem Tunneling when KeepFileOpen=false
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: bug, file-target, size/M, file-archiving

#5428 Version 5.2.7
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version, size/S

#5430 PlatformDetector - NetStandard should recognize Windows NT and not old Windows
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/PlatformDetector.cs
  src/NLog/Internal/RuntimeOS.cs
Labels: enhancement
