Repository NLog/NLog, pull requests merged in 2023-01, with the labels that each got.

#5140 ConfigurationItemFactory - Handle concurrent registration with single lock
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/Factory.cs
Labels: refactoring, size/M

#5141 AsyncTaskTarget - Dynamic wait time after TaskTimeoutSeconds has expired
  src/NLog/Targets/AsyncTaskTarget.cs
Labels: enhancement, size/XS

#5144 Emit LogEventDropped event from NetworkTarget
  src/NLog/Targets/NetworkLogEventDroppedEventArgs.cs
  src/NLog/Targets/NetworkLogEventDroppedReason.cs
  src/NLog/Targets/NetworkTarget.cs
  tests/NLog.UnitTests/Targets/NetworkTargetTests.cs
Labels: enhancement, network/NLogViewer-target, size/M
