Repository NLog/NLog, pull requests merged in 2024-03, with the labels that each got.

#5480 Logger LayoutRenderer extended with PrefixName option
  src/NLog/LayoutRenderers/LoggerNameLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/LoggerNameTests.cs
Labels: enhancement, size/M

#5463 LogManager GetCurrentClassLogger fallback to assembly-name when no namespace
  appveyor.yml
  src/NLog/Internal/StackTraceUsageUtils.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/CallSiteTests.cs
Labels: enhancement, breaking behavior change, size/M

#5485 LogFactory - Disconnect from Target write and Target flush
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Internal/ITargetWithFilterChain.cs
  src/NLog/Internal/TargetWithFilterChain.cs
  src/NLog/LogFactory.cs
  src/NLog/Logger.cs
Labels: refactoring, size/L

#5489 Logging Rule with FinalMinLevel should also support dynamic filters
  src/NLog/Internal/TargetWithFilterChain.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
Labels: enhancement, size/M

#5487 CallSiteLayoutRenderer - Falback to Exception TargetSite when available
  src/NLog/LayoutRenderers/CallSite/CallSiteLayoutRenderer.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/CallSiteTests.cs
Labels: enhancement, size/L

#5490 Marked LogManager AddHiddenAssembly obsolete
  src/NLog/Internal/CallSiteInformation.cs
  src/NLog/Internal/StackTraceUsageUtils.cs
  src/NLog/LayoutRenderers/CallSite/StackTraceLayoutRenderer.cs
  src/NLog/LogEventInfo.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
  src/NLog/SetupLogFactoryBuilderExtensions.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/CallSiteTests.cs
  tests/NLog.UnitTests/LogFactoryTests.cs
Labels: breaking behavior change, size/L

#5313 Added AddCallSiteHiddenClassType to hide single class type from callsite
  src/NLog/Internal/CallSiteInformation.cs
  src/NLog/Internal/StackTraceUsageUtils.cs
  src/NLog/SetupLogFactoryBuilderExtensions.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSite/CallSiteTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
Labels: enhancement, size/M

#5380 WrapperTarget is the wrapper and not the wrapped
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
  src/NLog/Targets/Wrappers/FilteringTargetWrapper.cs
  src/NLog/Targets/Wrappers/GroupByTargetWrapper.cs
  src/NLog/Targets/Wrappers/LimitingTargetWrapper.cs
  src/NLog/Targets/Wrappers/PostFilteringTargetWrapper.cs
  src/NLog/Targets/Wrappers/RetryingTargetWrapper.cs
Labels: size/S

#5491 Marked ChildRules obsolete for LoggingRule
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Config/LoggingRule.cs
  src/NLog/Internal/TargetWithFilterChain.cs
  tests/NLog.UnitTests/Config/RuleConfigurationTests.cs
Labels: refactoring, breaking behavior change, size/S

#5416 FileTarget - Marked NetworkWrites as obsolete, and replaced by KeepFileOpen=false
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: file-target, refactoring, size/M

#5431 Marked ILoggerBase and ISuppress as obsolete and instead use ILogger
  src/NLog/Abstractions/ILogger.cs
  src/NLog/Abstractions/ILoggerBase.cs
  src/NLog/Abstractions/ISuppress.cs
Labels: breaking behavior change, size/L

#5355 Marked EscapeDataNLogLegacy as obsolete
  src/NLog/Internal/UrlHelper.cs
  src/NLog/LayoutRenderers/Wrappers/UrlEncodeLayoutRendererWrapper.cs
  src/NLog/Targets/WebServiceTarget.cs
Labels: refactoring, breaking behavior change, size/M

#5242 NLogTraceListener - Align Filter-behavior for all Write-methods
  src/NLog/NLogTraceListener.cs
  tests/NLog.UnitTests/NLogTraceListenerTests.cs
Labels: enhancement, breaking behavior change, size/L

#5495 CallSiteInformation - Reduce lookups of StackFrame.GetMethod
  src/NLog/Internal/CallSiteInformation.cs
Labels: refactoring, size/S
