Repository NLog/NLog, pull requests merged in 2024-08, with the labels that each got.

#5548 FileTarget: Reset reusable MemoryStream when above max capacity
  src/NLog/Internal/ObjectPools/ReusableAsyncLogEventList.cs
  src/NLog/Internal/ObjectPools/ReusableBufferCreator.cs
  src/NLog/Internal/ObjectPools/ReusableBuilderCreator.cs
  src/NLog/Internal/ObjectPools/ReusableObjectCreator.cs
  src/NLog/Internal/ObjectPools/ReusableStreamCreator.cs
  src/NLog/Internal/ObjectPools/StringBuilderPool.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.UnitTests/Internal/StringBuilderPoolTests.cs
Labels: enhancement, file-target, size/M

#5562 TargetWithContext - Skip caching when render value for ContextProperties
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/Typed/Layout.cs
  src/NLog/Layouts/Typed/ValueTypeLayoutInfo.cs
  src/NLog/Targets/Target.cs
Labels: performance, size/M

#5566 PropertiesDictionary - Added PropertyDictionaryEnumerator to enumerate without allocation
  src/NLog/Internal/Collections/PropertiesDictionary.cs
  src/NLog/Internal/ScopeContextPropertyEnumerator.cs
  src/NLog/Internal/XmlHelper.cs
  src/NLog/LayoutRenderers/Contexts/AllEventPropertiesLayoutRenderer.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
  src/NLog/Targets/TargetWithContext.cs
Labels: performance, json / json-layout, xml-layout, size/L

#5567 PropertiesDictionary - Simplify PropertyDictionaryEnumerator MoveNext
  src/NLog/Internal/Collections/PropertiesDictionary.cs
  src/NLog/Targets/TargetWithContext.cs
Labels: performance, refactoring, size/M

#5568 ThreadIdLayoutRenderer - Added IStringValueRenderer optimization
  src/NLog/LayoutRenderers/Threads/ThreadIdLayoutRenderer.cs
Labels: performance, size/XS

#5569 Version 5.3.3
  CHANGELOG.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version, size/M

#5570 ScopeContextPropertyEnumerator - Optimize HasUniqueCollectionKeys
  src/NLog/Internal/Collections/PropertiesDictionary.cs
  src/NLog/Internal/ScopeContextAsyncState.cs
  src/NLog/Internal/ScopeContextPropertyEnumerator.cs
Labels: performance, refactoring, size/M

#5571 XmlLayout - Fixed bug in handling unsafe xml property names
  src/NLog/Internal/XmlHelper.cs
  tests/NLog.UnitTests/Layouts/XmlLayoutTests.cs
Labels: bug, size/M

#5573 FuncThreadAgnosticLayoutRenderer - Implement IRawValue
  src/NLog/LayoutRenderers/DateTime/DateLayoutRenderer.cs
  src/NLog/LayoutRenderers/FuncThreadAgnosticLayoutRenderer.cs
Labels: enhancement, size/S

#5572 Layout.FromMethod that supports typed Layout #5532
  src/NLog/Layouts/Typed/Layout.cs
  tests/NLog.UnitTests/Layouts/LayoutTypedTests.cs
Labels: size/L

#5577 Introduced OnConfigurationAssigned to signal activation of LoggingConfiguration
  src/NLog/Common/InternalLogger.cs
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/LogFactory.cs
Labels: enhancement, size/M

#5580 Layout.FromMethod without boxing
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/Typed/Layout.cs
  src/NLog/Layouts/Typed/ValueTypeLayoutInfo.cs
  src/NLog/SetupExtensionsBuilderExtensions.cs
  tests/NLog.UnitTests/Layouts/LayoutTypedTests.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
Labels: feature, size/XL

#5582 Layout.FromMethod without boxing (refactor)
  src/NLog/Layouts/Typed/Layout.cs
  src/NLog/Layouts/Typed/LayoutTypedExtensions.cs
Labels: size/S

#5583 Layout.FromMethod without boxing (refactor)
  src/NLog/Layouts/Typed/Layout.cs
Labels: feature, size/S

#5584 Layout.FromMethod without boxing (refactor)
  src/NLog/Layouts/Typed/Layout.cs
Labels: feature, size/XS

#5586 Layout.FromMethod without boxing (refactor)
  src/NLog/Layouts/Typed/ValueTypeLayoutInfo.cs
Labels: feature, size/S

#5585 Fixed various issues reported by EnableNETAnalyzers
  src/NLog/Internal/XmlHelper.cs
  src/NLog/LayoutRenderers/CallSite/StackTraceLayoutRenderer.cs
  src/NLog/Layouts/LayoutParser.cs
  src/NLog/LogFactory.cs
  src/NLog/LogLevel.cs
  src/NLog/SetupBuilderExtensions.cs
  src/NLog/SetupLoadConfigurationExtensions.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeDateAndSequence.cs
  src/NLog/Targets/FileArchiveModes/FileArchiveModeSequence.cs
Labels: refactoring, size/S
