Repository NLog/NLog, pull requests merged in 2024-10, with the labels that each got.

#5604 Remove Serializable-attribute and SerializationInfo since obsolete in NET8
  src/NLog/Common/InternalLogger.cs
  src/NLog/Conditions/Exceptions/ConditionEvaluationException.cs
  src/NLog/Conditions/Exceptions/ConditionParseException.cs
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Config/ConfigSectionHandler.cs
  src/NLog/Config/LoggingConfigurationFileLoader.cs
  src/NLog/Config/LoggingConfigurationWatchableFileLoader.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/Contexts/NestedDiagnosticsLogicalContext.cs
  src/NLog/Internal/Abstractions/IConfigurationManager.cs
  src/NLog/Internal/AppDomains/AppDomainWrapper.cs
  src/NLog/Internal/ConfigurationManager.cs
  src/NLog/Internal/DynamicallyAccessedMemberTypes.cs
  src/NLog/Internal/FileAppenders/BaseMutexFileAppender.cs
  src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs
  src/NLog/LayoutRenderers/ApplicationEnvironment/AppSettingLayoutRenderer.cs
  src/NLog/LogFactory.cs
  src/NLog/NLogConfigurationException.cs
  src/NLog/NLogRuntimeException.cs
  src/NLog/Targets/EventLogTarget.cs
  src/NLog/Targets/FileTarget.cs
  src/NLog/Targets/MailTarget.cs
Labels: refactoring, size/M

#5617 Removed NLog.Fluent since obsolete
  src/NLog/Fluent/Log.cs
  src/NLog/Fluent/LogBuilder.cs
  src/NLog/Fluent/LoggerExtensions.cs
  tests/NLog.UnitTests/Fluent/LogBuilderTests.cs
Labels: breaking change, size/XXL

#5620 Remove obsolete MDLC + NDLC from TargetWithContext
  src/NLog/Targets/TargetWithContext.cs
Labels: breaking change, size/L

#5619 Remove obsolete LogToTrace from InternalLogger
  src/NLog/Common/IInternalLoggerContext.cs
  src/NLog/Common/InternalLogger.cs
  src/NLog/Common/InternalLoggerMessageEventArgs.cs
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/SetupInternalLoggerBuilderExtensions.cs
  tests/NLog.UnitTests/Common/InternalLoggerTests.cs
  tests/NLog.UnitTests/Common/InternalLoggerTests_Trace.cs
  tests/NLog.UnitTests/Config/InternalLoggingTests.cs
  tests/NLog.UnitTests/Config/LogFactorySetupTests.cs
Labels: breaking change, size/XL

#5618 Remove obsolete LayoutRenderers MDC + MDLC + NDC + NDLC
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Config/AssemblyExtensionTypes.tt
  src/NLog/LayoutRenderers/MdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/MdlcLayoutRenderer.cs
  src/NLog/LayoutRenderers/NdcLayoutRenderer.cs
  src/NLog/LayoutRenderers/NdlcLayoutRenderer.cs
  src/NLog/LayoutRenderers/NdlcTimingLayoutRenderer.cs
  src/NLog/LayoutRenderers/ScopeContextNestedStatesLayoutRenderer.cs
  src/NLog/LayoutRenderers/ScopeContextPropertyLayoutRenderer.cs
  src/NLog/LayoutRenderers/ScopeContextTimingLayoutRenderer.cs
Labels: breaking change, size/XL

#5621 ConfigurationItemFactory - Remove obsolete registration methods
  src/NLog.sln
  src/NLog/Config/AssemblyExtensionLoader.cs
  src/NLog/Config/AssemblyLoadingEventArgs.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Config/Factory.cs
  src/NLog/Config/IFactory.cs
  src/NLog/Config/INamedItemFactory.cs
  src/NLog/Config/MethodFactory.cs
  src/NLog/Layouts/LayoutParser.cs
  src/NLog/SetupExtensionsBuilderExtensions.cs
  tests/NLog.UnitTests/Config/ConfigurationItemFactoryTests.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/PackageLoaderTestAssembly/NLogPackageLoaders.cs
  tests/PackageLoaderTestAssembly/PackageLoaderTestAssembly.csproj
Labels: breaking change, size/XXL

#5625 Removed obsolete public IAppDomain from LogFactory
  src/NLog/Internal/AppDomainWrapper.cs
  src/NLog/Internal/AppEnvironmentWrapper.cs
  src/NLog/Internal/IAppDomain.cs
  src/NLog/Internal/IAppEnvironment.cs
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/ApiTests.cs
  tests/NLog.UnitTests/LayoutRenderers/BaseDirTests.cs
  tests/NLog.UnitTests/Mocks/AppDomainMock.cs
  tests/NLog.UnitTests/Mocks/AppEnvironmentMock.cs
Labels: breaking change, size/XL

#5626 Removed obsolete ConfigurationReloaded from LogFactory
  src/NLog/Config/LoggingConfigurationReloadedEventArgs.cs
  src/NLog/Config/LoggingConfigurationWatchableFileLoader.cs
  src/NLog/LogFactory.cs
  src/NLog/LogManager.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
Labels: breaking change, size/L

#5627 Now checking define NETFRAMEWORK since the odd one
  src/NLog.Database/DatabaseTarget.cs
  src/NLog.WindowsRegistry/RegistryLayoutRenderer.cs
  src/NLog/Common/InternalLogger.cs
  src/NLog/Config/AssemblyExtensionTypes.tt
  src/NLog/Config/Factory.cs
  src/NLog/Internal/AppEnvironmentWrapper.cs
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/BaseMutexFileAppender.cs
  src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs
  src/NLog/Internal/MutexDetector.cs
  src/NLog/Internal/NativeMethods.cs
  src/NLog/Internal/PlatformDetector.cs
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/Internal/Win32FileNativeMethods.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/EventLogTargetOverflowAction.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.Database.Tests/DatabaseTargetTests.cs
  tests/NLog.UnitTests/Config/CultureInfoTests.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
  tests/NLog.UnitTests/Internal/FileAppenders/FileAppenderCacheTests.cs
  tests/NLog.UnitTests/Internal/PlatformDetectorTests.cs
  tests/NLog.UnitTests/LayoutRenderers/AppSettingTests.cs
  tests/NLog.UnitTests/LayoutRenderers/AssemblyVersionTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteFileNameLayoutTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteLineNumberTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteTests.cs
  tests/NLog.UnitTests/LogManagerTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
  tests/NLog.UnitTests/ProcessRunner.cs
  tests/NLog.UnitTests/Targets/ConcurrentFileTargetTests.cs
  tests/NLog.UnitTests/Targets/DebugSystemTargetTests.cs
  tests/NLog.UnitTests/Targets/EventLogTargetTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
  tests/NLog.UnitTests/Targets/MailTargetTests.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
  tests/NLog.WindowsRegistry.Tests/RegistryTests.cs
Labels: refactoring, size/L

#5628 Now checking define NETFRAMEWORK since the odd one
  src/NLog.Database/DatabaseTarget.cs
  src/NLog.WindowsRegistry/RegistryLayoutRenderer.cs
  src/NLog/Common/InternalLogger.cs
  src/NLog/Config/Factory.cs
  src/NLog/Internal/FileAppenders/BaseFileAppender.cs
  src/NLog/Internal/FileAppenders/BaseMutexFileAppender.cs
  src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs
  src/NLog/Internal/MutexDetector.cs
  src/NLog/Internal/NativeMethods.cs
  src/NLog/Internal/PlatformDetector.cs
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/Internal/Win32FileNativeMethods.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/Targets/AsyncTaskTarget.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/EventLogTargetOverflowAction.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.Database.Tests/DatabaseTargetTests.cs
  tests/NLog.UnitTests/Config/CultureInfoTests.cs
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
  tests/NLog.UnitTests/Internal/FileAppenders/FileAppenderCacheTests.cs
  tests/NLog.UnitTests/Internal/PlatformDetectorTests.cs
  tests/NLog.UnitTests/LayoutRenderers/AppSettingTests.cs
  tests/NLog.UnitTests/LayoutRenderers/AssemblyVersionTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteFileNameLayoutTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteLineNumberTests.cs
  tests/NLog.UnitTests/LayoutRenderers/CallSiteTests.cs
  tests/NLog.UnitTests/LogManagerTests.cs
  tests/NLog.UnitTests/NLogTestBase.cs
  tests/NLog.UnitTests/ProcessRunner.cs
  tests/NLog.UnitTests/Targets/ConcurrentFileTargetTests.cs
  tests/NLog.UnitTests/Targets/DebugSystemTargetTests.cs
  tests/NLog.UnitTests/Targets/EventLogTargetTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
  tests/NLog.UnitTests/Targets/MailTargetTests.cs
  tests/NLog.UnitTests/Targets/WebServiceTargetTests.cs
  tests/NLog.WindowsRegistry.Tests/RegistryTests.cs
Labels: refactoring, size/L

#5630 LogAssemblyVersion should check InternalLogger IsInfoEnabled
  src/NLog/Common/InternalLogger.cs
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
Labels: enhancement, size/XS

#5632 Removed obsolete method LogAssemblyVersion from InternalLogger
  src/NLog/Common/InternalLogger.cs
  src/NLog/Config/AssemblyExtensionLoader.cs
  src/NLog/Internal/AssemblyHelpers.cs
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/Internal/AppDomainPartialTrustTests.cs
Labels: breaking change, size/L

#5633 Removed constructor reflection from ServiceRepository
  src/NLog/Config/ServiceRepositoryInternal.cs
  tests/NLog.UnitTests/Config/ServiceRepositoryTests.cs
Labels: breaking change, size/L

#5637 Updated dependabot.yml after removal of NETSTANDARD1
  .github/dependabot.yml
  src/NLog.sln
Labels: size/M

#5641 Fix XML docs for ICreateFileParameters options
  src/NLog/Internal/FileAppenders/ICreateFileParameters.cs
Labels: size/XS

#5639 Fixing Failed to convert the binary code coverage reports to XML in SonarQube
  src/NLog.Targets.Network/Internal/PlatformDetector.cs
  src/NLog.Targets.Network/Internal/PlatformOS.cs
  src/NLog.Targets.Network/Internal/XmlHelpers.cs
  src/NLog.Targets.Network/Log4JXmlEventLayoutRenderer.cs
  src/NLog.Targets.Network/Log4JXmlEventParameter.cs
  src/NLog.Targets.Network/NLog.Targets.Network.csproj
  src/NLog.Targets.Network/NetworkSenders/IWebRequestFactory.cs
  src/NLog.Targets.Network/NetworkSenders/TcpNetworkSender.cs
  src/NLog.Targets.Network/NetworkTarget.cs
  src/NLog.Targets.Network/README.md
  src/NLog.Targets.WebService/NLog.Targets.WebService.csproj
  src/NLog/Internal/PlatformDetector.cs
  tests/NLog.Database.Tests/NLog.Database.Tests.csproj
  tests/NLog.Targets.Mail.Tests/NLog.Targets.Mail.Tests.csproj
  tests/NLog.Targets.Network.Tests/Log4JXmlTests.cs
  tests/NLog.Targets.Network.Tests/NLog.Targets.Network.Tests.csproj
  tests/NLog.Targets.Network.Tests/NetworkSenders/HttpNetworkSenderTests.cs
  tests/NLog.Targets.Network.Tests/NetworkSenders/ManualDisposableMemoryStream.cs
  tests/NLog.Targets.Network.Tests/NetworkSenders/WebRequestFactoryMock.cs
  tests/NLog.Targets.Network.Tests/NetworkSenders/WebRequestMock.cs
  tests/NLog.Targets.Network.Tests/NetworkTargetTests.cs
  tests/NLog.Targets.WebService.Tests/NLog.Targets.WebService.Tests.csproj
  tests/NLog.WindowsRegistry.Tests/NLog.WindowsRegistry.Tests.csproj
Labels: size/L

#5643 Log4JXmlTests more stable by extension registration upfront
  src/NLog/Targets/Wrappers/BufferingTargetWrapper.cs
  tests/NLog.Targets.Network.Tests/Log4JXmlTests.cs
Labels: unit-tests, size/XS

#5645 Improve test-coverage of source-code
  src/NLog.Targets.Network/Internal/PlatformDetector.cs
  src/NLog.Targets.Network/NetworkSenders/HttpNetworkSender.cs
  src/NLog.Targets.Network/NetworkSenders/QueuedNetworkSender.cs
  src/NLog/Internal/PlatformDetector.cs
  src/NLog/Internal/ReflectionHelpers.cs
Labels: unit-tests, size/M

#5646 ColoredConsoleTarget without direct RegEx support for word highlight
  build.ps1
  run-tests.ps1
  src/NLog.RegEx/Conditions/RegexConditionMethods.cs
  src/NLog.RegEx/Internal/RegexHelper.cs
  src/NLog.RegEx/LayoutRenderers/Wrappers/RegexReplaceLayoutRendererWrapper.cs
  src/NLog.RegEx/NLog.RegEx.csproj
  src/NLog.RegEx/README.md
  src/NLog.RegEx/Targets/ConsoleWordHighlightingRuleRegex.cs
  src/NLog.Targets.WebService/WebServiceTarget.cs
  src/NLog.sln
  src/NLog/Conditions/ConditionMethods.cs
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Config/AssemblyExtensionTypes.tt
  src/NLog/Internal/StringHelpers.cs
  src/NLog/LayoutRenderers/Wrappers/ReplaceLayoutRendererWrapper.cs
  src/NLog/Targets/ColoredConsoleTarget.cs
  src/NLog/Targets/ConsoleWordHighlightingRule.cs
  tests/NLog.RegEx.Tests/ColoredConsoleTargetTests.cs
  tests/NLog.RegEx.Tests/ConditionEvaluatorTests.cs
  tests/NLog.RegEx.Tests/NLog.RegEx.Tests.csproj
  tests/NLog.RegEx.Tests/RegexReplaceTests.cs
  tests/NLog.UnitTests/Conditions/ConditionEvaluatorTests.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/ReplaceTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs
  tests/NLog.UnitTests/Targets/ColoredConsoleTargetTests.cs
Labels: breaking change, size/XXL

#5647 Regex-Replace - Removed RegEx-option since implicit by type name
  src/NLog.RegEx/LayoutRenderers/Wrappers/RegexReplaceLayoutRendererWrapper.cs
  tests/NLog.RegEx.Tests/RegexReplaceTests.cs
Labels: breaking change, size/S

#5653 Fix Sonar Qube issues in example code
  examples/ExtendingLoggers/README.html
  examples/targets/Configuration API/ASPNetBufferingWrapper/NormalPage.aspx
  examples/targets/Configuration API/ASPNetBufferingWrapper/PageWithWarnings.aspx
  examples/targets/Configuration API/ASPNetTrace/test.aspx
Labels: documentation, size/S

#5652 ObjectGraphScanner - Handle property-getter that throws when AOT
  .bettercodehub.yml
  .coderabbit.yaml
  src/NLog/Internal/ObjectGraphScanner.cs
  tests/NLog.Database.Tests/DatabaseTargetTests.cs
  tests/NLog.Targets.Network.Tests/NetworkTargetTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
Labels: enhancement, size/L

#5654 Fix Sonar issues in example code
  examples/ExtendingLoggers/README.html
  examples/targets/Configuration API/ASPNetBufferingWrapper/NormalPage.aspx
  examples/targets/Configuration API/ASPNetBufferingWrapper/PageWithWarnings.aspx
  examples/targets/Configuration API/ASPNetTrace/test.aspx
Labels: documentation, size/S

#5655 LoggingConfigurationParser - Handle property-getter that throws when AOT
  src/NLog/Config/LoggingConfigurationParser.cs
Labels: enhancement, size/M

#5656 LoggingConfigurationParser - Handle property-getter that throws when AOT
  src/NLog/Config/LoggingConfigurationParser.cs
Labels: enhancement, size/M
