Repository NLog/NLog, pull requests merged in 2025-06, with the labels that each got.

#5856 Moved details about contribution into CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  src/NLog.sln
Labels: size/M

#5858 ConsoleTarget - Added ForceWriteLine to match NLog v6 Schema
  src/NLog/Targets/ConsoleTarget.cs
Labels: enhancement, size/XS

#5851 Version 6.0 RC2
  CHANGELOG.md
  build.ps1
  src/NLog/Config/Factory.cs
  src/NLog/LogEventInfo.cs
  src/NLog/NLog.csproj
  tests/NLog.UnitTests/LogMessageFormatterTests.cs
Labels: version, size/L

#5860 NLog.Schema nuget-package code-example
  README.md
  src/NuGet/NLog.Schema/NLog.Schema.nuspec
Labels: documentation, size/S

#5866 Layout.FromLiteral to match NLog v6
  src/NLog/Layouts/Layout.cs
Labels: enhancement, size/S

#5863 Log4JXmlEventLayout - Support IncludeEmptyValue for Parameters
  src/NLog.Targets.Network/Layouts/Log4JXmlEventLayout.cs
  src/NLog/LayoutRenderers/Wrappers/WhenEmptyLayoutRendererWrapper.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
  tests/NLog.Targets.Network.Tests/Log4JXmlTests.cs
Labels: size/L, log4jxml-layout

#5869 Version 6.0 RC3
  CHANGELOG.md
  README.md
  build.ps1
  src/NLog/NLog.csproj
Labels: version, size/S

#5871 RegisterObjectTransformation so build trimming will keep public properties
  src/NLog/SetupSerializationBuilderExtensions.cs
Labels: enhancement, size/S

#5878 DatabaseTarget with support for AOT without type-reflection
  run-tests.ps1
  src/NLog.Database/DatabaseObjectPropertyInfo.cs
  src/NLog.Database/DatabaseParameterInfo.cs
  src/NLog.Database/DatabaseTarget.cs
  src/NLog.Database/NLog.Database.csproj
  tests/NLog.Database.Tests/DatabaseTargetTests.cs
  tests/NLog.Database.Tests/NLog.Database.Tests.csproj
Labels: database-target, size/L, platform support

#5884 TargetWithLayoutHeaderAndFooter - Layout-property-getter without casting check
  src/NLog.Database/DatabaseTarget.cs
  src/NLog/Targets/TargetWithLayoutHeaderAndFooter.cs
Labels: performance, size/M

#5883 AsyncTargetWrapper - LogEventDropped and EventQueueGrow events fixes
  src/NLog/Targets/Wrappers/AsyncRequestQueue-T.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncRequestQueueTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/CommonRequestQueueTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/ConcurrentRequestQueueTests.cs
Labels: bug, size/L

#5885 AsyncTargetWrapper - LogEventDropped and EventQueueGrow events fixes
  src/NLog/Targets/Wrappers/AsyncRequestQueue-T.cs
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
  src/NLog/Targets/Wrappers/ConcurrentRequestQueue.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncRequestQueueTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/AsyncTargetWrapperTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/CommonRequestQueueTests.cs
  tests/NLog.UnitTests/Targets/Wrappers/ConcurrentRequestQueueTests.cs
Labels: bug, size/L

#5888 ChainsawTarget with type-alias Log4JXml to match NLog v6
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Targets/ChainsawTarget.cs
Labels: enhancement, size/XS

#5889 StringBuilderExt - Change Append2DigitsZeroPadded to array-lookup
  src/NLog/Internal/AppendBuilderCreator.cs
  src/NLog/Internal/StringBuilderExt.cs
  src/NLog/LayoutRenderers/LevelLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/WrapperLayoutRendererBuilderBase.cs
  src/NLog/Targets/FileTarget.cs
Labels: performance, size/M

#5892 NLog v6 API Docs
  src/NLog.Targets.GZipFile/GZipFileTarget.cs
  src/NLog.Targets.GZipFile/NLog.Targets.GZipFile.csproj
  src/NLog.Targets.Network/Targets/Log4JXmlTarget.cs
  src/NLog.Targets.Trace/NLog.Targets.Trace.csproj
  src/NLog/Targets/ColoredConsoleTarget.cs
  tools/NLogNugetPackages/NLogNugetPackages.csproj
  tools/SandcastleDocs/BuildDoc.cmd
  tools/SandcastleDocs/NLog.shfbproj
  tools/SandcastleDocs/dll_to_doc/dll_to_doc.csproj
Labels: documentation, size/L

#5902 ConditionBasedFilter - Changed Condition to non-nullable
  src/NLog/Filters/ConditionBasedFilter.cs
Labels: size/XS

#5891 AtomicFileTarget - Added net8.0-windows without mono-dependency
  build.ps1
  src/NLog.Targets.AtomicFile/AtomicFileTarget.cs
  src/NLog.Targets.AtomicFile/NLog.Targets.AtomicFile.csproj
Labels: enhancement, size/M, platform support

#5906 ConditionExpression without reflection
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Config/AssemblyExtensionTypes.tt
Labels: enhancement, size/S

#5909 ConfigurationItemFactory - Added extension hints for webservice and activityid
  src/NLog/Config/Factory.cs
  tools/NLogNugetPackages/NLogNugetPackages.csproj
Labels: enhancement, size/S
