Repository NLog/NLog, pull requests merged in 2025-07, with the labels that each got.

#5912 NLog.Targets.Trace - Updated nuget-package README.md
  src/NLog.Targets.Network/README.md
  src/NLog.Targets.Trace/README.md
  tests/NLog.UnitTests/Targets/Wrappers/FallbackGroupTargetTests.cs
Labels: documentation, size/M

#5913 NLog.Targets.Network - Fixed ReadMe.md with link to Log4JXml-target
  src/NLog.Targets.Network/Layouts/SyslogFacility.cs
  src/NLog.Targets.Network/README.md
Labels: documentation, size/S

#5918 Log4JXmlTarget - Removed alias NLogViewer as conflicts with other nuget-packages
  src/NLog.Targets.Network/Targets/Log4JXmlTarget.cs
  src/NLog/Config/ConfigurationItemFactory.cs
Labels: enhancement, size/XS

#5915 ReplaceNewLinesLayoutRendererWrapper - Replace all line ending characters
  src/NLog/LayoutRenderers/Wrappers/ReplaceNewLinesLayoutRendererWrapper.cs
  tests/NLog.UnitTests/LayoutRenderers/Wrappers/ReplaceNewLinesTests.cs
Labels: enhancement, size/L

#5921 FileTarget - Activate legacy ArchiveFileName when ArchiveSuffixFormat contains legacy placeholder
  src/NLog/Targets/FileTarget.cs
Labels: enhancement, file-target, size/XS, file-archiving

#5911 NLog.Targets.GZipFile - Improve support for ArchiveAboveSize
  src/NLog.Targets.GZipFile/GZipFileTarget.cs
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/FileAppenders/ExclusiveFileLockingAppender.cs
  src/NLog/Targets/FileArchiveHandlers/BaseFileArchiveHandler.cs
  src/NLog/Targets/FileArchiveHandlers/RollingArchiveFileHandler.cs
  src/NLog/Targets/FileTarget.cs
  tests/NLog.Targets.GZipFile.Tests/GZipFileTests.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: enhancement, file-target, size/L, file-archiving

#5923 Updated unit-tests from NET6 to NET8
  run-tests.ps1
  tests/NLog.RegEx.Tests/NLog.RegEx.Tests.csproj
  tests/NLog.Targets.ConcurrentFile.Tests/NLog.Targets.ConcurrentFile.Tests.csproj
  tests/NLog.Targets.GZipFile.Tests/NLog.Targets.GZipFile.Tests.csproj
  tests/NLog.Targets.Mail.Tests/NLog.Targets.Mail.Tests.csproj
  tests/NLog.Targets.Network.Tests/NLog.Targets.Network.Tests.csproj
  tests/NLog.Targets.Trace.Tests/NLog.Targets.Trace.Tests.csproj
  tests/NLog.Targets.WebService.Tests/NLog.Targets.WebService.Tests.csproj
  tests/NLog.UnitTests/Config/ExtensionTests.cs
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.WindowsRegistry.Tests/NLog.WindowsRegistry.Tests.csproj
Labels: unit-tests, size/M, platform support

#5924 AsyncTargetWrapper - Updated FullBatchSizeWriteLimit default value from 5 to 10
  src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs
Labels: size/XS

#5926 SplunkTarget - NetworkTarget with SplunkLayout
  src/NLog.Targets.Network/Layouts/GelfLayout.cs
  src/NLog.Targets.Network/Layouts/SplunkLayout.cs
  src/NLog.Targets.Network/Layouts/SyslogLayout.cs
  src/NLog.Targets.Network/Targets/NetworkLogEventDroppedEventArgs.cs
  src/NLog.Targets.Network/Targets/SplunkTarget.cs
  tests/NLog.Targets.Network.Tests/NetworkTargetTests.cs
  tests/NLog.Targets.Network.Tests/SplunkLayoutTests.cs
Labels: feature, needs documentation on wiki, network/NLogViewer-target, size/XL

#5931 Fixed Sonar code smells
  src/NLog/Internal/TargetWithFilterChain.cs
  tests/NLog.Targets.Network.Tests/LocalIpAddressLayoutRendererTests.cs
Labels: unit-tests, refactoring, size/XS

#5933 Handle invalid message template when skipping parameters array
  src/NLog/Logger.cs
  tests/NLog.UnitTests/LoggerTests.cs
Labels: bug, size/M

#5936 NLog v5.5.1
  README.md
  build.ps1
  src/NLog/Layouts/XML/XmlElementBase.cs
  src/NLog/NLog.csproj
  src/NLog/SetupSerializationBuilderExtensions.cs
  tests/NLog.UnitTests/Layouts/XmlLayoutTests.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
Labels: version, size/L

#5935 Improve NLog XSD Schema with better handling of typed Layout
  tools/DumpApiXml/DocFileBuilder.cs
Labels: documentation, size/M

#5942 Verify ExpandoObject are still supported with NLog v6
  src/NLog/Internal/ObjectReflectionCache.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: unit-tests, size/S

#5945 NLog.Targets.AtomicFile - Added README.md for nuget-package
  src/NLog.Targets.AtomicFile/README.md
  src/NLog.Targets.ConcurrentFile/README.md
  src/NLog.Targets.GZipFile/README.md
Labels: documentation, size/M

#5950 SplunkLayout - Restore SplunkEvents but as obsolete
  src/NLog.Targets.Network/Layouts/SplunkLayout.cs
  src/NLog.Targets.WebService/WebServiceTarget.cs
  src/NLog/Config/RequiredParameterAttribute.cs
  src/NLog/Config/StackTraceUsage.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/LayoutRenderers/FuncLayoutRenderer.cs
  src/NLog/LayoutRenderers/ScopeContextTimingLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/WrapperLayoutRendererBuilderBase.cs
  src/NLog/Layouts/LayoutRenderOptions.cs
  src/NLog/Layouts/SimpleLayout.cs
  src/NLog/LogEventInfo.cs
  src/NLog/LogManager.cs
  src/NLog/MappedDiagnosticsContext.cs
  src/NLog/MappedDiagnosticsLogicalContext.cs
  src/NLog/NestedDiagnosticsContext.cs
  src/NLog/NestedDiagnosticsLogicalContext.cs
  src/NLog/Targets/ConsoleTarget.cs
  src/NLog/Targets/FileTarget.cs
Labels: enhancement, network/NLogViewer-target, size/M
