Repository NLog/NLog, pull requests merged in 2025-04, with the labels that each got.

#5754 NLog.Targets.Network - Introduced SyslogTarget and SyslogLayout
  src/NLog.Targets.Network/Layouts/Log4JXmlEventLayout.cs
  src/NLog.Targets.Network/Layouts/Log4JXmlEventLayoutRenderer.cs
  src/NLog.Targets.Network/Layouts/Log4JXmlEventParameter.cs
  src/NLog.Targets.Network/Layouts/SyslogFacility.cs
  src/NLog.Targets.Network/Layouts/SyslogLayout.cs
  src/NLog.Targets.Network/Layouts/SyslogSeverity.cs
  src/NLog.Targets.Network/NetworkSenders/SslSocketProxy.cs
  src/NLog.Targets.Network/Targets/ChainsawTarget.cs
  src/NLog.Targets.Network/Targets/NetworkLogEventDroppedEventArgs.cs
  src/NLog.Targets.Network/Targets/NetworkLogEventDroppedReason.cs
  src/NLog.Targets.Network/Targets/NetworkTarget.cs
  src/NLog.Targets.Network/Targets/NetworkTargetCompressionType.cs
  src/NLog.Targets.Network/Targets/NetworkTargetConnectionsOverflowAction.cs
  src/NLog.Targets.Network/Targets/NetworkTargetOverflowAction.cs
  src/NLog.Targets.Network/Targets/NetworkTargetQueueOverflowAction.cs
  src/NLog.Targets.Network/Targets/SyslogTarget.cs
  src/NLog/LogFactory.cs
  tests/NLog.Targets.Network.Tests/SyslogLayoutTests.cs
  tests/NLog.UnitTests/ApiTests.cs
Labels: feature, needs documentation on wiki, network/NLogViewer-target, size/XXL

#5757 ServiceRepository - Failing to resolve service-type should report service-type in Exception message
  src/NLog/Config/ServiceRepositoryExtensions.cs
  src/NLog/Config/ServiceRepositoryInternal.cs
Labels: refactoring, size/S

#5760 ServiceRepository - Failing to resolve service-type should report service-type in Exception message
  src/NLog/Config/ServiceRepositoryExtensions.cs
  src/NLog/Config/ServiceRepositoryInternal.cs
Labels: refactoring, size/S

#5759 LayoutRenderer - Skip caching result of Inner Layout Render
  src/NLog/Filters/WhenContainsFilter.cs
  src/NLog/Filters/WhenEqualFilter.cs
  src/NLog/Filters/WhenNotContainsFilter.cs
  src/NLog/Filters/WhenNotEqualFilter.cs
  src/NLog/Filters/WhenRepeatedFilter.cs
  src/NLog/LayoutRenderers/CounterLayoutRenderer.cs
  src/NLog/LayoutRenderers/EnvironmentLayoutRenderer.cs
  src/NLog/LayoutRenderers/ScopeContextIndentLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/CachedLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WhenEmptyLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WrapperLayoutRendererBase.cs
Labels: performance, size/M

#5763 ExceptionLayoutRenderer - Error handling for Exception Properties that throws
  src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs
Labels: refactoring, size/S

#5767 Marked JsonLayout EscapeForwardSlash as obsolete and without any effect
  src/NLog/LayoutRenderers/Wrappers/JsonEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/JSON/JsonAttribute.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/JsonSerializeOptions.cs
Labels: breaking behavior change, size/S

#5768 Updated API examples from SimpleConfigurator to LoggingConfiguration
  examples/targets/Configuration API/ASPNetBufferingWrapper/Global.asax.cs
  examples/targets/Configuration API/ASPNetTrace/Global.asax.cs
  examples/targets/Configuration API/AsyncWrapper/Wrapping File/Example.cs
  examples/targets/Configuration API/AutoFlushWrapper/Simple/Example.cs
  examples/targets/Configuration API/BufferingWrapper/Simple/Example.cs
  examples/targets/Configuration API/Chainsaw/Simple/Example.cs
  examples/targets/Configuration API/ColoredConsole/Row Highlighting/Example.cs
  examples/targets/Configuration API/ColoredConsole/Simple/Example.cs
  examples/targets/Configuration API/ColoredConsole/Word Highlighting/Example.cs
  examples/targets/Configuration API/Console/Simple/Example.cs
  examples/targets/Configuration API/Database/MSSQL/Example.cs
  examples/targets/Configuration API/Database/Oracle.Native/Example.cs
  examples/targets/Configuration API/Database/Oracle.OleDb/Example.cs
  examples/targets/Configuration API/Debug/Simple/Example.cs
  examples/targets/Configuration API/Debugger/Simple/Example.cs
  examples/targets/Configuration API/EventLog/Simple/Example.cs
  examples/targets/Configuration API/FallbackGroup/Simple/Example.cs
  examples/targets/Configuration API/File/Archive1/Example.cs
  examples/targets/Configuration API/File/Archive2/Example.cs
  examples/targets/Configuration API/File/Archive3/Example.cs
  examples/targets/Configuration API/File/Archive4/Example.cs
  examples/targets/Configuration API/File/Asynchronous/Example.cs
  examples/targets/Configuration API/File/CSV/Example.cs
  examples/targets/Configuration API/File/Multiple/Example.cs
  examples/targets/Configuration API/File/Multiple2/Example.cs
  examples/targets/Configuration API/File/Simple/Example.cs
  examples/targets/Configuration API/FilteringWrapper/Simple/Example.cs
  examples/targets/Configuration API/MSMQ/Multiple Queues/Example.cs
  examples/targets/Configuration API/MSMQ/Simple/Example.cs
  examples/targets/Configuration API/Mail/Buffered/Example.cs
  examples/targets/Configuration API/Mail/Simple/Example.cs
  examples/targets/Configuration API/Memory/Simple/Example.cs
  examples/targets/Configuration API/MethodCall/Simple/Example.cs
  examples/targets/Configuration API/NLogViewer/Simple/Example.cs
  examples/targets/Configuration API/Network/Simple/Example.cs
  examples/targets/Configuration API/Null/Simple/Example.cs
  examples/targets/Configuration API/OutputDebugString/Simple/Example.cs
  examples/targets/Configuration API/PerfCounter/Simple/Example.cs
  examples/targets/Configuration API/PostFilteringWrapper/Simple/Example.cs
  examples/targets/Configuration API/RandomizeGroup/Simple/Example.cs
  examples/targets/Configuration API/RepeatingWrapper/Simple/Example.cs
  examples/targets/Configuration API/RetryingWrapper/Simple/Example.cs
  examples/targets/Configuration API/RoundRobinGroup/Simple/Example.cs
  examples/targets/Configuration API/SplitGroup/Simple/Example.cs
  examples/targets/Configuration API/Trace/Simple/Example.cs
  examples/targets/Configuration API/WebService/Simple/Example.cs
Labels: documentation, size/L

#5769 Updated API examples from SimpleConfigurator to LoggingConfiguration
  examples/targets/Configuration API/ASPNetBufferingWrapper/Global.asax.cs
  examples/targets/Configuration API/ASPNetTrace/Global.asax.cs
  examples/targets/Configuration API/AsyncWrapper/Wrapping File/Example.cs
  examples/targets/Configuration API/AutoFlushWrapper/Simple/Example.cs
  examples/targets/Configuration API/BufferingWrapper/Simple/Example.cs
  examples/targets/Configuration API/Chainsaw/Simple/Example.cs
  examples/targets/Configuration API/ColoredConsole/Row Highlighting/Example.cs
  examples/targets/Configuration API/ColoredConsole/Simple/Example.cs
  examples/targets/Configuration API/ColoredConsole/Word Highlighting/Example.cs
  examples/targets/Configuration API/Console/Simple/Example.cs
  examples/targets/Configuration API/Database/MSSQL/Example.cs
  examples/targets/Configuration API/Database/Oracle.Native/Example.cs
  examples/targets/Configuration API/Database/Oracle.OleDb/Example.cs
  examples/targets/Configuration API/Debug/Simple/Example.cs
  examples/targets/Configuration API/Debugger/Simple/Example.cs
  examples/targets/Configuration API/EventLog/Simple/Example.cs
  examples/targets/Configuration API/FallbackGroup/Simple/Example.cs
  examples/targets/Configuration API/File/Archive1/Example.cs
  examples/targets/Configuration API/File/Archive2/Example.cs
  examples/targets/Configuration API/File/Archive3/Example.cs
  examples/targets/Configuration API/File/Archive4/Example.cs
  examples/targets/Configuration API/File/Asynchronous/Example.cs
  examples/targets/Configuration API/File/CSV/Example.cs
  examples/targets/Configuration API/File/Multiple/Example.cs
  examples/targets/Configuration API/File/Multiple2/Example.cs
  examples/targets/Configuration API/File/Simple/Example.cs
  examples/targets/Configuration API/FilteringWrapper/Simple/Example.cs
  examples/targets/Configuration API/MSMQ/Multiple Queues/Example.cs
  examples/targets/Configuration API/MSMQ/Simple/Example.cs
  examples/targets/Configuration API/Mail/Buffered/Example.cs
  examples/targets/Configuration API/Mail/Simple/Example.cs
  examples/targets/Configuration API/Memory/Simple/Example.cs
  examples/targets/Configuration API/MethodCall/Simple/Example.cs
  examples/targets/Configuration API/NLogViewer/Simple/Example.cs
  examples/targets/Configuration API/Network/Simple/Example.cs
  examples/targets/Configuration API/Null/Simple/Example.cs
  examples/targets/Configuration API/OutputDebugString/Simple/Example.cs
  examples/targets/Configuration API/PerfCounter/Simple/Example.cs
  examples/targets/Configuration API/PostFilteringWrapper/Simple/Example.cs
  examples/targets/Configuration API/RandomizeGroup/Simple/Example.cs
  examples/targets/Configuration API/RepeatingWrapper/Simple/Example.cs
  examples/targets/Configuration API/RetryingWrapper/Simple/Example.cs
  examples/targets/Configuration API/RoundRobinGroup/Simple/Example.cs
  examples/targets/Configuration API/SplitGroup/Simple/Example.cs
  examples/targets/Configuration API/Trace/Simple/Example.cs
  examples/targets/Configuration API/WebService/Simple/Example.cs
Labels: documentation, size/L

#5771 NLog.Targets.AtomicFile.Tests - Changed to dynamic sequence archive
  src/NLog/Targets/FileArchiveHandlers/BaseFileArchiveHandler.cs
  tests/NLog.Targets.AtomicFile.Tests/ConcurrentWritesMultiProcessTests.cs
Labels: unit-tests, file-target, size/S, file-archiving

#5775 ObjectReflectionCache - PropertyValue with exception handler for AOT
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
Labels: enhancement, size/S

#5776 ObjectReflectionCache - PropertyValue with exception handler for AOT
  src/NLog/Internal/ObjectReflectionCache.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
Labels: enhancement, size/S

#5781 JsonLayout - Changed SuppressSpaces to default true
  src/NLog/Layouts/JSON/JsonArrayLayout.cs
  src/NLog/Layouts/JSON/JsonLayout.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  src/NLog/Targets/DefaultJsonSerializer.cs
  src/NLog/Targets/JsonSerializeOptions.cs
  tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs
  tests/NLog.UnitTests/LayoutRenderers/VariableLayoutRendererTests.cs
  tests/NLog.UnitTests/Layouts/CompoundLayoutTests.cs
  tests/NLog.UnitTests/Layouts/JsonArrayLayoutTests.cs
  tests/NLog.UnitTests/Layouts/JsonLayoutTests.cs
  tests/NLog.UnitTests/LogMessageFormatterTests.cs
  tests/NLog.UnitTests/LoggerTests.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerClassTests.cs
  tests/NLog.UnitTests/Targets/DefaultJsonSerializerTestsBase.cs
Labels: json / json-layout, breaking behavior change, size/L, new default (breaking)

#5782 XmlLoggingConfiguration - AutoReload available by default as before
  build.ps1
  run-tests.ps1
  src/NLog.AutoReloadConfig/NLog.AutoReloadConfig.csproj
  src/NLog.AutoReloadConfig/README.md
  src/NLog.AutoReloadConfig/SetupBuilderAutoReloadExtensions.cs
  src/NLog.sln
  src/NLog/Config/LoggingConfiguration.cs
  src/NLog/Config/XmlLoggingConfiguration.cs
  src/NLog/Internal/MultiFileWatcher.cs
  tests/NLog.AutoReloadConfig.Tests/NLog.AutoReloadConfig.Tests.csproj
  tests/NLog.UnitTests/Config/AutoReloadTests.cs
  tests/NLog.UnitTests/Config/ReloadTests.cs
  tests/NLog.UnitTests/ConfigFileLocatorTests.cs
Labels: breaking change, refactoring, size/XL

#5785 Remove NLog.Contrib.ActiveMQ
  packages-and-status.md
Labels: size/XS

#5786 LiteralWithRawValueLayoutRenderer without reflection
  src/NLog/Config/AssemblyExtensionLoader.cs
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Config/AssemblyExtensionTypes.tt
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Layouts/Layout.cs
Labels: refactoring, size/M

#5788 FuncLayoutRenderer without reflection
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Config/AssemblyExtensionTypes.tt
  src/NLog/Layouts/Layout.cs
Labels: refactoring, size/XS

#5787 FuncLayoutRenderer without reflection
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Config/AssemblyExtensionTypes.tt
Labels: refactoring, size/XS

#5789 ConcurrentFileTarget - Removed explicit static constructor
  src/NLog.Targets.ConcurrentFile/ConcurrentFileTarget.cs
Labels: file-target, refactoring, size/S

#5791 Removed obsolete FactoryHelper since not referenced
  src/NLog/Internal/FactoryHelper.cs
Labels: refactoring, size/M

#5793 TargetWithContext - Reduce allocation for RenderLogEvent when SimpleLayout
  src/NLog/LayoutRenderers/MessageLayoutRenderer.cs
  src/NLog/Layouts/SimpleLayout.cs
  src/NLog/Layouts/Typed/Layout.cs
  src/NLog/Targets/Target.cs
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.UnitTests/ApiTests.cs
  tests/NLog.UnitTests/Targets/TargetWithContextTest.cs
Labels: performance, size/M

#5795 ConditionLayoutExpression - Skip caching result of Inner Layout.Render
  src/NLog/Conditions/ConditionLayoutExpression.cs
  src/NLog/Internal/FilePathLayout.cs
  src/NLog/Layouts/LayoutWithHeaderAndFooter.cs
  src/NLog/Targets/TargetWithContext.cs
Labels: performance, size/XS

#5794 Layout Render without caching, as handled by Precalculate
  src/NLog/Filters/WhenContainsFilter.cs
  src/NLog/Filters/WhenEqualFilter.cs
  src/NLog/Filters/WhenNotContainsFilter.cs
  src/NLog/Filters/WhenNotEqualFilter.cs
  src/NLog/Filters/WhenRepeatedFilter.cs
  src/NLog/Internal/AppendBuilderCreator.cs
  src/NLog/LayoutRenderers/CounterLayoutRenderer.cs
  src/NLog/LayoutRenderers/EnvironmentLayoutRenderer.cs
  src/NLog/LayoutRenderers/LayoutRenderer.cs
  src/NLog/LayoutRenderers/MessageLayoutRenderer.cs
  src/NLog/LayoutRenderers/ScopeContextIndentLayoutRenderer.cs
  src/NLog/LayoutRenderers/Wrappers/CachedLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/ObjectPathRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WhenEmptyLayoutRendererWrapper.cs
  src/NLog/LayoutRenderers/Wrappers/WrapperLayoutRendererBase.cs
  src/NLog/Layouts/Layout.cs
  src/NLog/Layouts/SimpleLayout.cs
  src/NLog/Layouts/Typed/Layout.cs
  src/NLog/Layouts/Typed/ValueTypeLayoutInfo.cs
  tests/NLog.UnitTests/Layouts/CsvLayoutTests.cs
  tests/NLog.UnitTests/Layouts/SimpleLayoutOutputTests.cs
Labels: performance, breaking behavior change, size/L

#5762 Removed static constructor from LogFactory
  src/NLog/LogFactory.cs
  tests/NLog.UnitTests/ApiTests.cs
Labels: refactoring, size/L, platform support

#5774 Log4JXmlEventLayout using Nlog XmlLayout
  src/NLog.Targets.Network/Layouts/Log4JXmlEventLayout.cs
  src/NLog.Targets.Network/Layouts/Log4JXmlEventLayoutRenderer.cs
  src/NLog.Targets.Network/Layouts/Log4JXmlEventParameter.cs
  src/NLog.Targets.Network/Targets/ChainsawTarget.cs
  src/NLog/Config/ConfigurationItemFactory.cs
  src/NLog/Internal/XmlHelper.cs
  src/NLog/LayoutRenderers/Wrappers/XmlEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/XML/XmlElement.cs
  tests/NLog.Targets.Network.Tests/Log4JXmlTests.cs
Labels: breaking change, size/XL, platform support, log4jxml-layout

#5796 Log4JXmlEventLayout - Inherit from CompoundLayout to optimize for async
  src/NLog.Targets.Network/Internal/XmlHelpers.cs
  src/NLog.Targets.Network/Layouts/Log4JXmlEventLayout.cs
  src/NLog.Targets.Network/Layouts/Log4JXmlEventParameter.cs
  src/NLog.Targets.Network/NLog.Targets.Network.csproj
  src/NLog.Targets.Network/Targets/ChainsawTarget.cs
  src/NLog.Targets.Network/Targets/NetworkTarget.cs
  src/NLog/LayoutRenderers/Wrappers/XmlEncodeLayoutRendererWrapper.cs
  src/NLog/Layouts/XML/XmlElement.cs
  src/NLog/Layouts/XML/XmlElementBase.cs
  src/NLog/Targets/TargetWithContext.cs
  tests/NLog.Database.Tests/NLog.Database.Tests.csproj
  tests/NLog.RegEx.Tests/NLog.RegEx.Tests.csproj
  tests/NLog.Targets.AtomicFile.Tests/NLog.Targets.AtomicFile.Tests.csproj
  tests/NLog.Targets.ConcurrentFile.Tests/NLog.Targets.ConcurrentFile.Tests.csproj
  tests/NLog.Targets.GZipFile.Tests/NLog.Targets.GZipFile.Tests.csproj
  tests/NLog.Targets.Mail.Tests/NLog.Targets.Mail.Tests.csproj
  tests/NLog.Targets.Network.Tests/Log4JXmlTests.cs
  tests/NLog.Targets.Network.Tests/NLog.Targets.Network.Tests.csproj
  tests/NLog.Targets.Trace.Tests/NLog.Targets.Trace.Tests.csproj
  tests/NLog.Targets.WebService.Tests/NLog.Targets.WebService.Tests.csproj
  tests/NLog.UnitTests/NLog.UnitTests.csproj
  tests/NLog.WindowsRegistry.Tests/NLog.WindowsRegistry.Tests.csproj
Labels: size/XL, log4jxml-layout

#5798 ConfigurationItemFactory - Restored RegisterItemsFromAssembly for NLog.Web
  src/NLog/Config/AssemblyExtensionLoader.cs
  src/NLog/Config/ConfigurationItemFactory.cs
Labels: refactoring, size/M, platform support

#5799 FileTarget - Fixed legacy ArchiveFileName to allow File.Move with dynamic-archive-logic
  src/NLog/Targets/FileArchiveHandlers/LegacyArchiveFileNameHandler.cs
  tests/NLog.UnitTests/Targets/FileTargetTests.cs
Labels: file-target, refactoring, size/M, file-archiving

#5797 NLog 6.0 preview 1 with strong-version 6.0.0.0
  CHANGELOG.md
  appveyor.yml
  build.ps1
  src/NLog.Database/NLog.Database.csproj
  src/NLog.OutputDebugString/NLog.OutputDebugString.csproj
  src/NLog.RegEx/NLog.RegEx.csproj
  src/NLog.Targets.AtomicFile/NLog.Targets.AtomicFile.csproj
  src/NLog.Targets.ConcurrentFile/NLog.Targets.ConcurrentFile.csproj
  src/NLog.Targets.GZipFile/NLog.Targets.GZipFile.csproj
  src/NLog.Targets.Mail/NLog.Targets.Mail.csproj
  src/NLog.Targets.Network/NLog.Targets.Network.csproj
  src/NLog.Targets.Trace/NLog.Targets.Trace.csproj
  src/NLog.Targets.WebService/NLog.Targets.WebService.csproj
  src/NLog.WindowsEventLog/NLog.WindowsEventLog.csproj
  src/NLog.WindowsRegistry/NLog.WindowsRegistry.csproj
  src/NLog/Config/Factory.cs
  src/NLog/NLog.csproj
  src/NLog/Targets/TargetWithContext.cs
Labels: version, size/L
