Repository NLog/NLog, pull requests merged in 2025-08, with the labels that each got.

#5953 NLog.Targets.Network nuget-package links
  src/NLog.Targets.Network/Internal/INetworkInterfaceRetriever.cs
  src/NLog.Targets.Network/Internal/NetworkInterfaceRetriever.cs
  src/NLog.Targets.Network/LayoutRenderers/LocalIpAddressLayoutRenderer.cs
  src/NLog.Targets.Network/NLog.Targets.Network.csproj
  tests/NLog.Targets.ConcurrentFile.Tests/ConcurrentFileTargetTests.cs
  tests/NLog.UnitTests/Properties/AssemblyInfo.cs
Labels: network/NLogViewer-target, size/S

#5955 LogMessageTemplateFormatter - Also use IValueFormatter for positional templates
  src/NLog/Config/LoggingConfigurationParser.cs
  src/NLog/Internal/LogMessageTemplateFormatter.cs
  src/NLog/MessageTemplates/ValueFormatter.cs
  tests/NLog.UnitTests/MessageTemplates/RendererTests.cs
  tests/NLog.UnitTests/MessageTemplates/ValueFormatterTest.cs
Labels: enhancement, size/L

#5959 Version 6.0.3
  CHANGELOG.md
  build.ps1
  src/NLog/Config/Factory.cs
  src/NLog/NLog.csproj
Labels: version, size/L

#5961 Fixed README.md for NLog.Targets.AtomicFile
  src/NLog.Targets.AtomicFile/NLog.Targets.AtomicFile.csproj
  src/NLog.Targets.GZipFile/NLog.Targets.GZipFile.csproj
Labels: enhancement, size/XS

#5967 Add Benchmark project and fix boxing issue in ConsoleRowHighlightingRule
  src/NLog.Benchmarks/ColoredConsoleTargetBenchmark.cs
  src/NLog.Benchmarks/NLog.Benchmarks.csproj
  src/NLog.Benchmarks/Program.cs
  src/NLog.sln
  src/NLog/Conditions/ConditionMethodExpression.cs
Labels: performance, console-target, size/L

#5971 ColoredConsoleTarget - Fix boxing issue in ConsoleRowHighlightingRule
  src/NLog/Conditions/ConditionMethodExpression.cs
  src/NLog/Config/AssemblyExtensionTypes.cs
  src/NLog/Config/AssemblyExtensionTypes.tt
  src/NLog/SetupLoadConfigurationExtensions.cs
Labels: performance, size/M

#5977 Improve nullability ergonomics for `ConditionExpression` cast
  src/NLog/Conditions/ConditionExpression.cs
Labels: enhancement, size/XS

#5980 FileTarget - Extend InternalLogger output with archive cleanup reason
  src/NLog/Targets/FileArchiveHandlers/BaseFileArchiveHandler.cs
  src/NLog/Targets/FileArchiveHandlers/LegacyArchiveFileNameHandler.cs
  src/NLog/Targets/FileArchiveHandlers/RollingArchiveFileHandler.cs
  src/NLog/Targets/FileArchiveHandlers/ZeroFileArchiveHandler.cs
Labels: size/M

#5982 SimpleLayout - Implicit operator with NotNullIfNotNull
  src/NLog/Layouts/SimpleLayout.cs
Labels: enhancement, size/XS
